// Code generated by cahsync from cc-arch-hands 0.16.1; DO NOT EDIT.
package cliprovider

const cahVersion = "0.16.1"

// cahSpecs contains the generated model catalog.
// Constructor adapters preserve current signatures and set per-model metadata.
func cahClaudeSpec(id, display, arg string, ctx int64, efforts []string) CLISpec {
	s := claudeSpec(id, display, arg, ctx)
	s.EffortLevels = efforts
	return s
}
func cahCodexSpec(id, display, arg string, ctx int64, efforts []string) CLISpec {
	s := codexSpec(id, display, arg, efforts)
	s.ContextWindow = ctx
	return s
}

var cahSpecs = []CLISpec{
	cahClaudeSpec("cli-claude-fable-5", "Fable 5 (1M)", "claude-fable-5", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-fable-5-1", "Fable (top, 1M)", "claude-fable-5-1", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-haiku-4-5", "Haiku 4.5 (200k)", "claude-haiku-4-5", 200000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-haiku-5-5", "Haiku (top, 1M)", "claude-haiku-5-5", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-opus-4-6", "Opus 4.6 (1M)", "claude-opus-4-6", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-opus-4-7", "Opus 4.7 (1M)", "claude-opus-4-7", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-opus-4-8", "Opus 4.8 (1M)", "claude-opus-4-8", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-opus-5-1m", "Opus 5 (1M)", "claude-opus-5[1m]", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-opus-5-5", "Opus (top, 1M)", "claude-opus-5-5", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-sonnet-4-5", "Sonnet 4.5 (200k)", "claude-sonnet-4-5", 200000, []string{"low", "medium", "high"}),
	cahClaudeSpec("cli-claude-sonnet-4-6", "Sonnet 4.6 (200k)", "claude-sonnet-4-6", 200000, []string{"low", "medium", "high", "max"}),
	cahClaudeSpec("cli-claude-sonnet-5-1m", "Sonnet 5 (1M)", "claude-sonnet-5[1m]", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahClaudeSpec("cli-claude-sonnet-5-5", "Sonnet (top, 1M)", "claude-sonnet-5-5", 1000000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahCodexSpec("cli-codex-gpt-6-1-sol", "Sol 6.1", "gpt-6.1-sol", 272000, []string{"low", "medium", "high", "xhigh", "max", "ultra"}),
	cahCodexSpec("cli-codex-gpt-6-astra", "Astra", "gpt-6-astra", 272000, []string{"low", "medium", "high", "xhigh", "max", "ultra"}),
	cahCodexSpec("cli-codex-gpt-6-luna", "Luna", "gpt-6-luna", 272000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahCodexSpec("cli-codex-gpt-6-sol", "Sol 6", "gpt-6-sol", 272000, []string{"low", "medium", "high", "xhigh", "max", "ultra"}),
	cahCodexSpec("cli-codex-luna", "Luna 5.6", "gpt-5.6-luna", 272000, []string{"low", "medium", "high", "xhigh", "max"}),
	cahCodexSpec("cli-codex-sol", "Sol 5.6", "gpt-5.6-sol", 272000, []string{"low", "medium", "high", "xhigh", "max", "ultra"}),
	cahCodexSpec("cli-codex-terra", "Terra", "gpt-5.6-terra", 272000, []string{"low", "medium", "high", "xhigh", "max", "ultra"}),
}
