package cliprovider

import (
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// Revert-check: generated entries appear exactly once and every stored compatibility slug remains registered.
func TestCAHCatalogUniqueAndCompatible(t *testing.T) {
	seen := map[string]CLISpec{}
	for _, spec := range All {
		_, duplicate := seen[spec.ModelID]
		require.False(t, duplicate, spec.ModelID)
		seen[spec.ModelID] = spec
	}
	require.NotEmpty(t, cahSpecs)
	binaries := map[string]bool{}
	for _, spec := range cahSpecs {
		require.NotEmpty(t, spec.ModelID)
		require.NotEmpty(t, spec.ModelName)
		require.Contains(t, []string{"claude", "codex"}, spec.Binary)
		binaries[spec.Binary] = true
		require.Positive(t, spec.ContextWindow, spec.ModelID)
		require.NotNil(t, spec.BuildArgs, spec.ModelID)
		require.NotEmpty(t, spec.EffortLevels, spec.ModelID)
		efforts := map[string]bool{}
		for _, level := range spec.EffortLevels {
			require.NotEmpty(t, level, spec.ModelID)
			require.False(t, efforts[level], "%s: duplicate effort %s", spec.ModelID, level)
			efforts[level] = true
		}
		require.Contains(t, seen, spec.ModelID)
		require.Equal(t, spec.ModelName, seen[spec.ModelID].ModelName)
		require.Equal(t, spec.EffortLevels, seen[spec.ModelID].EffortLevels)
		require.Equal(t, spec.Binary, seen[spec.ModelID].Binary)
		require.Equal(t, spec.ContextWindow, seen[spec.ModelID].ContextWindow)
	}
	require.True(t, binaries["claude"])
	require.True(t, binaries["codex"])
	// Only hand-written slugs; cah-derived ids are covered by the drift and resolver tests.
	for _, id := range []string{
		"cli-claude-opus", "cli-claude-sonnet", "cli-claude-haiku", "cli-claude-fable",
		"cli-codex", "cli-codex-gpt-5-2", "cli-codex-max", "cli-codex-mini",
		"cli-codex-gpt-5-5", "cli-codex-gpt-5-4", "cli-codex-gpt-5-2-base",
		"cli-gemini-flash", "cli-gemini-flash-35", "cli-gemini-flash-lite", "cli-gemini-pro", "cli-qwen",
	} {
		require.Contains(t, seen, id)
	}
	data, err := os.ReadFile("models_cah_gen.go")
	require.NoError(t, err)
	require.True(t, strings.HasPrefix(string(data), "// Code generated by cahsync from cc-arch-hands "+cahVersion+"; DO NOT EDIT.\n"))
}
