// Run: the per-session dispatcher. It claims the busy reservation and the
// inter-process session lock once per call, then loops runTurn over queued
// work until the mailbox drains.
package agent

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"charm.land/fantasy"

	"github.com/charmbracelet/crush/internal/message"
	"github.com/charmbracelet/crush/internal/session"
)

// Run executes one or more agent turns for call.SessionID. It owns the
// session's busy reservation and the inter-process OS lock for the whole
// call, including any turns generated by queue-drain (a queued message
// picked up after the current turn ends, or after a mid-turn cancel, or
// after an in-turn /compact). Those used to be handled by Run calling
// itself recursively from three places deep in its own body — which, since
// the OS lock (see below) is not reentrant even within one process, deadlocked
// against itself: the recursive call tried to acquire a lock its own parent
// stack frame was still holding (the parent's `defer ipcLock.Release()`
// hadn't run yet), and got rejected with "already in use". runTurn below is
// the extracted single-turn body; Run just loops it.
func (a *sessionAgent) Run(ctx context.Context, call SessionAgentCall) (*fantasy.AgentResult, error) {
	if call.Prompt == "" && !message.ContainsTextAttachment(call.Attachments) {
		return nil, ErrEmptyPrompt
	}
	if call.SessionID == "" {
		return nil, ErrSessionMissing
	}
	// Refuse outright once shutdown has begun (closing review, blocker 1).
	// Checked BEFORE tryReserveSession so no ownership is claimed and no
	// mailbox is created: the per-mailbox `stopped` latch can only stop an
	// existing turn loop, and CancelAll's sweep cannot reach a mailbox that
	// does not exist yet. See the shuttingDown field's doc for the call
	// paths that reach here after the sweep. This check is combined with
	// runWg registration under admitMu (tryAdmitRunWg) to close the
	// P1-1 race: without the mutex, a concurrent CancelAll could set
	// shuttingDown and start its Wait goroutine while the counter was
	// still 0, letting Wait return before Add(1) landed (panics or
	// admits work after "shutdown complete").
	if !a.tryAdmitRunWg() {
		return nil, ErrAgentShuttingDown
	}
	defer a.runWg.Done()

	// runCtx/runCancel span the WHOLE dispatcher (every turn + every
	// preamble). The loop derives a per-turn turnCtx from runCtx (#284) so
	// that cancelling a single turn's preamble — via InterruptAndReplace —
	// does NOT kill the dispatcher: runCancel is never the target of an
	// interrupt; it is invoked only by this defer and by CancelAll's
	// hardStop. tryReserveSession stores runCancel as dispatcherCancel, the
	// mailbox's durable fallback when no live generation cancel exists yet.
	runCtx, runCancel := context.WithCancel(ctx)
	defer runCancel()

	// Atomically check-and-claim the busy slot via the session's mailbox
	// (mailbox.submit, design §3). If someone else already owns the
	// session, submit has already appended call to the mailbox's own
	// pending queue under the same lock — nothing left to do here.
	became, epoch := a.tryReserveSession(call, runCancel)
	if !became {
		return nil, nil
	}
	// We now own call.SessionID's reservation, under ownership era `epoch`,
	// for the entire loop below, including every queue-drain turn. Released
	// exactly once, whichever way the loop ends, via THIS defer.
	//
	// Round 9 review, BLOCKER-2: this defer fires on EVERY return from Run
	// — not just the pre-loop bail-out paths its old doc comment claimed —
	// including after runTurn's own final drain already released the era
	// (the common, correct case) and after any early-return inside runTurn
	// that skipped its own drain entirely (an error path). It must
	// therefore be safe to call unconditionally on every exit.
	//
	// This defer uses abandonOwnershipWithHandoff to ensure that any work
	// left in the mailbox after a non-cancel error gets a runner started via
	// detached runs, fixing P0-1 and P1-1. The OS lock (if any) will be
	// released before this defer runs — lk is acquired below and this defer
	// releases it first to avoid the HIGH-1 window where mbIdle becomes true
	// while the lock is still held.
	defer func() {
		a.abandonOwnershipWithHandoff(call.SessionID, epoch)
	}()

	// Inter-process session lock. The reservation above is per-process (an
	// in-memory map); two crush processes wouldn't see each other's busy
	// state and could both start streaming into the same session id — the
	// accidental-double-spawn race documented in the parallel-process audit
	// (#6 CRITICAL). The OS-level lock auto-releases on process death, so a
	// crashed holder never leaves a stuck session id.
	//
	// Sub-agents are NOT exempt: a sub-agent runs under its own CHILD
	// session id (parentMessageID$$toolCallID, see
	// session.CreateAgentToolSessionID), which is a completely different
	// id from the parent's call.SessionID. The parent's lock only covers
	// the parent's own session id — the child id is otherwise unlocked,
	// so a second crush process opening that exact child session (e.g.
	// via `crush sessions pick`/`resume`) could acquire it and stream into
	// it concurrently with this in-process sub-agent run. Locking must
	// happen per session id, regardless of isSubAgent.
	//
	// This does not introduce false-positive "already in use" errors for
	// legitimate same-process reentrancy (e.g. the "agent" tool's
	// resume_session_id path racing a still-active run on that same child
	// id): the in-process reservation above (tryReserveSession/mailbox.submit)
	// already queues that case behind the current in-process owner and
	// returns before this point is ever reached — AS LONG AS the mailbox
	// still reports that owner as busy. Round 11 review, HIGH-1: before that
	// fix, drainOrReleaseMerged could flip the mailbox to mbIdle (making
	// IsSessionBusy/tryReserveSession see "not busy") strictly BEFORE this
	// same process's own prior Run() call had actually released ITS lk —
	// runTurn's deferred wg.Wait() and the rest of the call stack unwinding
	// still hadn't run. A second same-process Run() call for the identical
	// session id could then become the new in-process owner (submit()
	// legitimately returns becomeOwner=true) and reach TryAcquireSessionLock
	// here while the OS lock was still, transiently, held by its own
	// process's outgoing turn — a same-process false "already in use".
	// drainOrReleaseMerged now releases lk inside the same mailbox critical
	// section that flips state to mbIdle (see mailbox.drainOrReleaseFinal),
	// so "not busy" and "OS lock free" become true together — this window
	// is closed. Two sub-agent invocations
	// spawned in parallel by fantasy's ParallelAgentTool likewise never
	// collide here — each gets a distinct toolCallID and therefore a
	// distinct child session id.
	//
	// Acquired ONCE for the whole loop below — every queue-drain turn reuses
	// this same lock instead of each one acquiring (and needing to release)
	// its own, which is what made the old recursive-Run() shape deadlock.
	// The lock is released by the defer above (abandonOwnershipWithHandoff)
	// before Run returns to avoid the HIGH-1 window.
	var lk *session.SessionLock
	if a.dataDir != "" {
		var lockErr error
		lk, lockErr = session.TryAcquireSessionLockWithOptions(a.dataDir, call.SessionID, a.lockOptions...)
		if lockErr != nil {
			var busyErr *session.SessionLockBusyError
			if errors.As(lockErr, &busyErr) {
				slog.Warn(
					"agent.Run: rejected — session locked by another process",
					"session_id", call.SessionID,
					"holder_pid", busyErr.HolderPID,
					"lock_path", busyErr.Path,
				)
				return nil, fmt.Errorf("session %q is already in use: %w", call.SessionID, lockErr)
			}
			// Unidentified error (not "busy") — e.g. permission denied,
			// IO error, or any other failure that isn't "someone else
			// holds this lock". Previously this case logged a warning
			// and continued WITHOUT the inter-process guard, which
			// defeats the whole point: the in-process busy check only
			// protects against races inside this one process, not the
			// cross-process double-spawn this lock exists for. Fail
			// closed instead — refuse to run rather than silently
			// proceed unprotected.
			slog.Error("agent.Run: failed to acquire inter-process session lock, refusing to run unprotected",
				"session_id", call.SessionID, "err", lockErr)
			return nil, fmt.Errorf("session %q: could not acquire session lock: %w", call.SessionID, lockErr)
		}
		// Release the lock in the abandonOwnershipWithHandoff defer above.
		defer func() {
			if lk != nil {
				lk.Release()
			}
		}()
	}

	// Turn loop: replaces the three recursive a.Run(ctx, ...) call sites
	// that used to live inside runTurn's body (cancel-drain, end-of-turn
	// drain, and the /compact drain in runSummarizeBody). Each iteration
	// runs exactly one provider turn; runTurn reports whether another
	// queued call should run next, using the reservation and OS lock
	// acquired once above instead of re-acquiring them. runCtx (not the
	// original ctx) is passed through so runCancel — registered as the
	// busy slot's CancelFunc — actually reaches every turn's genCtx.
	for {
		// Test-only seam (#289): fires strictly after any end-of-turn drain
		// has already released mb.mu and strictly before this iteration's
		// beginGeneration call below re-arms it. nil (a no-op) in every
		// production path — see mailbox.testLoopRearmSeam's own doc for why
		// this exists and what it lets a test do that it otherwise could
		// not: deterministically land a concurrent Cancel() inside the
		// window between a reclaim and the loop's own re-arm, instead of
		// racing the two for the next mb.mu acquisition.
		mb := a.getMailbox(call.SessionID)
		if mb.testLoopRearmSeam != nil {
			mb.testLoopRearmSeam()
		}
		// #307 (P1-2 follow-up): reclaim a same-window replacement BEFORE
		// committing to run `call` — the value the PREVIOUS turn's own drain
		// already decided on. An InterruptAndReplace landing in the
		// inter-turn window (after the previous iteration's turnCancel()
		// above, before this iteration's beginGeneration below —
		// mb.current.cancel is nil for the whole window, exactly where
		// testLoopRearmSeam parks a test) now records mb.replacement and
		// returns a nil cancel instead of falling back to dispatcherCancel
		// (see interruptAndReplace's own doc for why that fallback used to
		// cancel runCtx itself and poison every future turn). Nothing was
		// cancelled, so nothing recovers the replacement automatically —
		// this call is what actually picks it up, swapping it in for `call`
		// so the interrupt's intent takes effect on the very next
		// generation instead of `call` running to completion first and the
		// replacement only surfacing via that turn's own end-of-turn drain.
		// A no-op (returns call unchanged) on every iteration where no
		// interrupt landed in this exact window, which is the overwhelming
		// majority of iterations.
		call = mb.reclaimReplacementOrKeep(call)
		// Per-turn context, derived from runCtx but independently
		// cancelable. An interrupt during this turn's DB preamble (before
		// runTurn creates genCtx) targets THIS cancel — not runCancel — so
		// the dispatcher (this loop, plus runCtx) survives the interrupt and
		// can atomically decide what to do next via runTurn's own
		// drainAfterCancel recovery. Before #284 the loop registered
		// runCancel for the preamble window, so an InterruptAndReplace
		// during the preamble killed the entire dispatcher and the
		// replacement was stranded in the legacy queue with no runner.
		turnCtx, turnCancel := context.WithCancel(runCtx)
		a.activeRequests.Set(call.SessionID, turnCancel)
		// Mirror the activeRequests re-arm into the mailbox's current
		// generation cancel (design §4): Cancel(sessionID) targets
		// mailbox.current.cancel, so it must be populated for the whole
		// preamble (until runTurn swaps in its own per-turn genCtx cancel
		// below). Using turnCancel (not runCancel) is the #284 fix: the
		// preamble is now part of a cancelable generation that is SEPARATE
		// from the durable dispatcher cancel.
		mb.beginGeneration(turnCancel)
		result, next, hasNext, err := a.runTurn(turnCtx, call, lk, epoch, runCancel)
		turnCancel()
		if !hasNext {
			return result, err
		}
		call = next
	}
}
