// Run: the per-session dispatcher. It claims the busy reservation and the
// inter-process session lock once per call, then loops runTurn over queued
// work until the mailbox drains.
package agent

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"charm.land/fantasy"

	"github.com/PHPCraftdream/rush/internal/message"
	"github.com/PHPCraftdream/rush/internal/session"
)

// Run executes one or more agent turns for call.SessionID. It owns the
// session's busy reservation and the inter-process OS lock for the whole
// call, including any turns generated by queue-drain (a queued message
// picked up after the current turn ends, or after a mid-turn cancel, or
// after an in-turn /compact). Those used to be handled by Run calling
// itself recursively from three places deep in its own body — which, since
// the OS lock (see below) is not reentrant even within one process, deadlocked
// against itself: the recursive call tried to acquire a lock its own parent
// stack frame was still holding (the parent's `defer ipcLock.Release()`
// hadn't run yet), and got rejected with "already in use". runTurn below is
// the extracted single-turn body; Run just loops it.
func (a *sessionAgent) Run(ctx context.Context, call SessionAgentCall) (*fantasy.AgentResult, error) {
	if call.Prompt == "" && !message.ContainsTextAttachment(call.Attachments) {
		return nil, ErrEmptyPrompt
	}
	if call.SessionID == "" {
		return nil, ErrSessionMissing
	}
	// Refuse outright once shutdown has begun (closing review, blocker 1).
	// Checked BEFORE tryReserveSession so no ownership is claimed and no
	// mailbox is created: the per-mailbox `stopped` latch can only stop an
	// existing turn loop, and CancelAll's sweep cannot reach a mailbox that
	// does not exist yet. See the shuttingDown field's doc for the call
	// paths that reach here after the sweep. This check is combined with
	// runWg registration under admitMu (tryAdmitRunWg) to close the
	// P1-1 race: without the mutex, a concurrent CancelAll could set
	// shuttingDown and start its Wait goroutine while the counter was
	// still 0, letting Wait return before Add(1) landed (panics or
	// admits work after "shutdown complete").
	if !a.tryAdmitRunWg() {
		return nil, ErrAgentShuttingDown
	}
	defer a.runWg.Done()

	// runCtx/runCancel span the WHOLE dispatcher (every turn + every
	// preamble). The loop derives a per-turn turnCtx from runCtx (#284) so
	// that cancelling a single turn's preamble — via InterruptAndReplace —
	// does NOT kill the dispatcher: runCancel is never the target of an
	// interrupt; it is invoked only by this defer and by CancelAll's
	// hardStop. tryReserveSession stores runCancel as dispatcherCancel, the
	// mailbox's durable fallback when no live generation cancel exists yet.
	runCtx, runCancel := context.WithCancel(ctx)
	defer runCancel()

	// Atomically check-and-claim the busy slot via the session's mailbox
	// (mailbox.submit, design §3). If someone else already owns the
	// session, submit has already appended call to the mailbox's own
	// pending queue under the same lock — nothing left to do here.
	became, epoch := a.tryReserveSession(call, runCancel)
	if !became {
		// R1-4: fail-fast callers (sdk.Client.Run/RunWithCredentials) must
		// get a hard error, not the historical silent queue. The decision
		// is atomic with the ownership check inside mailbox.submit, so a
		// call that loses the race for an idle session errors immediately
		// instead of falling into the queue.
		if call.FailIfSessionBusy {
			return nil, fmt.Errorf("session %q is already processing another request: %w", call.SessionID, ErrSessionBusy)
		}
		return nil, nil
	}
	return a.runOwned(ctx, runCtx, call, epoch, runCancel)
}

// RunWithReservedOwnership executes call using an ownership era ALREADY
// claimed by the caller (via ReserveExclusive/mailbox.beginCompact-shaped
// atomic mbIdle->mbOwned transition), instead of claiming a fresh one via
// tryReserveSession/mailbox.submit.
//
// This exists for task #614 (handleRerunMessage): a caller that must run
// several serving-side operations (cancel the old turn, delete the message
// tail, delete the target message) UNDER exclusive ownership before handing
// off to a fresh turn needs that ownership to survive from the reservation
// all the way through the replacement Run — with no window where the
// mailbox is observably idle in between. Calling the ordinary Run() for the
// handoff would re-invoke tryReserveSession, which only succeeds when the
// mailbox is CURRENTLY mbIdle; since the caller is already the owner (mbOwned
// under `epoch`), that call would misinterpret its own reservation as "busy"
// and silently queue `call` behind itself instead of running it — the mailbox
// has no way to tell "the current owner is submitting its own next turn"
// apart from "a different caller is submitting while owned". Continuing the
// caller's own `epoch` instead of re-reserving is what closes that hole:
// ownership is transferred by CONTINUING the same era, never by dropping it
// and re-acquiring, so there is no instant at which the mailbox is idle and
// a third party could slip in and become owner instead.
//
// reserveCancel is the CancelFunc ReserveExclusive returned — it is tied to
// a short-lived placeholder context that has nothing to do with this turn
// loop's own lifetime, so it is REPLACED FIRST, via mailbox.rebindDispatcher,
// by a fresh runCancel derived from ctx — the actual context this turn loop
// (and every provider call inside it) will run under — and only after that
// rebind succeeds is it invoked, to release the now-superseded placeholder
// context. rebindDispatcher keeps
// mb.epoch/state/current.id untouched, so Cancel(sessionID)/CancelAll landing
// either before or after this swap still target a live, correct CancelFunc
// for the whole hold-to-turn transition; only the specific func changes, not
// the era it belongs to.
//
// THE SINGLE HANDOFF POINT (read this before touching any return path in
// this function): ownership transfers from "this function's responsibility
// to release" to "runOwned's deferred abandonOwnershipWithHandoff is
// responsible" at EXACTLY ONE LINE — the `return a.runOwned(...)` at the
// bottom of this function, call it the handoff line. Every return ABOVE the
// handoff line is this function's own responsibility to release explicitly
// before returning (findings review, task #614 defect 1: four early returns
// here previously fell straight through with no release at all, leaking the
// reservation and permanently wedging the session at mbOwned on any ordinary
// error — e.g. a ContainsTextAttachment/SessionID validation failure or an
// admission-gate rejection during shutdown). Every return AT OR BELOW the
// handoff line is runOwned's responsibility, not this function's — do not
// add a release call after the handoff line, or the reservation would be
// released twice (once here, once by runOwned's defer), corrupting a LATER
// owner's era if one has already started under the bumped epoch.
//
// The ONE exception to "this function releases every early return" is the
// rebindDispatcher failure branch. A failed rebind has TWO distinct
// causes (see mailbox.rebindDispatcher: it returns false when
// `mb.epoch != epoch || mb.state != mbOwned || mb.stopped`):
//
//   - Epoch/state mismatch: the epoch this caller thinks it owns has
//     ALREADY ended (moved on to some other owner, or this era vacated
//     some other way). Calling abandonOwnershipWithHandoff(sessionID,
//     epoch) would present a STALE epoch that its own epoch check (via
//     abandonOwnershipAndPopSubmitted) will correctly refuse as a no-op —
//     so it would not corrupt anything — but it also would not be
//     releasing anything real: the era already isn't ours to release.
//   - Mailbox hard-stopped (mb.stopped, task d4e64288's added clause):
//     the era is STILL ours (epoch and state both match) but the process
//     is shutting down — CancelAll's hardStop sweep has latched stopped
//     and already fired the dispatcher cancel (which for a held
//     reservation is the placeholder reserveCancel). Not releasing HERE
//     does not, and is not meant to, keep the reservation latched: the
//     sole production caller (handleRerunMessage) has a releaseOnBailout
//     defer that fires on this very error and calls ReleaseExclusive
//     with the still-matching epoch one stack frame later — which pops
//     any queued work and durably enqueues it via
//     restartOrphanedWithRetry. That is acceptable (and arguably better
//     than the alternative) because "restart" since task #340 is a row
//     in the durable session_run_queue, NOT a fresh provider turn: the
//     shutdown admission gate (tryAdmitRunWg) refuses any Run the pump
//     might attempt, and App.Shutdown stops the pump before closing the
//     DB. The stopped latch's real teardown protections live in the
//     turn-loop drains (drainAfterCancel, and drainOrReleaseFinal's
//     ENTRY check, which skips the live branches for a stopped mailbox —
//     since #646 its finalize step is latch-blind in effect, treating
//     stopped and non-stopped identically) and in interruptAndReplace's
//     "nobody running" refusal — the abandon-path release is
//     deliberately NOT one of them (task #641 F-4 corrected an earlier version of this
//     paragraph that claimed "every drain refuses on the latch anyway",
//     which was never true of abandonOwnershipAndPopSubmitted). Note:
//     the caller-side release ALSO drains summarizeQueue and spawns
//     `go a.Summarize(context.Background(), ...)`, but Summarize's own
//     admission gate refuses it during shutdown.
//
// For the epoch/state mismatch, calling abandonOwnershipWithHandoff
// there would be dead (stale epoch: a verified no-op). For the stopped
// case it would be redundant rather than wrong — the caller's own
// bailout defer performs the same epoch-matched release one frame later
// — so that branch leaves the release to the caller and cleans up only
// runCancel/reserveCancel, both of which are unconditionally ours
// regardless of mailbox state.
//
// The caller must have obtained (holdCtx, epoch, reserveCancel) from
// ReserveExclusive on call.SessionID's mailbox. The caller must not call
// ReleaseExclusive after the handoff point (once onHandoff has fired),
// because runOwned's defer owns releasing from that point forward. On early
// error returns before the handoff, the caller's armed defer is the intended
// (and on the mb.stopped rebind branch, the ONLY) release mechanism.
//
// onHandoff, if non-nil, is invoked immediately before the handoff to
// runOwned. It is used by callers (e.g. handleRerunMessage) to transfer
// release responsibility exactly when the handoff occurs: the caller's
// defer (which releases on early returns) is disarmed by invoking onHandoff,
// and from that point forward runOwned's defer owns releasing the reservation.
//
// For MOST early returns (before onHandoff fires), this function itself
// releases and the caller's still-armed defer's release is then an
// epoch-mismatched/idle no-op. The EXCEPTION is the mb.stopped rebind
// branch: this function deliberately does NOT release (the epoch still
// matches, the mailbox is still mbOwned with possibly non-empty queues),
// and the caller's later ReleaseExclusive (via its bailout defer) is what
// actually releases and durably enqueues the queued work (proven by
// p641_mbstopped_rebind_test.go).
func (a *sessionAgent) RunWithReservedOwnership(ctx context.Context, call SessionAgentCall, epoch uint64, reserveCancel context.CancelFunc, onHandoff func()) (*fantasy.AgentResult, error) {
	if call.Prompt == "" && !message.ContainsTextAttachment(call.Attachments) {
		// Before the handoff line: this function must release what
		// ReserveExclusive claimed. reserveCancel's placeholder context was
		// never superseded (rebindDispatcher hasn't run yet), so cancel it
		// too, mirroring ReleaseExclusive's own body.
		a.abandonOwnershipWithHandoff(call.SessionID, epoch)
		reserveCancel()
		return nil, ErrEmptyPrompt
	}
	if call.SessionID == "" {
		a.abandonOwnershipWithHandoff(call.SessionID, epoch)
		reserveCancel()
		return nil, ErrSessionMissing
	}
	// Unlike Run, admission (tryAdmitRunWg) and the reservation itself were
	// already handled by the caller's ReserveExclusive call — ReserveExclusive
	// itself does not register with runWg (it is not a turn loop yet), so
	// register this execution now, symmetric with Run's own registration.
	if !a.tryAdmitRunWg() {
		// Shutdown has begun. Still release the reservation this call is
		// holding — shuttingDown only refuses NEW admission, it does not
		// itself release reservations already claimed, and a wedged mbOwned
		// mailbox would make CancelAll's own hardStop sweep (which iterates
		// existing mailboxes) the only thing that could ever clear it.
		// abandonOwnershipWithHandoff is safe to call post-shutdown-latch:
		// it does not consult mb.stopped (deliberately — see the rebind
		// branch below), but "restarting" queued work means durably
		// enqueueing it via restartOrphanedWithRetry, not starting a
		// provider turn — the admission gate refuses any Run during
		// shutdown, and the pump is stopped before the DB closes. With no
		// queued work it just flips the era to mbIdle.
		//
		// Note: abandonOwnershipWithHandoff ALSO unconditionally drains
		// summarizeQueue and spawns `go a.Summarize(context.Background(), ...)`.
		// The Summarize call IS a provider turn attempt, but it is harmless
		// during shutdown because Summarize's own admission gate (tryAdmitRunWg,
		// agent_compaction.go:54-55) refuses it with ErrAgentShuttingDown.
		a.abandonOwnershipWithHandoff(call.SessionID, epoch)
		reserveCancel()
		return nil, ErrAgentShuttingDown
	}
	defer a.runWg.Done()

	// Test-only seam (task #641 F-4): fires strictly after admission
	// succeeded and strictly before rebindDispatcher runs — the exact
	// window a concurrent CancelAll must land in to make the rebind below
	// fail on mb.stopped. nil in every production path.
	if a.testReserveRebindSeam != nil {
		a.testReserveRebindSeam()
	}

	// runCtx/runCancel span the whole dispatcher, exactly like Run's own —
	// see Run's doc for why the turn loop needs its own cancelable context
	// distinct from the caller's ctx.
	runCtx, runCancel := context.WithCancel(ctx)
	defer runCancel()

	mb := a.getMailbox(call.SessionID)
	if !mb.rebindDispatcher(epoch, runCancel) {
		// EXCEPTION to "this function releases every early return" — see the
		// doc paragraph above titled "THE SINGLE HANDOFF POINT": the refusal
		// is either an epoch/state mismatch (the era already isn't ours to
		// release) or a hard-stopped mailbox (shutdown; the release — and
		// the durable enqueue of any queued work — happens one frame later
		// via the caller's releaseOnBailout defer, which see).
		runCancel()
		reserveCancel()
		return nil, fmt.Errorf("agent.RunWithReservedOwnership: reservation for session %q is no longer valid (epoch mismatch or stopped mailbox)", call.SessionID)
	}
	// The placeholder context ReserveExclusive created is superseded by
	// runCtx above (rebindDispatcher already repointed the mailbox at
	// runCancel) — release it now so it doesn't leak.
	reserveCancel()

	// Invoke onHandoff (if non-nil) to transfer release responsibility to
	// runOwned's defer. This is the exact point where the caller's bail-out
	// defer is disarmed.
	if onHandoff != nil {
		onHandoff()
	}

	// HANDOFF LINE: from here on, runOwned's own deferred
	// abandonOwnershipWithHandoff owns releasing this reservation, exactly
	// once, on every path out of runOwned (including panics that unwind
	// through its defer). Nothing after this line may call
	// abandonOwnershipWithHandoff/ReleaseExclusive again for this epoch.
	return a.runOwned(ctx, runCtx, call, epoch, runCancel)
}

// runOwned is Run's body once ownership (epoch) and the dispatcher cancel
// (runCancel) are already established — shared by Run (which claims them
// itself via tryReserveSession) and RunWithReservedOwnership (which reuses
// ones the caller already claimed via ReserveExclusive). ctx is the
// caller-facing context (used for the inter-process lock acquisition log
// fields and as InterruptAndSend-style callers expect); runCtx is the
// cancelable context every turn in the loop derives from.
func (a *sessionAgent) runOwned(ctx, runCtx context.Context, call SessionAgentCall, epoch uint64, runCancel context.CancelFunc) (*fantasy.AgentResult, error) {
	// We now own call.SessionID's reservation, under ownership era `epoch`,
	// for the entire loop below, including every queue-drain turn. Released
	// exactly once, whichever way the loop ends, via THIS defer.
	//
	// Round 9 review, BLOCKER-2: this defer fires on EVERY return from Run
	// — not just the pre-loop bail-out paths its old doc comment claimed —
	// including after runTurn's own final drain already released the era
	// (the common, correct case) and after any early-return inside runTurn
	// that skipped its own drain entirely (an error path). It must
	// therefore be safe to call unconditionally on every exit.
	//
	// This defer uses abandonOwnershipWithHandoff to ensure that any work
	// left in the mailbox after a non-cancel error gets a runner started via
	// detached runs, fixing P0-1 and P1-1. The OS lock (if any) will be
	// released before this defer runs — lk is acquired below and this defer
	// releases it first to avoid the HIGH-1 window where mbIdle becomes true
	// while the lock is still held.
	defer func() {
		a.abandonOwnershipWithHandoff(call.SessionID, epoch)
	}()

	// Inter-process session lock. The reservation above is per-process (an
	// in-memory map); two rush processes wouldn't see each other's busy
	// state and could both start streaming into the same session id — the
	// accidental-double-spawn race documented in the parallel-process audit
	// (#6 CRITICAL). The OS-level lock auto-releases on process death, so a
	// crashed holder never leaves a stuck session id.
	//
	// Sub-agents are NOT exempt: a sub-agent runs under its own CHILD
	// session id (parentMessageID$$toolCallID, see
	// session.CreateAgentToolSessionID), which is a completely different
	// id from the parent's call.SessionID. The parent's lock only covers
	// the parent's own session id — the child id is otherwise unlocked,
	// so a second rush process opening that exact child session (e.g.
	// via `rush sessions pick`/`resume`) could acquire it and stream into
	// it concurrently with this in-process sub-agent run. Locking must
	// happen per session id, regardless of isSubAgent.
	//
	// This does not introduce false-positive "already in use" errors for
	// legitimate same-process reentrancy (e.g. the "agent" tool's
	// resume_session_id path racing a still-active run on that same child
	// id): the in-process reservation above (tryReserveSession/mailbox.submit)
	// already queues that case behind the current in-process owner and
	// returns before this point is ever reached — AS LONG AS the mailbox
	// still reports that owner as busy. Round 11 review, HIGH-1: before that
	// fix, drainOrReleaseMerged could flip the mailbox to mbIdle (making
	// IsSessionBusy/tryReserveSession see "not busy") strictly BEFORE this
	// same process's own prior Run() call had actually released ITS lk —
	// runTurn's deferred wg.Wait() and the rest of the call stack unwinding
	// still hadn't run. A second same-process Run() call for the identical
	// session id could then become the new in-process owner (submit()
	// legitimately returns becomeOwner=true) and reach TryAcquireSessionLock
	// here while the OS lock was still, transiently, held by its own
	// process's outgoing turn — a same-process false "already in use".
	// drainOrReleaseMerged now releases lk inside the same mailbox critical
	// section that flips state to mbIdle (see mailbox.drainOrReleaseFinal),
	// so "not busy" and "OS lock free" become true together — this window
	// is closed. Two sub-agent invocations
	// spawned in parallel by fantasy's ParallelAgentTool likewise never
	// collide here — each gets a distinct toolCallID and therefore a
	// distinct child session id.
	//
	// Acquired ONCE for the whole loop below — every queue-drain turn reuses
	// this same lock instead of each one acquiring (and needing to release)
	// its own, which is what made the old recursive-Run() shape deadlock.
	// The lock is released by the defer above (abandonOwnershipWithHandoff)
	// before Run returns to avoid the HIGH-1 window.
	var lk *session.SessionLock
	if a.dataDir != "" {
		var lockErr error
		lk, lockErr = session.TryAcquireSessionLockWithOptions(a.dataDir, call.SessionID, a.lockOptions...)
		if lockErr != nil {
			var busyErr *session.SessionLockBusyError
			if errors.As(lockErr, &busyErr) {
				slog.Warn(
					"agent.Run: rejected — session locked by another process",
					"session_id", call.SessionID,
					"holder_pid", busyErr.HolderPID,
					"lock_path", busyErr.Path,
				)
				return nil, fmt.Errorf("session %q is already in use: %w", call.SessionID, lockErr)
			}
			// Unidentified error (not "busy") — e.g. permission denied,
			// IO error, or any other failure that isn't "someone else
			// holds this lock". Previously this case logged a warning
			// and continued WITHOUT the inter-process guard, which
			// defeats the whole point: the in-process busy check only
			// protects against races inside this one process, not the
			// cross-process double-spawn this lock exists for. Fail
			// closed instead — refuse to run rather than silently
			// proceed unprotected.
			slog.Error("agent.Run: failed to acquire inter-process session lock, refusing to run unprotected",
				"session_id", call.SessionID, "err", lockErr)
			return nil, fmt.Errorf("session %q: could not acquire session lock: %w", call.SessionID, lockErr)
		}
		// Release the lock in the abandonOwnershipWithHandoff defer above.
		defer func() {
			if lk != nil {
				lk.Release()
			}
		}()
	}

	// Turn loop: replaces the three recursive a.Run(ctx, ...) call sites
	// that used to live inside runTurn's body (cancel-drain, end-of-turn
	// drain, and the /compact drain in runSummarizeBody). Each iteration
	// runs exactly one provider turn; runTurn reports whether another
	// queued call should run next, using the reservation and OS lock
	// acquired once above instead of re-acquiring them. runCtx (not the
	// original ctx) is passed through so runCancel — registered as the
	// busy slot's CancelFunc — actually reaches every turn's genCtx.
	for {
		// Test-only seam (#289): fires strictly after any end-of-turn drain
		// has already released mb.mu and strictly before this iteration's
		// beginGeneration call below re-arms it. nil (a no-op) in every
		// production path — see mailbox.testLoopRearmSeam's own doc for why
		// this exists and what it lets a test do that it otherwise could
		// not: deterministically land a concurrent Cancel() inside the
		// window between a reclaim and the loop's own re-arm, instead of
		// racing the two for the next mb.mu acquisition.
		mb := a.getMailbox(call.SessionID)
		if mb.testLoopRearmSeam != nil {
			mb.testLoopRearmSeam()
		}
		// #307 (P1-2 follow-up): reclaim a same-window replacement BEFORE
		// committing to run `call` — the value the PREVIOUS turn's own drain
		// already decided on. An InterruptAndReplace landing in the
		// inter-turn window (after the previous iteration's turnCancel()
		// above, before this iteration's beginGeneration below —
		// mb.current.cancel is nil for the whole window, exactly where
		// testLoopRearmSeam parks a test) now records mb.replacement and
		// returns a nil cancel instead of falling back to dispatcherCancel
		// (see interruptAndReplace's own doc for why that fallback used to
		// cancel runCtx itself and poison every future turn). Nothing was
		// cancelled, so nothing recovers the replacement automatically —
		// this call is what actually picks it up, swapping it in for `call`
		// so the interrupt's intent takes effect on the very next
		// generation instead of `call` running to completion first and the
		// replacement only surfacing via that turn's own end-of-turn drain.
		// A no-op (returns call unchanged) on every iteration where no
		// interrupt landed in this exact window, which is the overwhelming
		// majority of iterations.
		call = mb.reclaimReplacementOrKeep(call)
		// Per-turn context, derived from runCtx but independently
		// cancelable. An interrupt during this turn's DB preamble (before
		// runTurn creates genCtx) targets THIS cancel — not runCancel — so
		// the dispatcher (this loop, plus runCtx) survives the interrupt and
		// can atomically decide what to do next via runTurn's own
		// drainAfterCancel recovery. Before #284 the loop registered
		// runCancel for the preamble window, so an InterruptAndReplace
		// during the preamble killed the entire dispatcher and the
		// replacement was stranded in the legacy queue with no runner.
		turnCtx, turnCancel := context.WithCancel(runCtx)
		a.activeRequests.Set(call.SessionID, turnCancel)
		// Mirror the activeRequests re-arm into the mailbox's current
		// generation cancel (design §4): Cancel(sessionID) targets
		// mailbox.current.cancel, so it must be populated for the whole
		// preamble (until runTurn swaps in its own per-turn genCtx cancel
		// below). Using turnCancel (not runCancel) is the #284 fix: the
		// preamble is now part of a cancelable generation that is SEPARATE
		// from the durable dispatcher cancel.
		mb.beginGeneration(turnCancel)
		result, next, hasNext, err := a.runTurn(turnCtx, call, lk, epoch, runCancel)
		turnCancel()
		if !hasNext {
			return result, err
		}
		call = next
	}
}
