/**
 * Reasoning effort end-to-end UI tests.
 *
 * Tests for the reasoning effort control feature:
 * 1. Effort controls are visible only for CLI Claude models.
 * 2. Clicking the increase/decrease buttons cycles through effort levels: low → medium → high → max → low.
 * 3. The effort level is persisted in the session (survives page reload).
 * 4. Clicking effort controls sends set_session_models with the correct reasoning_effort.
 * 5. The effort badge is displayed next to the model name in assistant messages, driven by
 *    the real server→wire payload (generated by a temporary `go test -overlay` probe over
 *    `toMessageWire`), not a hand-written mock field.
 */

import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  setupMockWS,
  sendMockWSMessage,
  waitForWSSend,
} from "./helpers/mock-ws";
import { makeSession, makeConfig } from "./helpers/fixtures";

// ── Real wire payload generation for effort badge test ───────────────────────────

// Spec files load as ES modules ("type": "module"), where __dirname is
// undefined — derive the repo root from this module's URL instead.
// NB: resolve() is string-path math, so the FIRST ".." cancels the filename,
// then one more per directory: web/tests/reasoning-effort.spec.ts needs
// three ".." to reach the repo root that holds go.mod.
const REPO_ROOT = resolve(fileURLToPath(import.meta.url), "..", "..", "..");

const PROBE_SRC = `package server

import (
	"encoding/json"
	"testing"

	"github.com/charmbracelet/crush/internal/message"
)

// TestZZEffortWireProbe marshals a real toMessageWire conversion and prints
// the exact JSON the browser would receive on a message_created broadcast.
// It FAILS when message.ReasoningEffort does not survive the wire, so the
// Playwright spec consuming its output cannot pass against a wire that
// dropped the field.
func TestZZEffortWireProbe(t *testing.T) {
	m := message.Message{
		ID:              "resp-max",
		Role:            message.Assistant,
		SessionID:       "test-session-reasoning",
		Parts:           []message.ContentPart{message.TextContent{Text: "Response with max effort"}},
		Model:           "cli-claude-opus",
		Provider:        "local-cli",
		ReasoningEffort: "max",
	}
	b, err := json.Marshal(toMessageWire(m))
	if err != nil {
		t.Fatal(err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(b, &decoded); err != nil {
		t.Fatal(err)
	}
	if decoded["ReasoningEffort"] != "max" {
		t.Errorf("ReasoningEffort missing from wire JSON: %s", b)
	}
	t.Logf("ZZWIRE:%s", b)
}
`;

function realWireEffortMaxMessage(): Record<string, any> {
  const tmp = mkdtempSync(join(tmpdir(), "crush-effort-wire-"));
  const probePath = join(tmp, "zz_effort_wire_probe_test.go").replace(/\\/g, "/");
  writeFileSync(probePath, PROBE_SRC);
  const overlayPath = join(tmp, "overlay.json");
  writeFileSync(
    overlayPath,
    JSON.stringify({
      Replace: {
        [`${REPO_ROOT.replace(/\\/g, "/")}/internal/server/zz_effort_wire_probe_test.go`]: probePath,
      },
    }),
  );
  let out: string;
  try {
    out = execFileSync(
      "go",
      ["test", `-overlay=${overlayPath}`, "./internal/server/", "-run", "TestZZEffortWireProbe", "-v", "-count=1"],
      { cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
    );
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    throw new Error(
      `go wire probe failed — cannot generate the real message_created payload. ` +
        `Is the Go toolchain available and does internal/server compile?\n${e.stdout ?? ""}\n${e.stderr ?? ""}`,
    );
  }
  const m = /ZZWIRE:(\{.*\})/.exec(out);
  if (!m) throw new Error(`wire probe produced no ZZWIRE payload line:\n${out}`);
  const payload = JSON.parse(m[1]);
  if (payload.ReasoningEffort !== "max") {
    throw new Error(`wire payload lost ReasoningEffort: ${m[1]}`);
  }
  return payload;
}

test.beforeEach(async ({ page }) => {
  await setupMockWS(page);
  await page.route("/auth/check", (route) =>
    route.fulfill({ status: 200, body: "OK" })
  );
});

// ── Config factory ────────────────────────────────────────────────────────────

function makeClaudeConfig() {
  return makeConfig({
    models: {
      smart: { Provider: "local-cli", Model: "cli-claude-opus" },
      fast: { Provider: "local-cli", Model: "cli-claude-sonnet" },
    },
    providers: {
      "local-cli": {
        name: "CLI",
        enabled: true,
        type: "cli",
        models: [
          { id: "cli-claude-opus", name: "Claude Opus (CLI)", contextWindow: 1_000_000 },
          { id: "cli-claude-sonnet", name: "Claude Sonnet (CLI)", contextWindow: 1_000_000 },
          { id: "gemini-flash", name: "Gemini Flash", contextWindow: 200_000 },
        ],
      },
    },
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function setup(page: any) {
  await page.goto("/");
  const sessionID = "test-session-reasoning";

  await sendMockWSMessage(page, {
    type: "sessions_list",
    payload: [
      makeSession({
        ID: sessionID,
        Title: "Reasoning Effort Test",
        SmartModelProvider: "local-cli",
        SmartModelID: "cli-claude-opus",
        SmartModelReasoningEffort: "medium",
      }),
    ],
  });
  await sendMockWSMessage(page, { type: "config", payload: makeClaudeConfig() });

  // Wait for chat input to be enabled
  await expect(page.locator('[data-test-id="chat-input-textarea"]')).toBeEnabled({
    timeout: 5000,
  });

  return sessionID;
}

test.describe("Reasoning Effort Controls", () => {
  test("effort controls are visible for CLI Claude models", async ({ page }) => {
    await setup(page);

    // Smart model selector should show effort controls
    await expect(page.locator('[data-test-id="reasoning-effort-smart"]')).toBeVisible();
    await expect(
      page.locator('[data-test-id="reasoning-effort-smart-decrease"]'),
    ).toBeVisible();
    await expect(
      page.locator('[data-test-id="reasoning-effort-smart-label"]'),
    ).toBeVisible();
    await expect(
      page.locator('[data-test-id="reasoning-effort-smart-increase"]'),
    ).toBeVisible();

    // Fast model selector should also show effort controls
    await expect(page.locator('[data-test-id="reasoning-effort-fast"]')).toBeVisible();
  });

  test("effort label displays correct initial value (M for medium)", async ({ page }) => {
    await setup(page);

    const largeLabel = page.locator('[data-test-id="reasoning-effort-smart-label"]');
    await expect(largeLabel).toHaveText("M");

    const smallLabel = page.locator('[data-test-id="reasoning-effort-fast-label"]');
    await expect(smallLabel).toHaveText("M");
  });

  test("clicking increase button cycles through effort levels", async ({ page }) => {
    await setup(page);
    const sessionID = "test-session-reasoning";

    const label = page.locator('[data-test-id="reasoning-effort-smart-label"]');

    // effort.ts EFFORT_LEVELS is ["low", "medium", "high", "xhigh", "max"] —
    // a 5-level cycle, not 4. The old assertions here (H → X → L, skipping
    // "max"/"XX" entirely) never matched that source of truth; see effort.ts
    // and ModelSelector.tsx's EFFORT_LABELS (max -> "XX").

    // M (medium) → H (high)
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(label).toHaveText("H");

    // Verify set_session_models was sent
    const sentMsg = await waitForWSSend(page, "set_session_models");
    expect(sentMsg.type).toBe("set_session_models");
    expect(sentMsg.payload.smartModel.reasoning_effort).toBe("high");

    // H (high) → X (xhigh)
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(label).toHaveText("X");

    // X (xhigh) → XX (max)
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(label).toHaveText("XX");

    // XX (max) → L (low)
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(label).toHaveText("L");

    // L (low) → M (medium) - cycle completes
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(label).toHaveText("M");
  });

  test("clicking decrease button cycles through effort levels in reverse", async ({
    page,
  }) => {
    await setup(page);
    const label = page.locator('[data-test-id="reasoning-effort-smart-label"]');

    // Mirror of the increase test above — same 5-level cycle, reverse order.

    // M (medium) → L (low)
    await page.locator('[data-test-id="reasoning-effort-smart-decrease"]').click();
    await expect(label).toHaveText("L");

    // L (low) → XX (max)
    await page.locator('[data-test-id="reasoning-effort-smart-decrease"]').click();
    await expect(label).toHaveText("XX");

    // XX (max) → X (xhigh)
    await page.locator('[data-test-id="reasoning-effort-smart-decrease"]').click();
    await expect(label).toHaveText("X");

    // X (xhigh) → H (high)
    await page.locator('[data-test-id="reasoning-effort-smart-decrease"]').click();
    await expect(label).toHaveText("H");

    // H (high) → M (medium) - cycle completes
    await page.locator('[data-test-id="reasoning-effort-smart-decrease"]').click();
    await expect(label).toHaveText("M");
  });

  test("effort is persisted when session is reloaded", async ({ page }) => {
    await setup(page);
    const sessionID = "test-session-reasoning";

    // Change effort to high
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(
      page.locator('[data-test-id="reasoning-effort-smart-label"]'),
    ).toHaveText("H");

    // Wait for the update to be sent
    await waitForWSSend(page, "set_session_models");

    // Simulate page reload by sending updated session data
    await sendMockWSMessage(page, {
      type: "session_updated",
      payload: makeSession({
        ID: sessionID,
        Title: "Reasoning Effort Test",
        SmartModelProvider: "local-cli",
        SmartModelID: "cli-claude-opus",
        SmartModelReasoningEffort: "high",
      }),
    });

    // Label should still show H after "reload"
    await expect(
      page.locator('[data-test-id="reasoning-effort-smart-label"]'),
    ).toHaveText("H");
  });

  test("effort badge renders from the real server wire payload", async ({ page }) => {
    const sessionID = await setup(page);

    // Set effort to xhigh (M → H → X). The real server wire JSON payload below
    // is generated by running toMessageWire via a Go probe (see
    // realWireEffortMaxMessage) and carries its own independent ReasoningEffort: "max".
    // The badge reflects the message's own field (message.ReasoningEffort via
    // EffortBadge.tsx), not the selector value, so this click sequence only needs
    // to move the selector off the default; it isn't asserting the selector reaches "max".
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(
      page.locator('[data-test-id="reasoning-effort-smart-label"]'),
    ).toHaveText("X");

    // Send a message
    await page.locator('[data-test-id="chat-input-textarea"]').fill("Hello");
    await page.locator('[data-test-id="chat-input-send-button"]').click();

    // Wait for send_message
    await waitForWSSend(page, "send_message");

    // Drive the badge through the REAL server→wire path: the payload below
    // is the actual JSON toMessageWire emits for a max-effort assistant
    // message, produced by running the Go conversion (see
    // realWireEffortMaxMessage). No field is hand-written here.
    const wirePayload = realWireEffortMaxMessage();
    await sendMockWSMessage(page, {
      type: "message_created",
      payload: wirePayload,
    });

    // Wait for message text to appear
    await expect(page.getByText("Response with max effort")).toBeVisible({ timeout: 3000 });

    // EffortBadge lives inside AssistantHoverActions, which Message.tsx only
    // mounts while the row is hovered ({hovered && <AssistantHoverActions .../>})
    // — not just CSS-hidden, actually unmounted. Hover the row first. Message.tsx
    // renders the row as `<div id={`msg-${message.ID}`} className="msg-row" ...>`
    // (NB: not "group/msg" — that class doesn't exist here; other specs
    // referencing it may themselves be stale, out of scope for this test).
    const msgRow = page.locator("#msg-resp-max");
    await msgRow.hover();

    // Check that the model badge shows effort level XX (max).
    // The badge is a small span with the effort letter(s) in brackets next to
    // the model name — EffortBadge.tsx renders `[XX]` for effort === "max"
    // and sets title={`Reasoning effort: ${effort}`} (the raw effort string,
    // not the abbreviated label).
    const effortBadge = msgRow.locator("span[title='Reasoning effort: max']");
    await expect(effortBadge).toBeVisible();
    await expect(effortBadge).toHaveText("[XX]");
  }, 180_000);

  test("changing small model effort works independently", async ({ page }) => {
    await setup(page);

    const largeLabel = page.locator('[data-test-id="reasoning-effort-smart-label"]');
    const smallLabel = page.locator('[data-test-id="reasoning-effort-fast-label"]');

    // Set large to high
    await page.locator('[data-test-id="reasoning-effort-smart-increase"]').click();
    await expect(largeLabel).toHaveText("H");
    await expect(smallLabel).toHaveText("M"); // Fast unchanged

    // Set small to max
    await page.locator('[data-test-id="reasoning-effort-fast-increase"]').click();
    await page.locator('[data-test-id="reasoning-effort-fast-increase"]').click();
    await expect(smallLabel).toHaveText("X");
    await expect(largeLabel).toHaveText("H"); // Smart unchanged
  });
});
