// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: async_jobs.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const archiveAsyncJobToolCallID = `-- name: ArchiveAsyncJobToolCallID :execrows
UPDATE async_jobs SET tool_call_id = ?1, updated_at = ?2
WHERE owner_session_id = ?3 AND tool_call_id = ?4
  AND state != 'running' AND delivery IN ('done', 'void')
`

type ArchiveAsyncJobToolCallIDParams struct {
	NewToolCallID  string `json:"new_tool_call_id"`
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
	OldToolCallID  string `json:"old_tool_call_id"`
}

// B14/A14b fix: a (owner_session_id, tool_call_id) key whose row is already
// HISTORY (state != 'running' AND delivery IN ('done', 'void')) is renamed
// out of the active key namespace so a REUSED tool_call_id (a provider that
// numbers calls per response, e.g. "call_0") can claim a brand new row
// immediately instead of being refused for up to 7 days as "already started
// earlier"/"different input" (before phase 4 the id was freed at delivery;
// phase 4's durable row otherwise outlives it). The archived row keeps its
// own primary key column but under a new, collision-free text -- it stays
// fully addressable by notice_message_id (Rerun's repend, readers) and by
// every owner-scoped query; only a lookup BY THE ORIGINAL tool_call_id text
// stops seeing it, which is exactly the point: that text is free again.
// The `state != 'running'` guard is load-bearing, not redundant with the
// delivery check: Rerun's VoidAsyncJobsByToolCallIDs can set delivery='void'
// on a row that is STILL running (its stop may have raced or failed) --
// renaming such a row's tool_call_id would orphan its own eventual
// Transition call (which targets the OLD text) and, worse, risk that CAS
// colliding with an unrelated NEW row later claimed under the freed text.
func (q *Queries) ArchiveAsyncJobToolCallID(ctx context.Context, arg ArchiveAsyncJobToolCallIDParams) (int64, error) {
	result, err := q.exec(ctx, q.archiveAsyncJobToolCallIDStmt, archiveAsyncJobToolCallID,
		arg.NewToolCallID,
		arg.UpdatedAt,
		arg.OwnerSessionID,
		arg.OldToolCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const asyncReactionDebtExists = `-- name: AsyncReactionDebtExists :one
SELECT
    EXISTS (
        SELECT 1 FROM async_jobs
        WHERE owner_session_id = ?1 AND wake = 1 AND reacted = 0 AND delivery != 'void' AND announced = 1
    )
    OR EXISTS (
        SELECT 1 FROM session_notices
        WHERE owner = ?1 AND wake = 1 AND reacted = 0 AND delivery != 'void'
    ) AS has_debt
`

// Doc sec.3.4: one indexed EXISTS, backed by the partial indexes
// idx_async_jobs_debt and idx_session_notices_debt "(owner) WHERE wake=1
// AND reacted=0 AND delivery<>'void'" on both tables. The async_jobs branch
// additionally requires announced=1 (doc: "task rows with announced=1" --
// review fix): a job that reaches terminal before its own "started"
// tool-result commits is wake=1/delivery=pending/reacted=0/announced=0; an
// unannounced row can never produce a notice (DUR-7) and the drain pull
// (ListPendingAsyncJobNoticesForOwner/PullPendingAsyncJobNotice) already
// skips it, so without this guard the debt check falsely reports debt,
// driving a wasted provider turn with nothing to react to -- and if the ack
// then aborts, the row is deleted (DeleteUnannouncedAsyncJob) and the turn
// was wasted for nothing. session_notices carries no announced concept
// (doc sec.3.2: it has no ack gate), so its branch is unchanged.
func (q *Queries) AsyncReactionDebtExists(ctx context.Context, owner string) (sql.NullBool, error) {
	row := q.queryRow(ctx, q.asyncReactionDebtExistsStmt, asyncReactionDebtExists, owner)
	var has_debt sql.NullBool
	err := row.Scan(&has_debt)
	return has_debt, err
}

const claimAsyncJob = `-- name: ClaimAsyncJob :one
INSERT INTO async_jobs (
    owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id,
    origin_cli, state, host_id, claim_id, announced, delivery, wake, reacted,
    deadline_at, timeout_kind, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, 'running', ?, ?, 0, 'none', 0, 0, ?, ?, ?, ?
)
ON CONFLICT (owner_session_id, tool_call_id) DO NOTHING
RETURNING owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id
`

type ClaimAsyncJobParams struct {
	OwnerSessionID string         `json:"owner_session_id"`
	ToolCallID     string         `json:"tool_call_id"`
	Kind           string         `json:"kind"`
	ToolName       string         `json:"tool_name"`
	TimeoutSeconds int64          `json:"timeout_seconds"`
	InputHash      string         `json:"input_hash"`
	ChildSessionID sql.NullString `json:"child_session_id"`
	OriginCli      int64          `json:"origin_cli"`
	HostID         string         `json:"host_id"`
	ClaimID        string         `json:"claim_id"`
	DeadlineAt     sql.NullInt64  `json:"deadline_at"`
	TimeoutKind    sql.NullString `json:"timeout_kind"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

// Durable idempotent start. ON CONFLICT DO NOTHING mirrors
// EnqueueRunQueueEntry: a caller retrying the same (owner_session_id,
// tool_call_id) after a crash must not error just because an earlier
// attempt already committed the row -- it reads the existing row instead
// (GetAsyncJob), same as before.
//
// child_session_id is claimed here directly for delegations (doc sec.3.8,
// reversing the rejected branch's FK-driven "claim empty, fill in later"
// two-step): the id is deterministic and child_session_id carries no FK,
// so there is nothing blocking writing it at claim time. Callers pass NULL
// for plain (kind='command') jobs.
//
// claim_id (A11, migration 20260929000002): a random id minted once per
// claim, carried by the executor for this claim's lifetime and threaded
// into TransitionAsyncJobTerminalPreserveVoid's CAS -- closes the ABA where
// a deleted-then-re-claimed row would otherwise let a stale executor's late
// result commit onto the NEW claim just because both share
// (owner_session_id, tool_call_id) and state='running'.
func (q *Queries) ClaimAsyncJob(ctx context.Context, arg ClaimAsyncJobParams) (AsyncJob, error) {
	row := q.queryRow(ctx, q.claimAsyncJobStmt, claimAsyncJob,
		arg.OwnerSessionID,
		arg.ToolCallID,
		arg.Kind,
		arg.ToolName,
		arg.TimeoutSeconds,
		arg.InputHash,
		arg.ChildSessionID,
		arg.OriginCli,
		arg.HostID,
		arg.ClaimID,
		arg.DeadlineAt,
		arg.TimeoutKind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AsyncJob
	err := row.Scan(
		&i.OwnerSessionID,
		&i.ToolCallID,
		&i.Kind,
		&i.ToolName,
		&i.TimeoutSeconds,
		&i.InputHash,
		&i.ChildSessionID,
		&i.OriginCli,
		&i.State,
		&i.NoticeKind,
		&i.HostID,
		&i.Announced,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Wake,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.DeadlineAt,
		&i.TimeoutKind,
		&i.ResultSummary,
		&i.ResultIsError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimID,
		&i.AnnounceMessageID,
	)
	return i, err
}

const clearReactedFailedForOwner = `-- name: ClearReactedFailedForOwner :execrows
UPDATE async_jobs SET reacted_failed = 0, updated_at = ?
WHERE owner_session_id = ? AND reacted_failed = 1
`

type ClearReactedFailedForOwnerParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
}

// A1: a settle-by-failure closure ("this row's debt was closed by K=3
// failed wake-up attempts, not a real reaction") is NOT a permanent,
// unscoped fact about the owner -- it is superseded the moment the SAME
// owner proves it is alive and answering again. Cleared from TWO call
// sites: the real-reaction transaction (MarkReactedWithMessageUpdate, every
// time a step finishes with real content) and claiming a fresh delegation
// on a child session (Claim, before the new delegation's own rows can ever
// be confused with the old one's). Without this, ListReactedFailedText/
// refreshSubAgentCompletion read reacted_failed unscoped and report a
// delegation "failed" forever after one transient closure, even once the
// child session is back to answering normally (same delegation, a later
// job) or has been handed a brand new delegation entirely.
func (q *Queries) ClearReactedFailedForOwner(ctx context.Context, arg ClearReactedFailedForOwnerParams) (int64, error) {
	result, err := q.exec(ctx, q.clearReactedFailedForOwnerStmt, clearReactedFailedForOwner, arg.UpdatedAt, arg.OwnerSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAsyncJobsOlderThan = `-- name: CountAsyncJobsOlderThan :one
SELECT COUNT(*) FROM async_jobs
WHERE state != 'running' AND delivery IN ('done', 'void') AND updated_at < ?
  AND NOT (delivery = 'done' AND wake = 1 AND reacted = 0)
`

// Same predicate as PurgeAsyncJobsOlderThan, read-only, for
// `sessions gc --dry-run`.
func (q *Queries) CountAsyncJobsOlderThan(ctx context.Context, updatedAt int64) (int64, error) {
	row := q.queryRow(ctx, q.countAsyncJobsOlderThanStmt, countAsyncJobsOlderThan, updatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAsyncHostIfNoJobs = `-- name: DeleteAsyncHostIfNoJobs :execrows
DELETE FROM async_hosts
WHERE id = ? AND NOT EXISTS (SELECT 1 FROM async_jobs WHERE host_id = async_hosts.id)
`

// Owner deletes its own row at exit if it has no rows (doc sec.3.6); a
// recoverer holding a dead host's lock calls this too, after deleting the
// lock file itself. No FK enforces this -- the guard is explicit here.
// The subquery is correlated against async_hosts.id (not a second bound
// parameter): sqlc's SQLite plugin does not reliably rewrite a repeated
// same-named placeholder once one occurrence sits in the outer WHERE and
// the other inside a subquery's WHERE (confirmed against sqlc v1.30.0 --
// bare `?`, repeated @id, and two distinctly-named args all either
// under-counted the bind values or left an occurrence unrewritten,
// producing a query that fails at runtime). Correlating on the outer
// table's own column needs only ONE real parameter and sidesteps the bug
// entirely.
func (q *Queries) DeleteAsyncHostIfNoJobs(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteAsyncHostIfNoJobsStmt, deleteAsyncHostIfNoJobs, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnannouncedAsyncJob = `-- name: DeleteUnannouncedAsyncJob :execrows
DELETE FROM async_jobs WHERE owner_session_id = ? AND tool_call_id = ? AND announced = 0
`

type DeleteUnannouncedAsyncJobParams struct {
	OwnerSessionID string `json:"owner_session_id"`
	ToolCallID     string `json:"tool_call_id"`
}

// Abort: the "started" tool-result write itself failed, so nothing durable
// should remain (ASYNC-05). Scoped to announced=0 so a row that won the
// ack-gate race concurrently is never deleted out from under it.
func (q *Queries) DeleteUnannouncedAsyncJob(ctx context.Context, arg DeleteUnannouncedAsyncJobParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteUnannouncedAsyncJobStmt, deleteUnannouncedAsyncJob, arg.OwnerSessionID, arg.ToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAsyncHost = `-- name: GetAsyncHost :one
SELECT id, pid, label, started_at FROM async_hosts WHERE id = ?
`

func (q *Queries) GetAsyncHost(ctx context.Context, id string) (AsyncHost, error) {
	row := q.queryRow(ctx, q.getAsyncHostStmt, getAsyncHost, id)
	var i AsyncHost
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Label,
		&i.StartedAt,
	)
	return i, err
}

const getAsyncJob = `-- name: GetAsyncJob :one
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs WHERE owner_session_id = ? AND tool_call_id = ?
`

type GetAsyncJobParams struct {
	OwnerSessionID string `json:"owner_session_id"`
	ToolCallID     string `json:"tool_call_id"`
}

func (q *Queries) GetAsyncJob(ctx context.Context, arg GetAsyncJobParams) (AsyncJob, error) {
	row := q.queryRow(ctx, q.getAsyncJobStmt, getAsyncJob, arg.OwnerSessionID, arg.ToolCallID)
	var i AsyncJob
	err := row.Scan(
		&i.OwnerSessionID,
		&i.ToolCallID,
		&i.Kind,
		&i.ToolName,
		&i.TimeoutSeconds,
		&i.InputHash,
		&i.ChildSessionID,
		&i.OriginCli,
		&i.State,
		&i.NoticeKind,
		&i.HostID,
		&i.Announced,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Wake,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.DeadlineAt,
		&i.TimeoutKind,
		&i.ResultSummary,
		&i.ResultIsError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimID,
		&i.AnnounceMessageID,
	)
	return i, err
}

const getRunningAsyncJobByChildSession = `-- name: GetRunningAsyncJobByChildSession :one
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs WHERE child_session_id = ? AND state = 'running'
`

// ASYNC-01 conflict check inside the claim transaction (doc sec.3.8): a
// second delegation naming the same child session while a RUNNING row
// already claims it must fail (dead-host row: recover it in the same
// attempt instead) rather than silently queuing behind it.
func (q *Queries) GetRunningAsyncJobByChildSession(ctx context.Context, childSessionID sql.NullString) (AsyncJob, error) {
	row := q.queryRow(ctx, q.getRunningAsyncJobByChildSessionStmt, getRunningAsyncJobByChildSession, childSessionID)
	var i AsyncJob
	err := row.Scan(
		&i.OwnerSessionID,
		&i.ToolCallID,
		&i.Kind,
		&i.ToolName,
		&i.TimeoutSeconds,
		&i.InputHash,
		&i.ChildSessionID,
		&i.OriginCli,
		&i.State,
		&i.NoticeKind,
		&i.HostID,
		&i.Announced,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Wake,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.DeadlineAt,
		&i.TimeoutKind,
		&i.ResultSummary,
		&i.ResultIsError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimID,
		&i.AnnounceMessageID,
	)
	return i, err
}

const incrementAsyncJobWakeAttempts = `-- name: IncrementAsyncJobWakeAttempts :execrows
UPDATE async_jobs SET wake_attempts = wake_attempts + 1, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id IN (/*SLICE:tool_call_ids*/?) AND wake = 1 AND reacted = 0
`

type IncrementAsyncJobWakeAttemptsParams struct {
	UpdatedAt      int64    `json:"updated_at"`
	OwnerSessionID string   `json:"owner_session_id"`
	ToolCallIds    []string `json:"tool_call_ids"`
}

// Settle-by-failure step 1 (doc sec.3.4: "a temporary failure ... increments
// the attempt counter in the row"): a temporary provider failure after a
// wake-up call increments wake_attempts on the SPECIFIC rows the failed
// turn was meant to react to, not every debt row of the owner (the doc is
// explicit the closing/counting scope is fixed at the start of that turn,
// not re-evaluated against whatever is pending now). Guarded by
// wake=1 AND reacted=0 so a row that settled (by a real step, or by an
// earlier failure closure) in the meantime is left alone.
func (q *Queries) IncrementAsyncJobWakeAttempts(ctx context.Context, arg IncrementAsyncJobWakeAttemptsParams) (int64, error) {
	query := incrementAsyncJobWakeAttempts
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.OwnerSessionID)
	if len(arg.ToolCallIds) > 0 {
		for _, v := range arg.ToolCallIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tool_call_ids*/?", strings.Repeat(",?", len(arg.ToolCallIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tool_call_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAsyncHosts = `-- name: ListAsyncHosts :many
SELECT id, pid, label, started_at FROM async_hosts ORDER BY started_at ASC
`

// Reader for `sessions jobs`/`sessions hosts` display.
func (q *Queries) ListAsyncHosts(ctx context.Context) ([]AsyncHost, error) {
	rows, err := q.query(ctx, q.listAsyncHostsStmt, listAsyncHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncHost{}
	for rows.Next() {
		var i AsyncHost
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Label,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsyncHostsWithNoJobs = `-- name: ListAsyncHostsWithNoJobs :many
SELECT id, pid, label, started_at FROM async_hosts
WHERE id NOT IN (SELECT DISTINCT host_id FROM async_jobs)
`

// Retention candidates (doc sec.3.7): host rows with zero referencing
// async_jobs rows of ANY state. Caller still must verify the lock file
// itself is gone/dead before treating a host as reapable.
func (q *Queries) ListAsyncHostsWithNoJobs(ctx context.Context) ([]AsyncHost, error) {
	rows, err := q.query(ctx, q.listAsyncHostsWithNoJobsStmt, listAsyncHostsWithNoJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncHost{}
	for rows.Next() {
		var i AsyncHost
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Label,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAsyncJobsForOwner = `-- name: ListAsyncJobsForOwner :many
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs WHERE owner_session_id = ? ORDER BY created_at ASC
`

// Reader for `sessions jobs`/`sessions why`.
func (q *Queries) ListAsyncJobsForOwner(ctx context.Context, ownerSessionID string) ([]AsyncJob, error) {
	rows, err := q.query(ctx, q.listAsyncJobsForOwnerStmt, listAsyncJobsForOwner, ownerSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncJob{}
	for rows.Next() {
		var i AsyncJob
		if err := rows.Scan(
			&i.OwnerSessionID,
			&i.ToolCallID,
			&i.Kind,
			&i.ToolName,
			&i.TimeoutSeconds,
			&i.InputHash,
			&i.ChildSessionID,
			&i.OriginCli,
			&i.State,
			&i.NoticeKind,
			&i.HostID,
			&i.Announced,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Wake,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.DeadlineAt,
			&i.TimeoutKind,
			&i.ResultSummary,
			&i.ResultIsError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimID,
			&i.AnnounceMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctRunningHostIDs = `-- name: ListDistinctRunningHostIDs :many
SELECT DISTINCT host_id FROM async_jobs WHERE state = 'running'
`

// Every host_id that currently owns a 'running' row -- the candidate set a
// recovery sweep probes (doc sec.3.6/3.7). Liveness itself is decided by
// the host lock module (OS lock probe), not by this query.
func (q *Queries) ListDistinctRunningHostIDs(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listDistinctRunningHostIDsStmt, listDistinctRunningHostIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var host_id string
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAsyncJobNoticesForOwner = `-- name: ListPendingAsyncJobNoticesForOwner :many
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs
WHERE owner_session_id = ? AND delivery = 'pending' AND announced = 1
ORDER BY created_at ASC
`

// Candidates for the drain's pull (doc sec.3.3): announced=1 is required --
// an unannounced job never produces a notice (DUR-7).
func (q *Queries) ListPendingAsyncJobNoticesForOwner(ctx context.Context, ownerSessionID string) ([]AsyncJob, error) {
	rows, err := q.query(ctx, q.listPendingAsyncJobNoticesForOwnerStmt, listPendingAsyncJobNoticesForOwner, ownerSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncJob{}
	for rows.Next() {
		var i AsyncJob
		if err := rows.Scan(
			&i.OwnerSessionID,
			&i.ToolCallID,
			&i.Kind,
			&i.ToolName,
			&i.TimeoutSeconds,
			&i.InputHash,
			&i.ChildSessionID,
			&i.OriginCli,
			&i.State,
			&i.NoticeKind,
			&i.HostID,
			&i.Announced,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Wake,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.DeadlineAt,
			&i.TimeoutKind,
			&i.ResultSummary,
			&i.ResultIsError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimID,
			&i.AnnounceMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactedFailedAsyncJobsForOwner = `-- name: ListReactedFailedAsyncJobsForOwner :many
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs WHERE owner_session_id = ? AND reacted_failed = 1 ORDER BY created_at ASC
`

// Reader for the parent-notification path (doc sec.3.4: "passes the parent
// the text of the unreacted notices") -- the rows settle-by-failure closed
// for this owner, whose text a failed delegation's parent must still see.
func (q *Queries) ListReactedFailedAsyncJobsForOwner(ctx context.Context, ownerSessionID string) ([]AsyncJob, error) {
	rows, err := q.query(ctx, q.listReactedFailedAsyncJobsForOwnerStmt, listReactedFailedAsyncJobsForOwner, ownerSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncJob{}
	for rows.Next() {
		var i AsyncJob
		if err := rows.Scan(
			&i.OwnerSessionID,
			&i.ToolCallID,
			&i.Kind,
			&i.ToolName,
			&i.TimeoutSeconds,
			&i.InputHash,
			&i.ChildSessionID,
			&i.OriginCli,
			&i.State,
			&i.NoticeKind,
			&i.HostID,
			&i.Announced,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Wake,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.DeadlineAt,
			&i.TimeoutKind,
			&i.ResultSummary,
			&i.ResultIsError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimID,
			&i.AnnounceMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningAsyncJobsForHost = `-- name: ListRunningAsyncJobsForHost :many
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs WHERE host_id = ? AND state = 'running' ORDER BY created_at ASC
`

// Recovery sweep input (doc sec.3.7): every RUNNING row owned by a
// particular host_id, for a leader/recoverer that has independently
// confirmed (via the host lock module) that host_id is dead.
func (q *Queries) ListRunningAsyncJobsForHost(ctx context.Context, hostID string) ([]AsyncJob, error) {
	rows, err := q.query(ctx, q.listRunningAsyncJobsForHostStmt, listRunningAsyncJobsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncJob{}
	for rows.Next() {
		var i AsyncJob
		if err := rows.Scan(
			&i.OwnerSessionID,
			&i.ToolCallID,
			&i.Kind,
			&i.ToolName,
			&i.TimeoutSeconds,
			&i.InputHash,
			&i.ChildSessionID,
			&i.OriginCli,
			&i.State,
			&i.NoticeKind,
			&i.HostID,
			&i.Announced,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Wake,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.DeadlineAt,
			&i.TimeoutKind,
			&i.ResultSummary,
			&i.ResultIsError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimID,
			&i.AnnounceMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningAsyncJobsForOwners = `-- name: ListRunningAsyncJobsForOwners :many
SELECT owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id FROM async_jobs
WHERE owner_session_id IN (/*SLICE:owner_ids*/?) AND state = 'running'
ORDER BY created_at ASC
`

// Own-area recovery/scope evaluation (doc sec.3.5/3.7): the leader's owner
// id set restricted to currently-running rows. That set comes from walking
// delegation rows (child_session_id), NOT parent_session_id -- doc sec.3.5
// is explicit: "descendants via parent_session_id are not walked". No
// lease/heartbeat filter -- liveness is decided per-host by the caller via
// the host lock module, not by this query.
func (q *Queries) ListRunningAsyncJobsForOwners(ctx context.Context, ownerIds []string) ([]AsyncJob, error) {
	query := listRunningAsyncJobsForOwners
	var queryParams []interface{}
	if len(ownerIds) > 0 {
		for _, v := range ownerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:owner_ids*/?", strings.Repeat(",?", len(ownerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:owner_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AsyncJob{}
	for rows.Next() {
		var i AsyncJob
		if err := rows.Scan(
			&i.OwnerSessionID,
			&i.ToolCallID,
			&i.Kind,
			&i.ToolName,
			&i.TimeoutSeconds,
			&i.InputHash,
			&i.ChildSessionID,
			&i.OriginCli,
			&i.State,
			&i.NoticeKind,
			&i.HostID,
			&i.Announced,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Wake,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.DeadlineAt,
			&i.TimeoutKind,
			&i.ResultSummary,
			&i.ResultIsError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimID,
			&i.AnnounceMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsyncJobAnnounced = `-- name: MarkAsyncJobAnnounced :execrows
UPDATE async_jobs SET announced = 1, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ?
`

type MarkAsyncJobAnnouncedParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
	ToolCallID     string `json:"tool_call_id"`
}

// Ack gate (DUR-7): "started" and announced=1 are one transaction with NO
// condition on state -- a job that raced to terminal before its own
// "started" tool-result committed must still be marked announced (the
// caller checks rows-affected==0 only to detect a since-deleted row, e.g.
// a Rerun that removed it out from under this transaction).
func (q *Queries) MarkAsyncJobAnnounced(ctx context.Context, arg MarkAsyncJobAnnouncedParams) (int64, error) {
	result, err := q.exec(ctx, q.markAsyncJobAnnouncedStmt, markAsyncJobAnnounced, arg.UpdatedAt, arg.OwnerSessionID, arg.ToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAsyncJobsReactedForOwner = `-- name: MarkAsyncJobsReactedForOwner :execrows
UPDATE async_jobs SET reacted = 1, updated_at = ?
WHERE owner_session_id = ? AND wake = 1 AND reacted = 0 AND delivery = 'done'
`

type MarkAsyncJobsReactedForOwnerParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
}

// Reaction is recorded where it happens (doc sec.3.4): the same transaction
// that persists a model step's real-content finish marks every wake=1,
// reacted=0, delivery='done' row of this owner reacted=1. Not derived from
// created_at/clock order -- every currently-done row qualifies, including
// ones a compaction later strips from context.
func (q *Queries) MarkAsyncJobsReactedForOwner(ctx context.Context, arg MarkAsyncJobsReactedForOwnerParams) (int64, error) {
	result, err := q.exec(ctx, q.markAsyncJobsReactedForOwnerStmt, markAsyncJobsReactedForOwner, arg.UpdatedAt, arg.OwnerSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pullPendingAsyncJobNotice = `-- name: PullPendingAsyncJobNotice :one
UPDATE async_jobs
SET delivery = 'done', updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ? AND delivery = 'pending' AND announced = 1
RETURNING owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id
`

type PullPendingAsyncJobNoticeParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
	ToolCallID     string `json:"tool_call_id"`
}

// The pull UPDATE...RETURNING (doc sec.3.3): one transaction per notice --
// caller does this, then INSERTs the history message, then stores
// notice_message_id via SetAsyncJobNoticeMessageID, all in the SAME tx. 0
// rows affected (checked by the caller via RETURNING yielding sql.ErrNoRows)
// means another leader already won this row; the caller must roll back
// rather than proceed to insert a duplicate message.
func (q *Queries) PullPendingAsyncJobNotice(ctx context.Context, arg PullPendingAsyncJobNoticeParams) (AsyncJob, error) {
	row := q.queryRow(ctx, q.pullPendingAsyncJobNoticeStmt, pullPendingAsyncJobNotice, arg.UpdatedAt, arg.OwnerSessionID, arg.ToolCallID)
	var i AsyncJob
	err := row.Scan(
		&i.OwnerSessionID,
		&i.ToolCallID,
		&i.Kind,
		&i.ToolName,
		&i.TimeoutSeconds,
		&i.InputHash,
		&i.ChildSessionID,
		&i.OriginCli,
		&i.State,
		&i.NoticeKind,
		&i.HostID,
		&i.Announced,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Wake,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.DeadlineAt,
		&i.TimeoutKind,
		&i.ResultSummary,
		&i.ResultIsError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimID,
		&i.AnnounceMessageID,
	)
	return i, err
}

const purgeAsyncJobsOlderThan = `-- name: PurgeAsyncJobsOlderThan :execrows
DELETE FROM async_jobs
WHERE state != 'running' AND delivery IN ('done', 'void') AND updated_at < ?
  AND NOT (delivery = 'done' AND wake = 1 AND reacted = 0)
`

// Bounded retention (doc sec.3.7): a terminal, delivered-or-voided row past
// the cutoff is deleted outright -- no soft delete, same precedent as
// `sessions gc`'s own row deletion. `NOT (delivery='done' AND wake=1 AND
// reacted=0)` (A5): a 'done' row with wake=1/reacted=0 IS unreacted debt --
// already surfaced in history, just not yet reacted to -- and must survive
// retention exactly like a 'running' row does, or a stuck/slow-to-react
// owner silently loses its own obligation instead of ever settling it (by a
// real turn or by settle-by-failure). Scoped to delivery='done' specifically,
// matching the system's own debt definition everywhere else (idx_async_jobs_
// debt, AsyncReactionDebtExists): a 'void' row is NEVER debt regardless of
// its wake/reacted bits (Rerun's VoidAsyncJobsByToolCallIDs voids a row
// without touching wake/reacted, so a voided row can carry stale wake=1/
// reacted=0 from before it was voided -- that must not block its purge,
// since a void row will never produce a notice to react to in the first
// place).
func (q *Queries) PurgeAsyncJobsOlderThan(ctx context.Context, updatedAt int64) (int64, error) {
	result, err := q.exec(ctx, q.purgeAsyncJobsOlderThanStmt, purgeAsyncJobsOlderThan, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const registerAsyncHost = `-- name: RegisterAsyncHost :one
INSERT INTO async_hosts (id, pid, label, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, pid, label, started_at
`

type RegisterAsyncHostParams struct {
	ID        string `json:"id"`
	Pid       int64  `json:"pid"`
	Label     string `json:"label"`
	StartedAt int64  `json:"started_at"`
}

// Lazy registration at first claim (doc sec.3.6): the host row is
// display-only bookkeeping, created once per process lifetime alongside the
// OS lock file. Never consulted to decide liveness.
func (q *Queries) RegisterAsyncHost(ctx context.Context, arg RegisterAsyncHostParams) (AsyncHost, error) {
	row := q.queryRow(ctx, q.registerAsyncHostStmt, registerAsyncHost,
		arg.ID,
		arg.Pid,
		arg.Label,
		arg.StartedAt,
	)
	var i AsyncHost
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Label,
		&i.StartedAt,
	)
	return i, err
}

const rependAsyncJobsByNoticeMessageIDs = `-- name: RependAsyncJobsByNoticeMessageIDs :execrows
UPDATE async_jobs SET delivery = 'pending', reacted = 0, reacted_failed = 0, wake_attempts = 0, updated_at = ?
WHERE owner_session_id = ? AND delivery = 'done' AND notice_message_id IN (/*SLICE:message_ids*/?)
`

type RependAsyncJobsByNoticeMessageIDsParams struct {
	UpdatedAt      int64            `json:"updated_at"`
	OwnerSessionID string           `json:"owner_session_id"`
	MessageIds     []sql.NullString `json:"message_ids"`
}

// Rerun undo-truncation (doc sec.3.8): a row announced BEFORE the
// truncation point whose OWN notice landed in the deleted tail goes back to
// pending/reacted=0 so the next turn on the new branch pulls it again
// (ASYNC-04). Matched by notice_message_id, which is only ever set once a
// row reaches delivery='done'; the `delivery = 'done'` guard (A4) makes that
// explicit rather than implied -- without it, a retried Rerun could turn an
// already-'void' row (delivery is not terminal until every writer says so)
// back into 'pending'. wake_attempts/reacted_failed are reset (A1): a row
// re-entering the pending pool starts its settle-by-failure counters fresh,
// not with whatever an earlier, unrelated closure left behind. Must run
// BEFORE the void queries in the same Rerun pass: a row whose OWN
// tool call is ALSO in the deleted tail matches both queries, and void must
// win for it.
func (q *Queries) RependAsyncJobsByNoticeMessageIDs(ctx context.Context, arg RependAsyncJobsByNoticeMessageIDsParams) (int64, error) {
	query := rependAsyncJobsByNoticeMessageIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.OwnerSessionID)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAsyncJobAnnounceMessageID = `-- name: SetAsyncJobAnnounceMessageID :execrows
UPDATE async_jobs SET announce_message_id = ?, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ?
`

type SetAsyncJobAnnounceMessageIDParams struct {
	AnnounceMessageID sql.NullString `json:"announce_message_id"`
	UpdatedAt         int64          `json:"updated_at"`
	OwnerSessionID    string         `json:"owner_session_id"`
	ToolCallID        string         `json:"tool_call_id"`
}

// Second half of the ack gate's fused transaction (AnnounceStarted): records
// the "started" tool-result message that announced this row, so a Rerun can
// void the row by the message it actually deleted instead of by
// tool_call_id (which a provider may reuse per response). See migration
// 20260929000003.
func (q *Queries) SetAsyncJobAnnounceMessageID(ctx context.Context, arg SetAsyncJobAnnounceMessageIDParams) (int64, error) {
	result, err := q.exec(ctx, q.setAsyncJobAnnounceMessageIDStmt, setAsyncJobAnnounceMessageID,
		arg.AnnounceMessageID,
		arg.UpdatedAt,
		arg.OwnerSessionID,
		arg.ToolCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAsyncJobNoticeMessageID = `-- name: SetAsyncJobNoticeMessageID :execrows
UPDATE async_jobs SET notice_message_id = ?, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ?
`

type SetAsyncJobNoticeMessageIDParams struct {
	NoticeMessageID sql.NullString `json:"notice_message_id"`
	UpdatedAt       int64          `json:"updated_at"`
	OwnerSessionID  string         `json:"owner_session_id"`
	ToolCallID      string         `json:"tool_call_id"`
}

// Second half of the pull transaction: records where the notice landed.
func (q *Queries) SetAsyncJobNoticeMessageID(ctx context.Context, arg SetAsyncJobNoticeMessageIDParams) (int64, error) {
	result, err := q.exec(ctx, q.setAsyncJobNoticeMessageIDStmt, setAsyncJobNoticeMessageID,
		arg.NoticeMessageID,
		arg.UpdatedAt,
		arg.OwnerSessionID,
		arg.ToolCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAsyncJobNoticeMessageIDIfDone = `-- name: SetAsyncJobNoticeMessageIDIfDone :execrows
UPDATE async_jobs SET notice_message_id = ?, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ? AND delivery = 'done' AND notice_message_id IS NULL
`

type SetAsyncJobNoticeMessageIDIfDoneParams struct {
	NoticeMessageID sql.NullString `json:"notice_message_id"`
	UpdatedAt       int64          `json:"updated_at"`
	OwnerSessionID  string         `json:"owner_session_id"`
	ToolCallID      string         `json:"tool_call_id"`
}

// A3 (docs/reviews/2026-09-29-async-phase4-round1.md): job_kill's own
// Transition call sets delivery='done' directly, bypassing the ordinary
// pull (doc sec.3.2) -- so nothing else ever calls SetAsyncJobNoticeMessageID
// for that row. This fuses job_kill's own tool-result message id onto it in
// the SAME transaction as that message's insert (AnnounceJobKillResult),
// satisfying the law "delivery='done' => the row names the message that
// carries its result" (Rerun's RependAsyncJobsByNoticeMessageIDs, matched by
// notice_message_id, could otherwise never find a job_kill'd tool call in a
// deleted tail). Guarded to delivery='done' AND notice_message_id IS NULL:
// a row whose OWN causeJobKill transition lost the race to a different
// cause (still 'pending', to be pulled normally instead) is left
// completely alone -- 0 rows affected is not an error, the caller's
// tool-result message is persisted either way.
func (q *Queries) SetAsyncJobNoticeMessageIDIfDone(ctx context.Context, arg SetAsyncJobNoticeMessageIDIfDoneParams) (int64, error) {
	result, err := q.exec(ctx, q.setAsyncJobNoticeMessageIDIfDoneStmt, setAsyncJobNoticeMessageIDIfDone,
		arg.NoticeMessageID,
		arg.UpdatedAt,
		arg.OwnerSessionID,
		arg.ToolCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAsyncJobsWakeZeroPendingForOwners = `-- name: SetAsyncJobsWakeZeroPendingForOwners :execrows
UPDATE async_jobs SET wake = 0, updated_at = ?
WHERE owner_session_id IN (/*SLICE:owner_ids*/?) AND delivery IN ('pending', 'done') AND wake = 1
`

type SetAsyncJobsWakeZeroPendingForOwnersParams struct {
	UpdatedAt int64    `json:"updated_at"`
	OwnerIds  []string `json:"owner_ids"`
}

// Stop transitivity (DUR-9, doc sec.3.8): every pending row of the stopped
// tree loses its wake bit in the same pass, so a race between natural
// completion and Stop can never grant a stopped delegation a turn.
func (q *Queries) SetAsyncJobsWakeZeroPendingForOwners(ctx context.Context, arg SetAsyncJobsWakeZeroPendingForOwnersParams) (int64, error) {
	query := setAsyncJobsWakeZeroPendingForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	if len(arg.OwnerIds) > 0 {
		for _, v := range arg.OwnerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:owner_ids*/?", strings.Repeat(",?", len(arg.OwnerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:owner_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settleAsyncJobsReactedFailed = `-- name: SettleAsyncJobsReactedFailed :execrows
UPDATE async_jobs SET reacted = 1, reacted_failed = 1, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id IN (/*SLICE:tool_call_ids*/?) AND wake = 1 AND reacted = 0
`

type SettleAsyncJobsReactedFailedParams struct {
	UpdatedAt      int64    `json:"updated_at"`
	OwnerSessionID string   `json:"owner_session_id"`
	ToolCallIds    []string `json:"tool_call_ids"`
}

// Settle-by-failure step 2, after K=3 (doc sec.3.4): closes debt on exactly
// the id set captured at the start of the failed turn -- doc: "only for the
// rows that were done at the moment it started" -- not every currently-pending
// row of the owner (a notice that arrived mid-retry must get its own future
// wake-up call, not be silently absorbed into this closure). reacted_failed
// distinguishes this from an ordinary step-persisted reaction
// (MarkAsyncJobsReactedForOwner): it is set ONLY here, never by a real
// step, so a child session can tell its parent the delegation failed
// instead of succeeded-with-no-output.
func (q *Queries) SettleAsyncJobsReactedFailed(ctx context.Context, arg SettleAsyncJobsReactedFailedParams) (int64, error) {
	query := settleAsyncJobsReactedFailed
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.OwnerSessionID)
	if len(arg.ToolCallIds) > 0 {
		for _, v := range arg.ToolCallIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tool_call_ids*/?", strings.Repeat(",?", len(arg.ToolCallIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tool_call_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const transitionAsyncJobTerminalPreserveVoid = `-- name: TransitionAsyncJobTerminalPreserveVoid :one
UPDATE async_jobs
SET state = ?, notice_kind = ?, result_summary = ?, result_is_error = ?,
    delivery = CASE delivery WHEN 'void' THEN 'void' ELSE ? END,
    wake = ?, reacted = ?, updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ? AND state = 'running' AND claim_id = ?
RETURNING owner_session_id, tool_call_id, kind, tool_name, timeout_seconds, input_hash, child_session_id, origin_cli, state, notice_kind, host_id, announced, delivery, notice_message_id, wake, reacted, wake_attempts, reacted_failed, deadline_at, timeout_kind, result_summary, result_is_error, created_at, updated_at, claim_id, announce_message_id
`

type TransitionAsyncJobTerminalPreserveVoidParams struct {
	State          string         `json:"state"`
	NoticeKind     string         `json:"notice_kind"`
	ResultSummary  sql.NullString `json:"result_summary"`
	ResultIsError  sql.NullInt64  `json:"result_is_error"`
	Delivery       string         `json:"delivery"`
	Wake           int64          `json:"wake"`
	Reacted        int64          `json:"reacted"`
	UpdatedAt      int64          `json:"updated_at"`
	OwnerSessionID string         `json:"owner_session_id"`
	ToolCallID     string         `json:"tool_call_id"`
	ClaimID        string         `json:"claim_id"`
}

// The ONE terminal-transition CAS (DUR-1/DUR-2/step-2 review): a terminal
// state, its cause (notice_kind), the result payload, delivery, wake, and
// reacted are all set by this single statement, scoped to state='running'
// so only the first committer wins -- every other concurrent caller sees 0
// rows affected and must re-read the row (GetAsyncJob) and accept whatever
// state is there instead of retrying the same transition. This is the
// ONLY terminal-transition query (doc sec.3.8 is explicit the terminal
// transition always preserves void, so the earlier non-preserving sibling
// this replaced -- TransitionAsyncJobTerminal -- is gone, not a second,
// parallel path): a row already voided by Rerun truncation must not be
// resurrected to 'pending' by a late-arriving terminal transition (e.g.
// job_kill racing the history truncation).
//
// delivery is a PARAMETER, not a hardcoded 'pending' literal (step 3): every
// cause passes 'pending' except step 6's job_kill, which passes 'done' once
// its own tool response carries the real output (doc sec.3.2), so that row
// never also surfaces as a history notice via the pull. reacted is also a
// PARAMETER (step 6): every cause passes 0 (a row cannot have reacted
// anything while still running) except job_kill, which passes 1 in the SAME
// statement -- so a job_kill row is neither debt nor a future notice the
// instant it commits, with no separate write.
//
// claim_id (A11): the CALLER always supplies a concrete value -- either the
// claim_id its own executor captured at Claim time (the real ABA guard), or
// -- for a caller with no claim_id of its own (recovery, test seeding) --
// the store's Go layer (AsyncJobStore.Transition) first reads the row's
// CURRENT claim_id in the SAME transaction and passes that back in, so the
// predicate below is a no-op for them (always matches whatever is already
// there) and their pre-A11 "any running row matches" behavior is unchanged.
func (q *Queries) TransitionAsyncJobTerminalPreserveVoid(ctx context.Context, arg TransitionAsyncJobTerminalPreserveVoidParams) (AsyncJob, error) {
	row := q.queryRow(ctx, q.transitionAsyncJobTerminalPreserveVoidStmt, transitionAsyncJobTerminalPreserveVoid,
		arg.State,
		arg.NoticeKind,
		arg.ResultSummary,
		arg.ResultIsError,
		arg.Delivery,
		arg.Wake,
		arg.Reacted,
		arg.UpdatedAt,
		arg.OwnerSessionID,
		arg.ToolCallID,
		arg.ClaimID,
	)
	var i AsyncJob
	err := row.Scan(
		&i.OwnerSessionID,
		&i.ToolCallID,
		&i.Kind,
		&i.ToolName,
		&i.TimeoutSeconds,
		&i.InputHash,
		&i.ChildSessionID,
		&i.OriginCli,
		&i.State,
		&i.NoticeKind,
		&i.HostID,
		&i.Announced,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Wake,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.DeadlineAt,
		&i.TimeoutKind,
		&i.ResultSummary,
		&i.ResultIsError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimID,
		&i.AnnounceMessageID,
	)
	return i, err
}

const visibleAsyncReactionDebtExists = `-- name: VisibleAsyncReactionDebtExists :one
SELECT
    EXISTS (
        SELECT 1 FROM async_jobs
        WHERE owner_session_id = ?1 AND wake = 1 AND reacted = 0 AND delivery = 'done' AND announced = 1
    )
    OR EXISTS (
        SELECT 1 FROM session_notices
        WHERE owner = ?1 AND wake = 1 AND reacted = 0 AND delivery = 'done'
    ) AS has_debt
`

// Phase 4 step 4 review fix (P1): same shape as AsyncReactionDebtExists, scoped to
// delivery='done' specifically instead of "!= 'void'" -- debt already
// VISIBLE in history right now (the pull already succeeded for it), not
// merely 'pending' (a pull that has not succeeded yet, or is permanently
// failing). The Drain turn-start decision uses THIS query, not the plain
// one: a permanently failing pull leaves rows stuck at 'pending' forever,
// and reacting to 'pending' debt would force an endless chain of empty-
// prompt provider turns with nothing new in history to react to. The
// partial debt indexes (idx_async_jobs_debt/idx_session_notices_debt,
// "WHERE wake=1 AND reacted=0 AND delivery != 'void'") do NOT serve this
// query: SQLite does not infer "delivery != 'void'" from "delivery = 'done'".
// async_jobs is narrowed by the (owner_session_id, tool_call_id) primary key
// prefix, session_notices by idx_session_notices_owner (migration
// 20260929000001).
func (q *Queries) VisibleAsyncReactionDebtExists(ctx context.Context, owner string) (sql.NullBool, error) {
	row := q.queryRow(ctx, q.visibleAsyncReactionDebtExistsStmt, visibleAsyncReactionDebtExists, owner)
	var has_debt sql.NullBool
	err := row.Scan(&has_debt)
	return has_debt, err
}

const voidAsyncJobsByAnnounceMessageIDs = `-- name: VoidAsyncJobsByAnnounceMessageIDs :many
UPDATE async_jobs SET delivery = 'void', updated_at = ?1
WHERE owner_session_id = ?2 AND announce_message_id IN (/*SLICE:message_ids*/?)
RETURNING tool_call_id, state, child_session_id, host_id
`

type VoidAsyncJobsByAnnounceMessageIDsParams struct {
	UpdatedAt  int64            `json:"updated_at"`
	Owner      string           `json:"owner"`
	MessageIds []sql.NullString `json:"message_ids"`
}

type VoidAsyncJobsByAnnounceMessageIDsRow struct {
	ToolCallID     string         `json:"tool_call_id"`
	State          string         `json:"state"`
	ChildSessionID sql.NullString `json:"child_session_id"`
	HostID         string         `json:"host_id"`
}

// Rerun truncation (doc sec.3.8): every row whose "started" tool-result
// message (announce_message_id) is among the rows the truncation actually
// deleted must never surface a notice, regardless of its current
// delivery/state -- including a still-'running' row (its stop may have
// raced or failed): the terminal-transition CAS always preserves an
// existing 'void' (TransitionAsyncJobTerminalPreserveVoid), so writing void
// here first closes that race for a late-arriving terminal transition too.
// Keyed by the message id, not tool_call_id: a provider that numbers calls
// per response reuses "call_0", so a tool_call_id match could void a KEPT
// row (or miss an archived one). RETURNING hands the caller the rows to
// stop once the transaction commits.
func (q *Queries) VoidAsyncJobsByAnnounceMessageIDs(ctx context.Context, arg VoidAsyncJobsByAnnounceMessageIDsParams) ([]VoidAsyncJobsByAnnounceMessageIDsRow, error) {
	query := voidAsyncJobsByAnnounceMessageIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.Owner)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoidAsyncJobsByAnnounceMessageIDsRow{}
	for rows.Next() {
		var i VoidAsyncJobsByAnnounceMessageIDsRow
		if err := rows.Scan(
			&i.ToolCallID,
			&i.State,
			&i.ChildSessionID,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidAsyncJobsByToolCallIDs = `-- name: VoidAsyncJobsByToolCallIDs :many
UPDATE async_jobs SET delivery = 'void', updated_at = ?
WHERE owner_session_id = ? AND announce_message_id IS NULL AND tool_call_id IN (/*SLICE:tool_call_ids*/?)
RETURNING tool_call_id, state, child_session_id, host_id
`

type VoidAsyncJobsByToolCallIDsParams struct {
	UpdatedAt      int64    `json:"updated_at"`
	OwnerSessionID string   `json:"owner_session_id"`
	ToolCallIds    []string `json:"tool_call_ids"`
}

type VoidAsyncJobsByToolCallIDsRow struct {
	ToolCallID     string         `json:"tool_call_id"`
	State          string         `json:"state"`
	ChildSessionID sql.NullString `json:"child_session_id"`
	HostID         string         `json:"host_id"`
}

// Legacy arm of the Rerun void, for rows announced before migration
// 20260929000003 (announce_message_id IS NULL): matched by the deleted
// tail's tool_call_ids. Restricted to NULL so a row that DOES name its
// announce message is never matched by a possibly-reused tool_call_id.
func (q *Queries) VoidAsyncJobsByToolCallIDs(ctx context.Context, arg VoidAsyncJobsByToolCallIDsParams) ([]VoidAsyncJobsByToolCallIDsRow, error) {
	query := voidAsyncJobsByToolCallIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.OwnerSessionID)
	if len(arg.ToolCallIds) > 0 {
		for _, v := range arg.ToolCallIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tool_call_ids*/?", strings.Repeat(",?", len(arg.ToolCallIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tool_call_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoidAsyncJobsByToolCallIDsRow{}
	for rows.Next() {
		var i VoidAsyncJobsByToolCallIDsRow
		if err := rows.Scan(
			&i.ToolCallID,
			&i.State,
			&i.ChildSessionID,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidPendingAsyncJobNotice = `-- name: VoidPendingAsyncJobNotice :execrows
UPDATE async_jobs SET delivery = 'void', updated_at = ?
WHERE owner_session_id = ? AND tool_call_id = ? AND delivery = 'pending'
`

type VoidPendingAsyncJobNoticeParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
	ToolCallID     string `json:"tool_call_id"`
}

// A pulled notice whose task-still-running condition failed (doc sec.3.4,
// supervision/wake_only void-at-drain rule) becomes void instead of done.
func (q *Queries) VoidPendingAsyncJobNotice(ctx context.Context, arg VoidPendingAsyncJobNoticeParams) (int64, error) {
	result, err := q.exec(ctx, q.voidPendingAsyncJobNoticeStmt, voidPendingAsyncJobNotice, arg.UpdatedAt, arg.OwnerSessionID, arg.ToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
