// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.ackRunQueueEntryStmt, err = db.PrepareContext(ctx, ackRunQueueEntry); err != nil {
		return nil, fmt.Errorf("error preparing query AckRunQueueEntry: %w", err)
	}
	if q.cleanupExpiredLeasesStmt, err = db.PrepareContext(ctx, cleanupExpiredLeases); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupExpiredLeases: %w", err)
	}
	if q.countMessagesBySessionStmt, err = db.PrepareContext(ctx, countMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountMessagesBySession: %w", err)
	}
	if q.countMessagesMissingUsageStmt, err = db.PrepareContext(ctx, countMessagesMissingUsage); err != nil {
		return nil, fmt.Errorf("error preparing query CountMessagesMissingUsage: %w", err)
	}
	if q.countMessagesMissingUsageInRangeStmt, err = db.PrepareContext(ctx, countMessagesMissingUsageInRange); err != nil {
		return nil, fmt.Errorf("error preparing query CountMessagesMissingUsageInRange: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createPendingInjectStmt, err = db.PrepareContext(ctx, createPendingInject); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePendingInject: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createSessionPermissionStmt, err = db.PrepareContext(ctx, createSessionPermission); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSessionPermission: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteMessageIfTerminalStmt, err = db.PrepareContext(ctx, deleteMessageIfTerminal); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessageIfTerminal: %w", err)
	}
	if q.deleteOrphanOutboxEntryIfPendingStmt, err = db.PrepareContext(ctx, deleteOrphanOutboxEntryIfPending); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOrphanOutboxEntryIfPending: %w", err)
	}
	if q.deletePendingInjectStmt, err = db.PrepareContext(ctx, deletePendingInject); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePendingInject: %w", err)
	}
	if q.deletePermissionStmt, err = db.PrepareContext(ctx, deletePermission); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePermission: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.enqueueRunQueueEntryStmt, err = db.PrepareContext(ctx, enqueueRunQueueEntry); err != nil {
		return nil, fmt.Errorf("error preparing query EnqueueRunQueueEntry: %w", err)
	}
	if q.getAverageResponseTimeStmt, err = db.PrepareContext(ctx, getAverageResponseTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageResponseTime: %w", err)
	}
	if q.getCallTreeActivityStmt, err = db.PrepareContext(ctx, getCallTreeActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetCallTreeActivity: %w", err)
	}
	if q.getCallTreeActivityBatchStmt, err = db.PrepareContext(ctx, getCallTreeActivityBatch); err != nil {
		return nil, fmt.Errorf("error preparing query GetCallTreeActivityBatch: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getHourDayHeatmapStmt, err = db.PrepareContext(ctx, getHourDayHeatmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourDayHeatmap: %w", err)
	}
	if q.getLastSessionStmt, err = db.PrepareContext(ctx, getLastSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getOldestPendingRunQueueEntryForSessionStmt, err = db.PrepareContext(ctx, getOldestPendingRunQueueEntryForSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetOldestPendingRunQueueEntryForSession: %w", err)
	}
	if q.getOrphanOutboxEntryStmt, err = db.PrepareContext(ctx, getOrphanOutboxEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrphanOutboxEntry: %w", err)
	}
	if q.getRecentActivityStmt, err = db.PrepareContext(ctx, getRecentActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentActivity: %w", err)
	}
	if q.getRunQueueEntryStmt, err = db.PrepareContext(ctx, getRunQueueEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetRunQueueEntry: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getSessionCostAccountingStmt, err = db.PrepareContext(ctx, getSessionCostAccounting); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionCostAccounting: %w", err)
	}
	if q.getToolUsageStmt, err = db.PrepareContext(ctx, getToolUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolUsage: %w", err)
	}
	if q.getTotalStatsStmt, err = db.PrepareContext(ctx, getTotalStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalStats: %w", err)
	}
	if q.getTranscriptWindowCursorStmt, err = db.PrepareContext(ctx, getTranscriptWindowCursor); err != nil {
		return nil, fmt.Errorf("error preparing query GetTranscriptWindowCursor: %w", err)
	}
	if q.getUsageByDayStmt, err = db.PrepareContext(ctx, getUsageByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDay: %w", err)
	}
	if q.getUsageByDayOfWeekStmt, err = db.PrepareContext(ctx, getUsageByDayOfWeek); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDayOfWeek: %w", err)
	}
	if q.getUsageByHourStmt, err = db.PrepareContext(ctx, getUsageByHour); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByHour: %w", err)
	}
	if q.getUsageByModelStmt, err = db.PrepareContext(ctx, getUsageByModel); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByModel: %w", err)
	}
	if q.hasOutstandingRunQueueEntryForSessionStmt, err = db.PrepareContext(ctx, hasOutstandingRunQueueEntryForSession); err != nil {
		return nil, fmt.Errorf("error preparing query HasOutstandingRunQueueEntryForSession: %w", err)
	}
	if q.incrementSessionCostStmt, err = db.PrepareContext(ctx, incrementSessionCost); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementSessionCost: %w", err)
	}
	if q.leaseRunQueueEntryByIDStmt, err = db.PrepareContext(ctx, leaseRunQueueEntryByID); err != nil {
		return nil, fmt.Errorf("error preparing query LeaseRunQueueEntryByID: %w", err)
	}
	if q.listAllSessionPermissionsStmt, err = db.PrepareContext(ctx, listAllSessionPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSessionPermissions: %w", err)
	}
	if q.listAllSessionsStmt, err = db.PrepareContext(ctx, listAllSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSessions: %w", err)
	}
	if q.listAllUserMessagesStmt, err = db.PrepareContext(ctx, listAllUserMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMessages: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMessagesBySessionAtCreatedAtStmt, err = db.PrepareContext(ctx, listMessagesBySessionAtCreatedAt); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySessionAtCreatedAt: %w", err)
	}
	if q.listMessagesBySessionOlderThanCreatedAtStmt, err = db.PrepareContext(ctx, listMessagesBySessionOlderThanCreatedAt); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySessionOlderThanCreatedAt: %w", err)
	}
	if q.listMessagesBySessionPaginatedStmt, err = db.PrepareContext(ctx, listMessagesBySessionPaginated); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySessionPaginated: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listPendingInjectsBySessionStmt, err = db.PrepareContext(ctx, listPendingInjectsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingInjectsBySession: %w", err)
	}
	if q.listPendingOrphanOutboxEntriesStmt, err = db.PrepareContext(ctx, listPendingOrphanOutboxEntries); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingOrphanOutboxEntries: %w", err)
	}
	if q.listPendingRunQueueEntriesStmt, err = db.PrepareContext(ctx, listPendingRunQueueEntries); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingRunQueueEntries: %w", err)
	}
	if q.listSessionPermissionsStmt, err = db.PrepareContext(ctx, listSessionPermissions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionPermissions: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listStaleLeasedRunQueueEntriesStmt, err = db.PrepareContext(ctx, listStaleLeasedRunQueueEntries); err != nil {
		return nil, fmt.Errorf("error preparing query ListStaleLeasedRunQueueEntries: %w", err)
	}
	if q.listSubSessionsStmt, err = db.PrepareContext(ctx, listSubSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSubSessions: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.matchSessionPermissionStmt, err = db.PrepareContext(ctx, matchSessionPermission); err != nil {
		return nil, fmt.Errorf("error preparing query MatchSessionPermission: %w", err)
	}
	if q.nackRunQueueEntryStmt, err = db.PrepareContext(ctx, nackRunQueueEntry); err != nil {
		return nil, fmt.Errorf("error preparing query NackRunQueueEntry: %w", err)
	}
	if q.nackRunQueueEntryNoAttemptPenaltyStmt, err = db.PrepareContext(ctx, nackRunQueueEntryNoAttemptPenalty); err != nil {
		return nil, fmt.Errorf("error preparing query NackRunQueueEntryNoAttemptPenalty: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.recordOrphanOutboxFailureStmt, err = db.PrepareContext(ctx, recordOrphanOutboxFailure); err != nil {
		return nil, fmt.Errorf("error preparing query RecordOrphanOutboxFailure: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.renewRunQueueLeaseStmt, err = db.PrepareContext(ctx, renewRunQueueLease); err != nil {
		return nil, fmt.Errorf("error preparing query RenewRunQueueLease: %w", err)
	}
	if q.setParentCostAccountedStmt, err = db.PrepareContext(ctx, setParentCostAccounted); err != nil {
		return nil, fmt.Errorf("error preparing query SetParentCostAccounted: %w", err)
	}
	if q.sumMessageUsageByDayInRangeStmt, err = db.PrepareContext(ctx, sumMessageUsageByDayInRange); err != nil {
		return nil, fmt.Errorf("error preparing query SumMessageUsageByDayInRange: %w", err)
	}
	if q.sumMessageUsageByModelInRangeStmt, err = db.PrepareContext(ctx, sumMessageUsageByModelInRange); err != nil {
		return nil, fmt.Errorf("error preparing query SumMessageUsageByModelInRange: %w", err)
	}
	if q.sumMessageUsageBySessionStmt, err = db.PrepareContext(ctx, sumMessageUsageBySession); err != nil {
		return nil, fmt.Errorf("error preparing query SumMessageUsageBySession: %w", err)
	}
	if q.terminalFailRunQueueEntryStmt, err = db.PrepareContext(ctx, terminalFailRunQueueEntry); err != nil {
		return nil, fmt.Errorf("error preparing query TerminalFailRunQueueEntry: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateMessageIfNotTerminalStmt, err = db.PrepareContext(ctx, updateMessageIfNotTerminal); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessageIfNotTerminal: %w", err)
	}
	if q.updateMessagePinnedStmt, err = db.PrepareContext(ctx, updateMessagePinned); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessagePinned: %w", err)
	}
	if q.updateMessageUsageStmt, err = db.PrepareContext(ctx, updateMessageUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessageUsage: %w", err)
	}
	if q.updatePermissionEnabledStmt, err = db.PrepareContext(ctx, updatePermissionEnabled); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePermissionEnabled: %w", err)
	}
	if q.updateSessionModelsStmt, err = db.PrepareContext(ctx, updateSessionModels); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionModels: %w", err)
	}
	if q.updateSessionReasoningEffortStmt, err = db.PrepareContext(ctx, updateSessionReasoningEffort); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionReasoningEffort: %w", err)
	}
	if q.updateSessionSystemPromptStmt, err = db.PrepareContext(ctx, updateSessionSystemPrompt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionSystemPrompt: %w", err)
	}
	if q.updateSessionWorkerReviewerModelsStmt, err = db.PrepareContext(ctx, updateSessionWorkerReviewerModels); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionWorkerReviewerModels: %w", err)
	}
	if q.updateSessionWorkerReviewerReasoningEffortStmt, err = db.PrepareContext(ctx, updateSessionWorkerReviewerReasoningEffort); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionWorkerReviewerReasoningEffort: %w", err)
	}
	if q.writeToOrphanOutboxStmt, err = db.PrepareContext(ctx, writeToOrphanOutbox); err != nil {
		return nil, fmt.Errorf("error preparing query WriteToOrphanOutbox: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.ackRunQueueEntryStmt != nil {
		if cerr := q.ackRunQueueEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ackRunQueueEntryStmt: %w", cerr)
		}
	}
	if q.cleanupExpiredLeasesStmt != nil {
		if cerr := q.cleanupExpiredLeasesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupExpiredLeasesStmt: %w", cerr)
		}
	}
	if q.countMessagesBySessionStmt != nil {
		if cerr := q.countMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.countMessagesMissingUsageStmt != nil {
		if cerr := q.countMessagesMissingUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMessagesMissingUsageStmt: %w", cerr)
		}
	}
	if q.countMessagesMissingUsageInRangeStmt != nil {
		if cerr := q.countMessagesMissingUsageInRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMessagesMissingUsageInRangeStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createPendingInjectStmt != nil {
		if cerr := q.createPendingInjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPendingInjectStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createSessionPermissionStmt != nil {
		if cerr := q.createSessionPermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionPermissionStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteMessageIfTerminalStmt != nil {
		if cerr := q.deleteMessageIfTerminalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageIfTerminalStmt: %w", cerr)
		}
	}
	if q.deleteOrphanOutboxEntryIfPendingStmt != nil {
		if cerr := q.deleteOrphanOutboxEntryIfPendingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOrphanOutboxEntryIfPendingStmt: %w", cerr)
		}
	}
	if q.deletePendingInjectStmt != nil {
		if cerr := q.deletePendingInjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePendingInjectStmt: %w", cerr)
		}
	}
	if q.deletePermissionStmt != nil {
		if cerr := q.deletePermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePermissionStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.enqueueRunQueueEntryStmt != nil {
		if cerr := q.enqueueRunQueueEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enqueueRunQueueEntryStmt: %w", cerr)
		}
	}
	if q.getAverageResponseTimeStmt != nil {
		if cerr := q.getAverageResponseTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageResponseTimeStmt: %w", cerr)
		}
	}
	if q.getCallTreeActivityStmt != nil {
		if cerr := q.getCallTreeActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCallTreeActivityStmt: %w", cerr)
		}
	}
	if q.getCallTreeActivityBatchStmt != nil {
		if cerr := q.getCallTreeActivityBatchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCallTreeActivityBatchStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getHourDayHeatmapStmt != nil {
		if cerr := q.getHourDayHeatmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourDayHeatmapStmt: %w", cerr)
		}
	}
	if q.getLastSessionStmt != nil {
		if cerr := q.getLastSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getOldestPendingRunQueueEntryForSessionStmt != nil {
		if cerr := q.getOldestPendingRunQueueEntryForSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOldestPendingRunQueueEntryForSessionStmt: %w", cerr)
		}
	}
	if q.getOrphanOutboxEntryStmt != nil {
		if cerr := q.getOrphanOutboxEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrphanOutboxEntryStmt: %w", cerr)
		}
	}
	if q.getRecentActivityStmt != nil {
		if cerr := q.getRecentActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentActivityStmt: %w", cerr)
		}
	}
	if q.getRunQueueEntryStmt != nil {
		if cerr := q.getRunQueueEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRunQueueEntryStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getSessionCostAccountingStmt != nil {
		if cerr := q.getSessionCostAccountingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionCostAccountingStmt: %w", cerr)
		}
	}
	if q.getToolUsageStmt != nil {
		if cerr := q.getToolUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolUsageStmt: %w", cerr)
		}
	}
	if q.getTotalStatsStmt != nil {
		if cerr := q.getTotalStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalStatsStmt: %w", cerr)
		}
	}
	if q.getTranscriptWindowCursorStmt != nil {
		if cerr := q.getTranscriptWindowCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTranscriptWindowCursorStmt: %w", cerr)
		}
	}
	if q.getUsageByDayStmt != nil {
		if cerr := q.getUsageByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayStmt: %w", cerr)
		}
	}
	if q.getUsageByDayOfWeekStmt != nil {
		if cerr := q.getUsageByDayOfWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayOfWeekStmt: %w", cerr)
		}
	}
	if q.getUsageByHourStmt != nil {
		if cerr := q.getUsageByHourStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByHourStmt: %w", cerr)
		}
	}
	if q.getUsageByModelStmt != nil {
		if cerr := q.getUsageByModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByModelStmt: %w", cerr)
		}
	}
	if q.hasOutstandingRunQueueEntryForSessionStmt != nil {
		if cerr := q.hasOutstandingRunQueueEntryForSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasOutstandingRunQueueEntryForSessionStmt: %w", cerr)
		}
	}
	if q.incrementSessionCostStmt != nil {
		if cerr := q.incrementSessionCostStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementSessionCostStmt: %w", cerr)
		}
	}
	if q.leaseRunQueueEntryByIDStmt != nil {
		if cerr := q.leaseRunQueueEntryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing leaseRunQueueEntryByIDStmt: %w", cerr)
		}
	}
	if q.listAllSessionPermissionsStmt != nil {
		if cerr := q.listAllSessionPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSessionPermissionsStmt: %w", cerr)
		}
	}
	if q.listAllSessionsStmt != nil {
		if cerr := q.listAllSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSessionsStmt: %w", cerr)
		}
	}
	if q.listAllUserMessagesStmt != nil {
		if cerr := q.listAllUserMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMessagesStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionAtCreatedAtStmt != nil {
		if cerr := q.listMessagesBySessionAtCreatedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionAtCreatedAtStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionOlderThanCreatedAtStmt != nil {
		if cerr := q.listMessagesBySessionOlderThanCreatedAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionOlderThanCreatedAtStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionPaginatedStmt != nil {
		if cerr := q.listMessagesBySessionPaginatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionPaginatedStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listPendingInjectsBySessionStmt != nil {
		if cerr := q.listPendingInjectsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingInjectsBySessionStmt: %w", cerr)
		}
	}
	if q.listPendingOrphanOutboxEntriesStmt != nil {
		if cerr := q.listPendingOrphanOutboxEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingOrphanOutboxEntriesStmt: %w", cerr)
		}
	}
	if q.listPendingRunQueueEntriesStmt != nil {
		if cerr := q.listPendingRunQueueEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingRunQueueEntriesStmt: %w", cerr)
		}
	}
	if q.listSessionPermissionsStmt != nil {
		if cerr := q.listSessionPermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionPermissionsStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listStaleLeasedRunQueueEntriesStmt != nil {
		if cerr := q.listStaleLeasedRunQueueEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStaleLeasedRunQueueEntriesStmt: %w", cerr)
		}
	}
	if q.listSubSessionsStmt != nil {
		if cerr := q.listSubSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSubSessionsStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.matchSessionPermissionStmt != nil {
		if cerr := q.matchSessionPermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing matchSessionPermissionStmt: %w", cerr)
		}
	}
	if q.nackRunQueueEntryStmt != nil {
		if cerr := q.nackRunQueueEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing nackRunQueueEntryStmt: %w", cerr)
		}
	}
	if q.nackRunQueueEntryNoAttemptPenaltyStmt != nil {
		if cerr := q.nackRunQueueEntryNoAttemptPenaltyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing nackRunQueueEntryNoAttemptPenaltyStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.recordOrphanOutboxFailureStmt != nil {
		if cerr := q.recordOrphanOutboxFailureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordOrphanOutboxFailureStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.renewRunQueueLeaseStmt != nil {
		if cerr := q.renewRunQueueLeaseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renewRunQueueLeaseStmt: %w", cerr)
		}
	}
	if q.setParentCostAccountedStmt != nil {
		if cerr := q.setParentCostAccountedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setParentCostAccountedStmt: %w", cerr)
		}
	}
	if q.sumMessageUsageByDayInRangeStmt != nil {
		if cerr := q.sumMessageUsageByDayInRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sumMessageUsageByDayInRangeStmt: %w", cerr)
		}
	}
	if q.sumMessageUsageByModelInRangeStmt != nil {
		if cerr := q.sumMessageUsageByModelInRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sumMessageUsageByModelInRangeStmt: %w", cerr)
		}
	}
	if q.sumMessageUsageBySessionStmt != nil {
		if cerr := q.sumMessageUsageBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sumMessageUsageBySessionStmt: %w", cerr)
		}
	}
	if q.terminalFailRunQueueEntryStmt != nil {
		if cerr := q.terminalFailRunQueueEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing terminalFailRunQueueEntryStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateMessageIfNotTerminalStmt != nil {
		if cerr := q.updateMessageIfNotTerminalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageIfNotTerminalStmt: %w", cerr)
		}
	}
	if q.updateMessagePinnedStmt != nil {
		if cerr := q.updateMessagePinnedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessagePinnedStmt: %w", cerr)
		}
	}
	if q.updateMessageUsageStmt != nil {
		if cerr := q.updateMessageUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageUsageStmt: %w", cerr)
		}
	}
	if q.updatePermissionEnabledStmt != nil {
		if cerr := q.updatePermissionEnabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePermissionEnabledStmt: %w", cerr)
		}
	}
	if q.updateSessionModelsStmt != nil {
		if cerr := q.updateSessionModelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionModelsStmt: %w", cerr)
		}
	}
	if q.updateSessionReasoningEffortStmt != nil {
		if cerr := q.updateSessionReasoningEffortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionReasoningEffortStmt: %w", cerr)
		}
	}
	if q.updateSessionSystemPromptStmt != nil {
		if cerr := q.updateSessionSystemPromptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionSystemPromptStmt: %w", cerr)
		}
	}
	if q.updateSessionWorkerReviewerModelsStmt != nil {
		if cerr := q.updateSessionWorkerReviewerModelsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionWorkerReviewerModelsStmt: %w", cerr)
		}
	}
	if q.updateSessionWorkerReviewerReasoningEffortStmt != nil {
		if cerr := q.updateSessionWorkerReviewerReasoningEffortStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionWorkerReviewerReasoningEffortStmt: %w", cerr)
		}
	}
	if q.writeToOrphanOutboxStmt != nil {
		if cerr := q.writeToOrphanOutboxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing writeToOrphanOutboxStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                             DBTX
	tx                                             *sql.Tx
	ackRunQueueEntryStmt                           *sql.Stmt
	cleanupExpiredLeasesStmt                       *sql.Stmt
	countMessagesBySessionStmt                     *sql.Stmt
	countMessagesMissingUsageStmt                  *sql.Stmt
	countMessagesMissingUsageInRangeStmt           *sql.Stmt
	createFileStmt                                 *sql.Stmt
	createMessageStmt                              *sql.Stmt
	createPendingInjectStmt                        *sql.Stmt
	createSessionStmt                              *sql.Stmt
	createSessionPermissionStmt                    *sql.Stmt
	deleteFileStmt                                 *sql.Stmt
	deleteMessageStmt                              *sql.Stmt
	deleteMessageIfTerminalStmt                    *sql.Stmt
	deleteOrphanOutboxEntryIfPendingStmt           *sql.Stmt
	deletePendingInjectStmt                        *sql.Stmt
	deletePermissionStmt                           *sql.Stmt
	deleteSessionStmt                              *sql.Stmt
	deleteSessionFilesStmt                         *sql.Stmt
	deleteSessionMessagesStmt                      *sql.Stmt
	enqueueRunQueueEntryStmt                       *sql.Stmt
	getAverageResponseTimeStmt                     *sql.Stmt
	getCallTreeActivityStmt                        *sql.Stmt
	getCallTreeActivityBatchStmt                   *sql.Stmt
	getFileStmt                                    *sql.Stmt
	getFileByPathAndSessionStmt                    *sql.Stmt
	getFileReadStmt                                *sql.Stmt
	getHourDayHeatmapStmt                          *sql.Stmt
	getLastSessionStmt                             *sql.Stmt
	getMessageStmt                                 *sql.Stmt
	getOldestPendingRunQueueEntryForSessionStmt    *sql.Stmt
	getOrphanOutboxEntryStmt                       *sql.Stmt
	getRecentActivityStmt                          *sql.Stmt
	getRunQueueEntryStmt                           *sql.Stmt
	getSessionByIDStmt                             *sql.Stmt
	getSessionCostAccountingStmt                   *sql.Stmt
	getToolUsageStmt                               *sql.Stmt
	getTotalStatsStmt                              *sql.Stmt
	getTranscriptWindowCursorStmt                  *sql.Stmt
	getUsageByDayStmt                              *sql.Stmt
	getUsageByDayOfWeekStmt                        *sql.Stmt
	getUsageByHourStmt                             *sql.Stmt
	getUsageByModelStmt                            *sql.Stmt
	hasOutstandingRunQueueEntryForSessionStmt      *sql.Stmt
	incrementSessionCostStmt                       *sql.Stmt
	leaseRunQueueEntryByIDStmt                     *sql.Stmt
	listAllSessionPermissionsStmt                  *sql.Stmt
	listAllSessionsStmt                            *sql.Stmt
	listAllUserMessagesStmt                        *sql.Stmt
	listFilesByPathStmt                            *sql.Stmt
	listFilesBySessionStmt                         *sql.Stmt
	listLatestSessionFilesStmt                     *sql.Stmt
	listMessagesBySessionStmt                      *sql.Stmt
	listMessagesBySessionAtCreatedAtStmt           *sql.Stmt
	listMessagesBySessionOlderThanCreatedAtStmt    *sql.Stmt
	listMessagesBySessionPaginatedStmt             *sql.Stmt
	listNewFilesStmt                               *sql.Stmt
	listPendingInjectsBySessionStmt                *sql.Stmt
	listPendingOrphanOutboxEntriesStmt             *sql.Stmt
	listPendingRunQueueEntriesStmt                 *sql.Stmt
	listSessionPermissionsStmt                     *sql.Stmt
	listSessionReadFilesStmt                       *sql.Stmt
	listSessionsStmt                               *sql.Stmt
	listStaleLeasedRunQueueEntriesStmt             *sql.Stmt
	listSubSessionsStmt                            *sql.Stmt
	listUserMessagesBySessionStmt                  *sql.Stmt
	matchSessionPermissionStmt                     *sql.Stmt
	nackRunQueueEntryStmt                          *sql.Stmt
	nackRunQueueEntryNoAttemptPenaltyStmt          *sql.Stmt
	recordFileReadStmt                             *sql.Stmt
	recordOrphanOutboxFailureStmt                  *sql.Stmt
	renameSessionStmt                              *sql.Stmt
	renewRunQueueLeaseStmt                         *sql.Stmt
	setParentCostAccountedStmt                     *sql.Stmt
	sumMessageUsageByDayInRangeStmt                *sql.Stmt
	sumMessageUsageByModelInRangeStmt              *sql.Stmt
	sumMessageUsageBySessionStmt                   *sql.Stmt
	terminalFailRunQueueEntryStmt                  *sql.Stmt
	updateMessageStmt                              *sql.Stmt
	updateMessageIfNotTerminalStmt                 *sql.Stmt
	updateMessagePinnedStmt                        *sql.Stmt
	updateMessageUsageStmt                         *sql.Stmt
	updatePermissionEnabledStmt                    *sql.Stmt
	updateSessionModelsStmt                        *sql.Stmt
	updateSessionReasoningEffortStmt               *sql.Stmt
	updateSessionSystemPromptStmt                  *sql.Stmt
	updateSessionWorkerReviewerModelsStmt          *sql.Stmt
	updateSessionWorkerReviewerReasoningEffortStmt *sql.Stmt
	writeToOrphanOutboxStmt                        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                             tx,
		tx:                                             tx,
		ackRunQueueEntryStmt:                           q.ackRunQueueEntryStmt,
		cleanupExpiredLeasesStmt:                       q.cleanupExpiredLeasesStmt,
		countMessagesBySessionStmt:                     q.countMessagesBySessionStmt,
		countMessagesMissingUsageStmt:                  q.countMessagesMissingUsageStmt,
		countMessagesMissingUsageInRangeStmt:           q.countMessagesMissingUsageInRangeStmt,
		createFileStmt:                                 q.createFileStmt,
		createMessageStmt:                              q.createMessageStmt,
		createPendingInjectStmt:                        q.createPendingInjectStmt,
		createSessionStmt:                              q.createSessionStmt,
		createSessionPermissionStmt:                    q.createSessionPermissionStmt,
		deleteFileStmt:                                 q.deleteFileStmt,
		deleteMessageStmt:                              q.deleteMessageStmt,
		deleteMessageIfTerminalStmt:                    q.deleteMessageIfTerminalStmt,
		deleteOrphanOutboxEntryIfPendingStmt:           q.deleteOrphanOutboxEntryIfPendingStmt,
		deletePendingInjectStmt:                        q.deletePendingInjectStmt,
		deletePermissionStmt:                           q.deletePermissionStmt,
		deleteSessionStmt:                              q.deleteSessionStmt,
		deleteSessionFilesStmt:                         q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:                      q.deleteSessionMessagesStmt,
		enqueueRunQueueEntryStmt:                       q.enqueueRunQueueEntryStmt,
		getAverageResponseTimeStmt:                     q.getAverageResponseTimeStmt,
		getCallTreeActivityStmt:                        q.getCallTreeActivityStmt,
		getCallTreeActivityBatchStmt:                   q.getCallTreeActivityBatchStmt,
		getFileStmt:                                    q.getFileStmt,
		getFileByPathAndSessionStmt:                    q.getFileByPathAndSessionStmt,
		getFileReadStmt:                                q.getFileReadStmt,
		getHourDayHeatmapStmt:                          q.getHourDayHeatmapStmt,
		getLastSessionStmt:                             q.getLastSessionStmt,
		getMessageStmt:                                 q.getMessageStmt,
		getOldestPendingRunQueueEntryForSessionStmt:    q.getOldestPendingRunQueueEntryForSessionStmt,
		getOrphanOutboxEntryStmt:                       q.getOrphanOutboxEntryStmt,
		getRecentActivityStmt:                          q.getRecentActivityStmt,
		getRunQueueEntryStmt:                           q.getRunQueueEntryStmt,
		getSessionByIDStmt:                             q.getSessionByIDStmt,
		getSessionCostAccountingStmt:                   q.getSessionCostAccountingStmt,
		getToolUsageStmt:                               q.getToolUsageStmt,
		getTotalStatsStmt:                              q.getTotalStatsStmt,
		getTranscriptWindowCursorStmt:                  q.getTranscriptWindowCursorStmt,
		getUsageByDayStmt:                              q.getUsageByDayStmt,
		getUsageByDayOfWeekStmt:                        q.getUsageByDayOfWeekStmt,
		getUsageByHourStmt:                             q.getUsageByHourStmt,
		getUsageByModelStmt:                            q.getUsageByModelStmt,
		hasOutstandingRunQueueEntryForSessionStmt:      q.hasOutstandingRunQueueEntryForSessionStmt,
		incrementSessionCostStmt:                       q.incrementSessionCostStmt,
		leaseRunQueueEntryByIDStmt:                     q.leaseRunQueueEntryByIDStmt,
		listAllSessionPermissionsStmt:                  q.listAllSessionPermissionsStmt,
		listAllSessionsStmt:                            q.listAllSessionsStmt,
		listAllUserMessagesStmt:                        q.listAllUserMessagesStmt,
		listFilesByPathStmt:                            q.listFilesByPathStmt,
		listFilesBySessionStmt:                         q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:                     q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:                      q.listMessagesBySessionStmt,
		listMessagesBySessionAtCreatedAtStmt:           q.listMessagesBySessionAtCreatedAtStmt,
		listMessagesBySessionOlderThanCreatedAtStmt:    q.listMessagesBySessionOlderThanCreatedAtStmt,
		listMessagesBySessionPaginatedStmt:             q.listMessagesBySessionPaginatedStmt,
		listNewFilesStmt:                               q.listNewFilesStmt,
		listPendingInjectsBySessionStmt:                q.listPendingInjectsBySessionStmt,
		listPendingOrphanOutboxEntriesStmt:             q.listPendingOrphanOutboxEntriesStmt,
		listPendingRunQueueEntriesStmt:                 q.listPendingRunQueueEntriesStmt,
		listSessionPermissionsStmt:                     q.listSessionPermissionsStmt,
		listSessionReadFilesStmt:                       q.listSessionReadFilesStmt,
		listSessionsStmt:                               q.listSessionsStmt,
		listStaleLeasedRunQueueEntriesStmt:             q.listStaleLeasedRunQueueEntriesStmt,
		listSubSessionsStmt:                            q.listSubSessionsStmt,
		listUserMessagesBySessionStmt:                  q.listUserMessagesBySessionStmt,
		matchSessionPermissionStmt:                     q.matchSessionPermissionStmt,
		nackRunQueueEntryStmt:                          q.nackRunQueueEntryStmt,
		nackRunQueueEntryNoAttemptPenaltyStmt:          q.nackRunQueueEntryNoAttemptPenaltyStmt,
		recordFileReadStmt:                             q.recordFileReadStmt,
		recordOrphanOutboxFailureStmt:                  q.recordOrphanOutboxFailureStmt,
		renameSessionStmt:                              q.renameSessionStmt,
		renewRunQueueLeaseStmt:                         q.renewRunQueueLeaseStmt,
		setParentCostAccountedStmt:                     q.setParentCostAccountedStmt,
		sumMessageUsageByDayInRangeStmt:                q.sumMessageUsageByDayInRangeStmt,
		sumMessageUsageByModelInRangeStmt:              q.sumMessageUsageByModelInRangeStmt,
		sumMessageUsageBySessionStmt:                   q.sumMessageUsageBySessionStmt,
		terminalFailRunQueueEntryStmt:                  q.terminalFailRunQueueEntryStmt,
		updateMessageStmt:                              q.updateMessageStmt,
		updateMessageIfNotTerminalStmt:                 q.updateMessageIfNotTerminalStmt,
		updateMessagePinnedStmt:                        q.updateMessagePinnedStmt,
		updateMessageUsageStmt:                         q.updateMessageUsageStmt,
		updatePermissionEnabledStmt:                    q.updatePermissionEnabledStmt,
		updateSessionModelsStmt:                        q.updateSessionModelsStmt,
		updateSessionReasoningEffortStmt:               q.updateSessionReasoningEffortStmt,
		updateSessionSystemPromptStmt:                  q.updateSessionSystemPromptStmt,
		updateSessionWorkerReviewerModelsStmt:          q.updateSessionWorkerReviewerModelsStmt,
		updateSessionWorkerReviewerReasoningEffortStmt: q.updateSessionWorkerReviewerReasoningEffortStmt,
		writeToOrphanOutboxStmt:                        q.writeToOrphanOutboxStmt,
	}
}
