// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT COUNT(*)
FROM messages
WHERE session_id = ?
`

func (q *Queries) CountMessagesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countMessagesBySessionStmt, countMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesMissingUsage = `-- name: CountMessagesMissingUsage :one
SELECT COUNT(*) FROM messages
WHERE session_id = ? AND role = 'assistant' AND total_tokens IS NULL
`

// Assistant rows in a session that carry no usage at all. Reported alongside
// any aggregate so "12% cache hit" is never presented without saying how many
// messages it was computed over.
func (q *Queries) CountMessagesMissingUsage(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countMessagesMissingUsageStmt, countMessagesMissingUsage, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesMissingUsageInRange = `-- name: CountMessagesMissingUsageInRange :one
SELECT CAST(COUNT(*) AS INTEGER) FROM messages
WHERE role = 'assistant'
  AND total_tokens IS NULL
  AND created_at >= ?
  AND created_at <= ?
`

type CountMessagesMissingUsageInRangeParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
}

// Assistant messages in the window with no usage recorded. Reported next to
// any aggregate so a ratio is never presented as the period's when it was
// computed over a fraction of it.
func (q *Queries) CountMessagesMissingUsageInRange(ctx context.Context, arg CountMessagesMissingUsageInRangeParams) (int64, error) {
	row := q.queryRow(ctx, q.countMessagesMissingUsageInRangeStmt, countMessagesMissingUsageInRange, arg.CreatedAt, arg.CreatedAt_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    model,
    provider,
    reasoning_effort,
    is_summary_message,
    hidden,
    auto_resumed,
    background_job_notice,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
`

type CreateMessageParams struct {
	ID                  string         `json:"id"`
	SessionID           string         `json:"session_id"`
	Role                string         `json:"role"`
	Parts               string         `json:"parts"`
	Model               sql.NullString `json:"model"`
	Provider            sql.NullString `json:"provider"`
	ReasoningEffort     sql.NullString `json:"reasoning_effort"`
	IsSummaryMessage    int64          `json:"is_summary_message"`
	Hidden              int64          `json:"hidden"`
	AutoResumed         int64          `json:"auto_resumed"`
	BackgroundJobNotice int64          `json:"background_job_notice"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
		arg.ReasoningEffort,
		arg.IsSummaryMessage,
		arg.Hidden,
		arg.AutoResumed,
		arg.BackgroundJobNotice,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Pinned,
		&i.Hidden,
		&i.ReasoningEffort,
		&i.AutoResumed,
		&i.BackgroundJobNotice,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.UsageProvider,
		&i.UsageModel,
		&i.CacheSupport,
		&i.UsageEstimated,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
FROM messages
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Pinned,
		&i.Hidden,
		&i.ReasoningEffort,
		&i.AutoResumed,
		&i.BackgroundJobNotice,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.TotalTokens,
		&i.CostUsd,
		&i.UsageProvider,
		&i.UsageModel,
		&i.CacheSupport,
		&i.UsageEstimated,
	)
	return i, err
}

const getTranscriptWindowCursor = `-- name: GetTranscriptWindowCursor :one
SELECT
    created_at,
    CAST(rowid AS INTEGER) AS row_id,
    COUNT(*) OVER () AS total_count
FROM messages
WHERE session_id = ?
ORDER BY created_at DESC, rowid DESC
LIMIT 1 OFFSET ?
`

type GetTranscriptWindowCursorParams struct {
	SessionID string `json:"session_id"`
	Offset    int64  `json:"offset"`
}

type GetTranscriptWindowCursorRow struct {
	CreatedAt  int64 `json:"created_at"`
	RowID      int64 `json:"row_id"`
	TotalCount int64 `json:"total_count"`
}

// Returns, in a SINGLE round trip, the (created_at, rowid) of the row at
// `offset` positions back from the newest message in the session, together
// with the session's total message count as of that same statement
// execution (SQLite evaluates COUNT(*) OVER() over the full WHERE-matched row
// set before LIMIT/OFFSET are applied, in the same query plan as the LIMIT 1
// OFFSET ? row selection - both numbers come from one consistent snapshot).
//
// This is the fix for the cross-statement race in read_delegation_transcript.go:
// previously Count() and ListPaginated() were two independent queries, so a
// message inserted between them (the normal case while observing a live
// sub-agent) could make the total and the offset-derived window disagree.
// message.Service.ListPaginatedSnapshot calls this query FIRST to pin down a
// single high-water-mark snapshot (the boundary row's created_at/row_id, plus
// total), then fetches the window strictly at-or-before that boundary via
// ListMessagesBySessionOlderThanCreatedAt + ListMessagesBySessionAtCreatedAt.
// Any message inserted after this query executes is newer than the pinned
// boundary and is therefore correctly excluded from both the "total" figure
// and the follow-up window fetch - the read as a whole reflects one
// consistent point in time rather than drifting across separate round trips.
//
// created_at/row_id are NULL when offset falls at or past the end of the
// session's messages (i.e. there is no row at that position): callers must
// treat NULL as "start of history", matching offset's existing clamp-to-empty
// behavior in clampTranscriptWindow.
//
// row_id is exposed via CAST(rowid AS INTEGER): sqlc's SQLite catalog has no
// notion of SQLite's implicit rowid column outside ORDER BY (confirmed by
// hand: any bare `rowid` reference in a WHERE clause or plain SELECT-list
// position fails static analysis with "column \"rowid\" does not exist",
// while the identical reference wrapped in CAST(... AS INTEGER) in the
// SELECT list is accepted) - see ListMessagesBySessionOlderThanCreatedAt's
// comment for why the keyset filter itself therefore avoids rowid in a WHERE
// clause entirely rather than fighting this further.
func (q *Queries) GetTranscriptWindowCursor(ctx context.Context, arg GetTranscriptWindowCursorParams) (GetTranscriptWindowCursorRow, error) {
	row := q.queryRow(ctx, q.getTranscriptWindowCursorStmt, getTranscriptWindowCursor, arg.SessionID, arg.Offset)
	var i GetTranscriptWindowCursorRow
	err := row.Scan(&i.CreatedAt, &i.RowID, &i.TotalCount)
	return i, err
}

const listAllUserMessages = `-- name: ListAllUserMessages :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
FROM messages
WHERE role = 'user'
ORDER BY created_at DESC, rowid DESC
`

// rowid is the tie-breaker: see ListUserMessagesBySession above - identical
// reasoning applies across all sessions, not just one.
func (q *Queries) ListAllUserMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.query(ctx, q.listAllUserMessagesStmt, listAllUserMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.UsageProvider,
			&i.UsageModel,
			&i.CacheSupport,
			&i.UsageEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
FROM messages
WHERE session_id = ?
ORDER BY created_at ASC, rowid ASC
`

// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
// turn produces dozens of rows with an identical created_at. Without a total
// order SQLite does not guarantee a stable order among those ties. This is the
// same class of bug fixed for ListMessagesBySessionPaginated (see its comment
// below) - here applied to the oldest-first, non-paginated variant, so
// (created_at ASC, rowid ASC) is a deterministic oldest-first total order.
// rowid is SQLite's implicit monotonic insertion counter (messages.id is a
// non-monotonic UUID, unsuitable as a tiebreaker).
func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionStmt, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.UsageProvider,
			&i.UsageModel,
			&i.CacheSupport,
			&i.UsageEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionAtCreatedAt = `-- name: ListMessagesBySessionAtCreatedAt :many
SELECT
    messages.id, messages.session_id, messages.role, messages.parts, messages.model, messages.created_at, messages.updated_at, messages.finished_at, messages.provider, messages.is_summary_message, messages.pinned, messages.hidden, messages.reasoning_effort, messages.auto_resumed, messages.background_job_notice, messages.input_tokens, messages.output_tokens, messages.reasoning_tokens, messages.cache_creation_tokens, messages.cache_read_tokens, messages.total_tokens, messages.cost_usd, messages.usage_provider, messages.usage_model, messages.cache_support, messages.usage_estimated,
    CAST(rowid AS INTEGER) AS row_id
FROM messages
WHERE session_id = ?
  AND created_at = ?
ORDER BY rowid DESC
`

type ListMessagesBySessionAtCreatedAtParams struct {
	SessionID string `json:"session_id"`
	CreatedAt int64  `json:"created_at"`
}

type ListMessagesBySessionAtCreatedAtRow struct {
	Message Message `json:"message"`
	RowID   int64   `json:"row_id"`
}

// Second half of the keyset pagination pair (see
// ListMessagesBySessionOlderThanCreatedAt): returns every message in the
// session sharing the exact boundary second, WITH its rowid (via
// CAST(rowid AS INTEGER), the one position sqlc's SQLite catalog accepts a
// bare rowid reference in - see GetTranscriptWindowCursor's comment), so the
// Go caller can apply the `rowid < boundary_row_id` half of the tiebreaker
// itself and merge the result with the older-seconds query above into one
// deterministic (created_at DESC, rowid DESC) window.
func (q *Queries) ListMessagesBySessionAtCreatedAt(ctx context.Context, arg ListMessagesBySessionAtCreatedAtParams) ([]ListMessagesBySessionAtCreatedAtRow, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionAtCreatedAtStmt, listMessagesBySessionAtCreatedAt, arg.SessionID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBySessionAtCreatedAtRow{}
	for rows.Next() {
		var i ListMessagesBySessionAtCreatedAtRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.SessionID,
			&i.Message.Role,
			&i.Message.Parts,
			&i.Message.Model,
			&i.Message.CreatedAt,
			&i.Message.UpdatedAt,
			&i.Message.FinishedAt,
			&i.Message.Provider,
			&i.Message.IsSummaryMessage,
			&i.Message.Pinned,
			&i.Message.Hidden,
			&i.Message.ReasoningEffort,
			&i.Message.AutoResumed,
			&i.Message.BackgroundJobNotice,
			&i.Message.InputTokens,
			&i.Message.OutputTokens,
			&i.Message.ReasoningTokens,
			&i.Message.CacheCreationTokens,
			&i.Message.CacheReadTokens,
			&i.Message.TotalTokens,
			&i.Message.CostUsd,
			&i.Message.UsageProvider,
			&i.Message.UsageModel,
			&i.Message.CacheSupport,
			&i.Message.UsageEstimated,
			&i.RowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionOlderThanCreatedAt = `-- name: ListMessagesBySessionOlderThanCreatedAt :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
FROM messages
WHERE session_id = ?
  AND created_at < ?
ORDER BY created_at DESC, rowid DESC
LIMIT ?
`

type ListMessagesBySessionOlderThanCreatedAtParams struct {
	SessionID string `json:"session_id"`
	CreatedAt int64  `json:"created_at"`
	Limit     int64  `json:"limit"`
}

// First half of the keyset pagination pair used by
// read_delegation_transcript.go: returns messages strictly OLDER (by
// created_at second) than the cursor boundary, deterministically ordered.
// Combined in Go with ListMessagesBySessionAtCreatedAt (which handles the
// boundary second's exact-tie rows via the rowid tiebreaker) to reproduce the
// same (created_at, rowid) keyset semantics as a single
// `(created_at, rowid) < (?, ?)` comparison would, without needing rowid in a
// WHERE clause - see GetTranscriptWindowCursor's comment for why that's
// avoided. Because the boundary is a concrete value pinned by
// GetTranscriptWindowCursor at the start of the read (not "the Nth row from
// the current end"), inserting new messages at the head between calls can
// never shift which rows this query returns: the boundary itself doesn't move.
func (q *Queries) ListMessagesBySessionOlderThanCreatedAt(ctx context.Context, arg ListMessagesBySessionOlderThanCreatedAtParams) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionOlderThanCreatedAtStmt, listMessagesBySessionOlderThanCreatedAt, arg.SessionID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.UsageProvider,
			&i.UsageModel,
			&i.CacheSupport,
			&i.UsageEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionPaginated = `-- name: ListMessagesBySessionPaginated :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
FROM messages
WHERE session_id = ?
ORDER BY created_at DESC, rowid DESC
LIMIT ? OFFSET ?
`

type ListMessagesBySessionPaginatedParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

// rowid is the tie-breaker: created_at is stored in SECONDS, so a single agent
// turn produces dozens of rows with an identical created_at. Without a total
// order SQLite does not guarantee a stable order among those ties, which makes
// OFFSET pagination lose/duplicate rows when the query plan shifts between
// page fetches. rowid is SQLite's implicit monotonic insertion counter, so
// (created_at DESC, rowid DESC) is a deterministic newest-first total order.
//
// NOTE: plain OFFSET is still vulnerable to a DIFFERENT instability than the
// tie-breaker bug above: concurrent inserts at the head of the DESC order (new
// messages from a still-running delegation) shift what a given numeric offset
// points at between two separate calls of this query. This query remains here
// as the plain, unprotected primitive; message.Service.ListPaginatedSnapshot
// is the race-free caller-facing wrapper read_delegation_transcript.go
// actually uses, built from GetTranscriptWindowCursor (pins one consistent
// snapshot boundary) plus the keyset pair ListMessagesBySessionOlderThan-
// CreatedAt / ListMessagesBySessionAtCreatedAt (fetches the window strictly
// at-or-before that boundary, immune to head insertions by construction).
func (q *Queries) ListMessagesBySessionPaginated(ctx context.Context, arg ListMessagesBySessionPaginatedParams) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionPaginatedStmt, listMessagesBySessionPaginated, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.UsageProvider,
			&i.UsageModel,
			&i.CacheSupport,
			&i.UsageEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessagesBySession = `-- name: ListUserMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, pinned, hidden, reasoning_effort, auto_resumed, background_job_notice, input_tokens, output_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, total_tokens, cost_usd, usage_provider, usage_model, cache_support, usage_estimated
FROM messages
WHERE session_id = ? AND role = 'user'
ORDER BY created_at DESC, rowid DESC
`

// rowid is the tie-breaker: created_at is stored in SECONDS, so multiple user
// messages within the same second (e.g. rapid follow-ups) are not given a
// stable order by created_at alone. Same class of bug fixed for
// ListMessagesBySession/ListMessagesBySessionPaginated - rowid is SQLite's
// implicit monotonic insertion counter (messages.id is a non-monotonic UUID,
// unsuitable as a tiebreaker), so (created_at DESC, rowid DESC) is a
// deterministic newest-first total order.
func (q *Queries) ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listUserMessagesBySessionStmt, listUserMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Pinned,
			&i.Hidden,
			&i.ReasoningEffort,
			&i.AutoResumed,
			&i.BackgroundJobNotice,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
			&i.UsageProvider,
			&i.UsageModel,
			&i.CacheSupport,
			&i.UsageEstimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMessageUsageByDayInRange = `-- name: SumMessageUsageByDayInRange :many
SELECT
    CAST(strftime('%Y-%m-%d', created_at, 'unixepoch', 'localtime') AS TEXT) AS day,
    CAST(COUNT(*) AS INTEGER) AS recorded,
    CAST(COALESCE(SUM(usage_estimated), 0) AS INTEGER) AS estimated,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(total_tokens), 0) AS INTEGER) AS total_tokens,
    CAST(COALESCE(SUM(cost_usd), 0) AS REAL) AS cost_usd
FROM messages
WHERE total_tokens IS NOT NULL
  AND created_at >= ?
  AND created_at <= ?
GROUP BY day
ORDER BY day
`

type SumMessageUsageByDayInRangeParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
}

type SumMessageUsageByDayInRangeRow struct {
	Day                 string  `json:"day"`
	Recorded            int64   `json:"recorded"`
	Estimated           int64   `json:"estimated"`
	InputTokens         int64   `json:"input_tokens"`
	OutputTokens        int64   `json:"output_tokens"`
	ReasoningTokens     int64   `json:"reasoning_tokens"`
	CacheCreationTokens int64   `json:"cache_creation_tokens"`
	CacheReadTokens     int64   `json:"cache_read_tokens"`
	TotalTokens         int64   `json:"total_tokens"`
	CostUsd             float64 `json:"cost_usd"`
}

// Same window and semantics as SumMessageUsageByModelInRange, bucketed by
// local calendar day so it lines up with `sessions cost --by day`, which
// formats with time.Unix(...).Format("2006-01-02") in local time.
func (q *Queries) SumMessageUsageByDayInRange(ctx context.Context, arg SumMessageUsageByDayInRangeParams) ([]SumMessageUsageByDayInRangeRow, error) {
	rows, err := q.query(ctx, q.sumMessageUsageByDayInRangeStmt, sumMessageUsageByDayInRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumMessageUsageByDayInRangeRow{}
	for rows.Next() {
		var i SumMessageUsageByDayInRangeRow
		if err := rows.Scan(
			&i.Day,
			&i.Recorded,
			&i.Estimated,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMessageUsageByModelInRange = `-- name: SumMessageUsageByModelInRange :many
SELECT
    COALESCE(usage_provider, '') AS provider,
    COALESCE(usage_model, '') AS model,
    COALESCE(cache_support, '') AS cache_support,
    CAST(COUNT(*) AS INTEGER) AS recorded,
    CAST(COALESCE(SUM(usage_estimated), 0) AS INTEGER) AS estimated,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(total_tokens), 0) AS INTEGER) AS total_tokens,
    CAST(COALESCE(SUM(cost_usd), 0) AS REAL) AS cost_usd
FROM messages
WHERE total_tokens IS NOT NULL
  AND created_at >= ?
  AND created_at <= ?
GROUP BY usage_provider, usage_model, cache_support
`

type SumMessageUsageByModelInRangeParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
}

type SumMessageUsageByModelInRangeRow struct {
	Provider            string  `json:"provider"`
	Model               string  `json:"model"`
	CacheSupport        string  `json:"cache_support"`
	Recorded            int64   `json:"recorded"`
	Estimated           int64   `json:"estimated"`
	InputTokens         int64   `json:"input_tokens"`
	OutputTokens        int64   `json:"output_tokens"`
	ReasoningTokens     int64   `json:"reasoning_tokens"`
	CacheCreationTokens int64   `json:"cache_creation_tokens"`
	CacheReadTokens     int64   `json:"cache_read_tokens"`
	TotalTokens         int64   `json:"total_tokens"`
	CostUsd             float64 `json:"cost_usd"`
}

// Per-model token/cache/cost totals across ALL sessions in a time window.
//
// Grouped by the model that actually PRODUCED each message, not by the
// session's current model. `sessions cost` groups by sessions.smart_model_id,
// so a session that switched models attributes every token to whichever model
// it happened to end on; this does not.
//
// Child (sub-agent) sessions are deliberately INCLUDED and this does NOT
// double-count. TransferChildCostToParent moves a child's cost into the
// PARENT'S sessions.cost column and never touches message rows, so each
// message's cost_usd is counted exactly once here. (`sessions cost` must
// exclude child sessions for precisely the opposite reason.)
//
// Every SUM is wrapped in CAST or sqlc infers interface{} for an aggregate
// over a nullable column and the generated struct is unusable.
func (q *Queries) SumMessageUsageByModelInRange(ctx context.Context, arg SumMessageUsageByModelInRangeParams) ([]SumMessageUsageByModelInRangeRow, error) {
	rows, err := q.query(ctx, q.sumMessageUsageByModelInRangeStmt, sumMessageUsageByModelInRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumMessageUsageByModelInRangeRow{}
	for rows.Next() {
		var i SumMessageUsageByModelInRangeRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.CacheSupport,
			&i.Recorded,
			&i.Estimated,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMessageUsageBySession = `-- name: SumMessageUsageBySession :many
SELECT
    COALESCE(usage_provider, '') AS provider,
    COALESCE(usage_model, '') AS model,
    COALESCE(cache_support, '') AS cache_support,
    CAST(COUNT(*) AS INTEGER) AS recorded,
    CAST(COALESCE(SUM(usage_estimated), 0) AS INTEGER) AS estimated,
    CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens,
    CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens,
    CAST(COALESCE(SUM(reasoning_tokens), 0) AS INTEGER) AS reasoning_tokens,
    CAST(COALESCE(SUM(cache_creation_tokens), 0) AS INTEGER) AS cache_creation_tokens,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS cache_read_tokens,
    CAST(COALESCE(SUM(total_tokens), 0) AS INTEGER) AS total_tokens,
    CAST(COALESCE(SUM(cost_usd), 0) AS REAL) AS cost_usd
FROM messages
WHERE session_id = ? AND total_tokens IS NOT NULL
GROUP BY usage_provider, usage_model, cache_support
`

type SumMessageUsageBySessionRow struct {
	Provider            string  `json:"provider"`
	Model               string  `json:"model"`
	CacheSupport        string  `json:"cache_support"`
	Recorded            int64   `json:"recorded"`
	Estimated           int64   `json:"estimated"`
	InputTokens         int64   `json:"input_tokens"`
	OutputTokens        int64   `json:"output_tokens"`
	ReasoningTokens     int64   `json:"reasoning_tokens"`
	CacheCreationTokens int64   `json:"cache_creation_tokens"`
	CacheReadTokens     int64   `json:"cache_read_tokens"`
	TotalTokens         int64   `json:"total_tokens"`
	CostUsd             float64 `json:"cost_usd"`
}

// Cache/token/cost aggregate for one session, grouped by the model that
// actually produced each message (a session can switch models mid-run, and
// averaging their cache behaviour into one number describes neither).
//
// recorded/estimated are returned so a caller can state its coverage rather
// than implying a total was computed over everything: rows written before this
// feature existed have NULL usage and are excluded by the WHERE clause.
//
// Every SUM is wrapped in CAST: without it sqlc infers interface{} for an
// aggregate over a nullable column and the generated struct is unusable.
func (q *Queries) SumMessageUsageBySession(ctx context.Context, sessionID string) ([]SumMessageUsageBySessionRow, error) {
	rows, err := q.query(ctx, q.sumMessageUsageBySessionStmt, sumMessageUsageBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumMessageUsageBySessionRow{}
	for rows.Next() {
		var i SumMessageUsageBySessionRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.CacheSupport,
			&i.Recorded,
			&i.Estimated,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.TotalTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    finished_at = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts      string        `json:"parts"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.exec(ctx, q.updateMessageStmt, updateMessage, arg.Parts, arg.FinishedAt, arg.ID)
	return err
}

const updateMessageIfNotTerminal = `-- name: UpdateMessageIfNotTerminal :execrows
UPDATE messages
SET
    parts = ?,
    finished_at = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
  AND finished_at IS NULL
`

type UpdateMessageIfNotTerminalParams struct {
	Parts      string        `json:"parts"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

// P0-4 fix: Only update if the message does NOT already have a non-partial finish.
// This prevents a hung checkpoint from overwriting a terminal finish after unblocking.
// A checkpoint writes with Partial=true (finished_at NULL), so this condition rejects
// the update if finished_at is already non-NULL (real terminal finish).
// Returns number of rows affected (0 = skipped because already terminal, 1 = updated).
func (q *Queries) UpdateMessageIfNotTerminal(ctx context.Context, arg UpdateMessageIfNotTerminalParams) (int64, error) {
	result, err := q.exec(ctx, q.updateMessageIfNotTerminalStmt, updateMessageIfNotTerminal, arg.Parts, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMessagePinned = `-- name: UpdateMessagePinned :exec
UPDATE messages
SET
    pinned = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessagePinnedParams struct {
	Pinned int64  `json:"pinned"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateMessagePinned(ctx context.Context, arg UpdateMessagePinnedParams) error {
	_, err := q.exec(ctx, q.updateMessagePinnedStmt, updateMessagePinned, arg.Pinned, arg.ID)
	return err
}

const updateMessageUsage = `-- name: UpdateMessageUsage :exec
UPDATE messages
SET
    input_tokens = ?,
    output_tokens = ?,
    reasoning_tokens = ?,
    cache_creation_tokens = ?,
    cache_read_tokens = ?,
    total_tokens = ?,
    cost_usd = ?,
    usage_provider = ?,
    usage_model = ?,
    cache_support = ?,
    usage_estimated = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageUsageParams struct {
	InputTokens         sql.NullInt64   `json:"input_tokens"`
	OutputTokens        sql.NullInt64   `json:"output_tokens"`
	ReasoningTokens     sql.NullInt64   `json:"reasoning_tokens"`
	CacheCreationTokens sql.NullInt64   `json:"cache_creation_tokens"`
	CacheReadTokens     sql.NullInt64   `json:"cache_read_tokens"`
	TotalTokens         sql.NullInt64   `json:"total_tokens"`
	CostUsd             sql.NullFloat64 `json:"cost_usd"`
	UsageProvider       sql.NullString  `json:"usage_provider"`
	UsageModel          sql.NullString  `json:"usage_model"`
	CacheSupport        sql.NullString  `json:"cache_support"`
	UsageEstimated      sql.NullInt64   `json:"usage_estimated"`
	ID                  string          `json:"id"`
}

// Per-message token usage and prompt-cache accounting (task #469).
//
// Written by a separate statement rather than folded into UpdateMessage on
// purpose: the agent appends the Finish part BEFORE the step's usage is
// resolved (internal/agent/agent.go - AddFinish precedes fallbackStepUsage),
// so there is no single moment where both are in hand. Keeping usage separate
// avoids reordering that finish chain.
//
// All placeholders are bare `?` in binding order. Do NOT mix bare `?` with
// numbered/named args here: SQLite numbers a bare `?` from the highest
// explicit index already used, which silently shifts positional binding.
func (q *Queries) UpdateMessageUsage(ctx context.Context, arg UpdateMessageUsageParams) error {
	_, err := q.exec(ctx, q.updateMessageUsageStmt, updateMessageUsage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
		arg.TotalTokens,
		arg.CostUsd,
		arg.UsageProvider,
		arg.UsageModel,
		arg.CacheSupport,
		arg.UsageEstimated,
		arg.ID,
	)
	return err
}
