// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AsyncHost struct {
	ID        string `json:"id"`
	Pid       int64  `json:"pid"`
	Label     string `json:"label"`
	StartedAt int64  `json:"started_at"`
}

type AsyncJob struct {
	OwnerSessionID    string         `json:"owner_session_id"`
	ToolCallID        string         `json:"tool_call_id"`
	Kind              string         `json:"kind"`
	ToolName          string         `json:"tool_name"`
	TimeoutSeconds    int64          `json:"timeout_seconds"`
	InputHash         string         `json:"input_hash"`
	ChildSessionID    sql.NullString `json:"child_session_id"`
	OriginCli         int64          `json:"origin_cli"`
	State             string         `json:"state"`
	NoticeKind        string         `json:"notice_kind"`
	HostID            string         `json:"host_id"`
	Announced         int64          `json:"announced"`
	Delivery          string         `json:"delivery"`
	NoticeMessageID   sql.NullString `json:"notice_message_id"`
	Wake              int64          `json:"wake"`
	Reacted           int64          `json:"reacted"`
	WakeAttempts      int64          `json:"wake_attempts"`
	ReactedFailed     int64          `json:"reacted_failed"`
	DeadlineAt        sql.NullInt64  `json:"deadline_at"`
	TimeoutKind       sql.NullString `json:"timeout_kind"`
	ResultSummary     sql.NullString `json:"result_summary"`
	ResultIsError     sql.NullInt64  `json:"result_is_error"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
	ClaimID           string         `json:"claim_id"`
	AnnounceMessageID sql.NullString `json:"announce_message_id"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID                   string          `json:"id"`
	SessionID            string          `json:"session_id"`
	Role                 string          `json:"role"`
	Parts                string          `json:"parts"`
	Model                sql.NullString  `json:"model"`
	CreatedAt            int64           `json:"created_at"`
	UpdatedAt            int64           `json:"updated_at"`
	FinishedAt           sql.NullInt64   `json:"finished_at"`
	Provider             sql.NullString  `json:"provider"`
	IsSummaryMessage     int64           `json:"is_summary_message"`
	Pinned               int64           `json:"pinned"`
	Hidden               int64           `json:"hidden"`
	ReasoningEffort      sql.NullString  `json:"reasoning_effort"`
	AutoResumed          int64           `json:"auto_resumed"`
	BackgroundJobNotice  int64           `json:"background_job_notice"`
	InputTokens          sql.NullInt64   `json:"input_tokens"`
	OutputTokens         sql.NullInt64   `json:"output_tokens"`
	ReasoningTokens      sql.NullInt64   `json:"reasoning_tokens"`
	CacheCreationTokens  sql.NullInt64   `json:"cache_creation_tokens"`
	CacheReadTokens      sql.NullInt64   `json:"cache_read_tokens"`
	TotalTokens          sql.NullInt64   `json:"total_tokens"`
	CostUsd              sql.NullFloat64 `json:"cost_usd"`
	UsageProvider        sql.NullString  `json:"usage_provider"`
	UsageModel           sql.NullString  `json:"usage_model"`
	CacheSupport         sql.NullString  `json:"cache_support"`
	UsageEstimated       sql.NullInt64   `json:"usage_estimated"`
	CheckpointGeneration int64           `json:"checkpoint_generation"`
	Origin               string          `json:"origin"`
	NoticeKind           string          `json:"notice_kind"`
}

type OrphanCallOutbox struct {
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
	CallData    string         `json:"call_data"`
	Status      string         `json:"status"`
	Attempts    int64          `json:"attempts"`
	MaxAttempts int64          `json:"max_attempts"`
	LastError   sql.NullString `json:"last_error"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type PendingInject struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	MessageID string `json:"message_id"`
	Content   string `json:"content"`
	Interrupt int64  `json:"interrupt"`
	CreatedAt int64  `json:"created_at"`
}

type QueueTask struct {
	ID         string          `json:"id"`
	SessionID  sql.NullString  `json:"session_id"`
	Prompt     string          `json:"prompt"`
	Role       sql.NullString  `json:"role"`
	MaxCost    sql.NullFloat64 `json:"max_cost"`
	MaxTokens  sql.NullInt64   `json:"max_tokens"`
	TimeoutSec sql.NullInt64   `json:"timeout_sec"`
	Status     string          `json:"status"`
	Cost       sql.NullFloat64 `json:"cost"`
	Tokens     sql.NullInt64   `json:"tokens"`
	ExitReason sql.NullString  `json:"exit_reason"`
	CreatedAt  int64           `json:"created_at"`
	StartedAt  sql.NullInt64   `json:"started_at"`
	FinishedAt sql.NullInt64   `json:"finished_at"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID                           string         `json:"id"`
	ParentSessionID              sql.NullString `json:"parent_session_id"`
	Title                        string         `json:"title"`
	MessageCount                 int64          `json:"message_count"`
	PromptTokens                 int64          `json:"prompt_tokens"`
	CompletionTokens             int64          `json:"completion_tokens"`
	Cost                         float64        `json:"cost"`
	UpdatedAt                    int64          `json:"updated_at"`
	CreatedAt                    int64          `json:"created_at"`
	SummaryMessageID             sql.NullString `json:"summary_message_id"`
	Todos                        sql.NullString `json:"todos"`
	SmartModelProvider           sql.NullString `json:"smart_model_provider"`
	SmartModelID                 sql.NullString `json:"smart_model_id"`
	FastModelProvider            sql.NullString `json:"fast_model_provider"`
	FastModelID                  sql.NullString `json:"fast_model_id"`
	SystemPrompt                 string         `json:"system_prompt"`
	YoloEnabled                  int64          `json:"yolo_enabled"`
	SmartModelReasoningEffort    sql.NullString `json:"smart_model_reasoning_effort"`
	FastModelReasoningEffort     sql.NullString `json:"fast_model_reasoning_effort"`
	CancelRequested              int64          `json:"cancel_requested"`
	EndedReason                  string         `json:"ended_reason"`
	BudgetMaxCost                float64        `json:"budget_max_cost"`
	BudgetMaxTokens              int64          `json:"budget_max_tokens"`
	BudgetTimeoutSec             int64          `json:"budget_timeout_sec"`
	DeletedTodos                 string         `json:"deleted_todos"`
	ParentCostAccounted          float64        `json:"parent_cost_accounted"`
	WorkerModelProvider          sql.NullString `json:"worker_model_provider"`
	WorkerModelID                sql.NullString `json:"worker_model_id"`
	WorkerModelReasoningEffort   sql.NullString `json:"worker_model_reasoning_effort"`
	ReviewerModelProvider        sql.NullString `json:"reviewer_model_provider"`
	ReviewerModelID              sql.NullString `json:"reviewer_model_id"`
	ReviewerModelReasoningEffort sql.NullString `json:"reviewer_model_reasoning_effort"`
	Origin                       string         `json:"origin"`
	CostSelf                     float64        `json:"cost_self"`
	CostBase                     float64        `json:"cost_base"`
	CostParentID                 string         `json:"cost_parent_id"`
}

type SessionDriver struct {
	SessionID string `json:"session_id"`
	HostID    string `json:"host_id"`
	Pid       int64  `json:"pid"`
	ClaimedAt int64  `json:"claimed_at"`
}

type SessionNotice struct {
	ID              int64          `json:"id"`
	Owner           string         `json:"owner"`
	Kind            string         `json:"kind"`
	Text            string         `json:"text"`
	Wake            int64          `json:"wake"`
	Delivery        string         `json:"delivery"`
	NoticeMessageID sql.NullString `json:"notice_message_id"`
	Reacted         int64          `json:"reacted"`
	WakeAttempts    int64          `json:"wake_attempts"`
	ReactedFailed   int64          `json:"reacted_failed"`
	JobToolCallID   sql.NullString `json:"job_tool_call_id"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

type SessionPermission struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	ToolName  string `json:"tool_name"`
	Action    string `json:"action"`
	Path      string `json:"path"`
	CreatedAt int64  `json:"created_at"`
	Enabled   int64  `json:"enabled"`
}

type SessionRunQueue struct {
	ID              string         `json:"id"`
	SessionID       string         `json:"session_id"`
	CallData        string         `json:"call_data"`
	Status          string         `json:"status"`
	LeasedBy        sql.NullString `json:"leased_by"`
	LeasedAt        sql.NullInt64  `json:"leased_at"`
	LeaseExpiresAt  sql.NullInt64  `json:"lease_expires_at"`
	Attempts        int64          `json:"attempts"`
	LastError       sql.NullString `json:"last_error"`
	TerminalFailure int64          `json:"terminal_failure"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

type WakeSchedule struct {
	ID             string         `json:"id"`
	OwnerSessionID string         `json:"owner_session_id"`
	Kind           string         `json:"kind"`
	Message        string         `json:"message"`
	NextRunAt      int64          `json:"next_run_at"`
	EveryMs        int64          `json:"every_ms"`
	MaxRuns        sql.NullInt64  `json:"max_runs"`
	UntilAt        sql.NullInt64  `json:"until_at"`
	State          string         `json:"state"`
	Occurrence     int64          `json:"occurrence"`
	LeaseOwner     sql.NullString `json:"lease_owner"`
	LeaseExpiresAt sql.NullInt64  `json:"lease_expires_at"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}
