// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_injects.sql

package db

import (
	"context"
)

const createPendingInject = `-- name: CreatePendingInject :exec

INSERT INTO pending_injects (
    id,
    session_id,
    message_id,
    content,
    interrupt,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreatePendingInjectParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	MessageID string `json:"message_id"`
	Content   string `json:"content"`
	Interrupt int64  `json:"interrupt"`
	CreatedAt int64  `json:"created_at"`
}

// pending_injects is the cross-process inject queue for `rush sessions
// inject`. See migration 20260703000001 for the full semantics.
//
// NOTE: as of this fork the session-layer wrapper (session.go
// DrainPendingInjects / CreatePendingInject) talks to this table via raw
// database/sql, matching the existing cross-process signal pattern
// (RequestCancel / SetBudget). These sqlc-generated methods below ARE
// wired into db.go's Prepare/Close/WithTx (as of the sqlc regeneration
// that added call_tree_activity.sql), but nothing in the codebase calls
// them yet - session.go's raw-SQL path remains the actual implementation.
// Keep both in sync if pending_injects' schema changes.
func (q *Queries) CreatePendingInject(ctx context.Context, arg CreatePendingInjectParams) error {
	_, err := q.exec(ctx, q.createPendingInjectStmt, createPendingInject,
		arg.ID,
		arg.SessionID,
		arg.MessageID,
		arg.Content,
		arg.Interrupt,
		arg.CreatedAt,
	)
	return err
}

const deletePendingInject = `-- name: DeletePendingInject :exec
DELETE FROM pending_injects
WHERE id = ?
`

func (q *Queries) DeletePendingInject(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deletePendingInjectStmt, deletePendingInject, id)
	return err
}

const listPendingInjectsBySession = `-- name: ListPendingInjectsBySession :many
SELECT id, session_id, message_id, content, interrupt, created_at FROM pending_injects
WHERE session_id = ?
ORDER BY created_at ASC, rowid ASC
`

func (q *Queries) ListPendingInjectsBySession(ctx context.Context, sessionID string) ([]PendingInject, error) {
	rows, err := q.query(ctx, q.listPendingInjectsBySessionStmt, listPendingInjectsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingInject{}
	for rows.Next() {
		var i PendingInject
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.Content,
			&i.Interrupt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
