// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_queue.sql

package db

import (
	"context"
	"database/sql"
)

const ackRunQueueEntry = `-- name: AckRunQueueEntry :one
DELETE FROM session_run_queue
WHERE id = ? AND status = 'leased' AND leased_by = ?
RETURNING id
`

type AckRunQueueEntryParams struct {
	ID       string         `json:"id"`
	LeasedBy sql.NullString `json:"leased_by"`
}

// Mark a leased entry as successfully completed (terminal).
// Removes it from the queue (acked is terminal, no longer needed).
// Scoped to the current lease owner (found by the fifth @oh review pass over
// #337-349): without this, an executor that lost its lease to a
// CleanupExpiredLeases recovery (a rare residual now that executeEntry
// renews its lease for the duration of a real turn, but not impossible
// under a pathological scheduling stall) could Ack a row a DIFFERENT,
// currently-live executor now owns, deleting work out from under it.
func (q *Queries) AckRunQueueEntry(ctx context.Context, arg AckRunQueueEntryParams) (string, error) {
	row := q.queryRow(ctx, q.ackRunQueueEntryStmt, ackRunQueueEntry, arg.ID, arg.LeasedBy)
	var id string
	err := row.Scan(&id)
	return id, err
}

const cleanupExpiredLeases = `-- name: CleanupExpiredLeases :exec
UPDATE session_run_queue
SET status = 'pending',
    leased_by = NULL,
    leased_at = NULL,
    lease_expires_at = NULL,
    last_error = 'lease_expired',
    attempts = attempts + 1,
    updated_at = ?
WHERE status = 'leased' AND lease_expires_at < ?
`

type CleanupExpiredLeasesParams struct {
	UpdatedAt      int64         `json:"updated_at"`
	LeaseExpiresAt sql.NullInt64 `json:"lease_expires_at"`
}

// Reset stale leased entries back to pending (lease expiry recovery).
// Run periodically to recover from crashed pump instances.
// Increments attempts: a lease that expired without a matching Ack/Nack
// means whatever was executing it (a pump process, a goroutine) died or
// hung mid-execution without ever completing a normal outcome. Without
// counting this as an attempt, a poison entry whose execution always
// kills the process before it can Ack or Nack would accumulate attempts=0
// forever and never reach RunQueueMaxAttempts, looping indefinitely
// instead of eventually being dead-lettered.
func (q *Queries) CleanupExpiredLeases(ctx context.Context, arg CleanupExpiredLeasesParams) error {
	_, err := q.exec(ctx, q.cleanupExpiredLeasesStmt, cleanupExpiredLeases, arg.UpdatedAt, arg.LeaseExpiresAt)
	return err
}

const enqueueRunQueueEntry = `-- name: EnqueueRunQueueEntry :one
INSERT INTO session_run_queue (
    id,
    session_id,
    call_data,
    status,
    attempts,
    terminal_failure,
    created_at,
    updated_at
) VALUES (?, ?, ?, 'pending', 0, 0, ?, ?)
ON CONFLICT(id) DO NOTHING
RETURNING id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at
`

type EnqueueRunQueueEntryParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	CallData  string `json:"call_data"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

// ON CONFLICT DO NOTHING makes this idempotent on id (P2-1): a caller that
// retries with the same, stable idempotency key must not error just because
// its own earlier attempt already committed the row. Returns zero rows on
// conflict (sql.ErrNoRows to the :one caller) rather than the pre-existing
// row's contents; the caller (session.EnqueueRunQueueEntry) treats that
// specifically as "already enqueued", not as a failure.
func (q *Queries) EnqueueRunQueueEntry(ctx context.Context, arg EnqueueRunQueueEntryParams) (SessionRunQueue, error) {
	row := q.queryRow(ctx, q.enqueueRunQueueEntryStmt, enqueueRunQueueEntry,
		arg.ID,
		arg.SessionID,
		arg.CallData,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SessionRunQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.LeasedBy,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastError,
		&i.TerminalFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOldestPendingRunQueueEntryForSession = `-- name: GetOldestPendingRunQueueEntryForSession :one
SELECT id, session_id, call_data, status, leased_by, leased_at, lease_expires_at,
       attempts, last_error, terminal_failure, created_at, updated_at
FROM session_run_queue
WHERE session_id = ? AND status = 'pending'
ORDER BY created_at ASC, rowid ASC
LIMIT 1
`

// Get the oldest pending entry for a session (for transactional lease).
func (q *Queries) GetOldestPendingRunQueueEntryForSession(ctx context.Context, sessionID string) (SessionRunQueue, error) {
	row := q.queryRow(ctx, q.getOldestPendingRunQueueEntryForSessionStmt, getOldestPendingRunQueueEntryForSession, sessionID)
	var i SessionRunQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.LeasedBy,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastError,
		&i.TerminalFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunQueueEntry = `-- name: GetRunQueueEntry :one
SELECT id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at FROM session_run_queue
WHERE id = ?
`

// Get a single entry by ID.
func (q *Queries) GetRunQueueEntry(ctx context.Context, id string) (SessionRunQueue, error) {
	row := q.queryRow(ctx, q.getRunQueueEntryStmt, getRunQueueEntry, id)
	var i SessionRunQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.LeasedBy,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastError,
		&i.TerminalFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasOutstandingRunQueueEntryForSession = `-- name: HasOutstandingRunQueueEntryForSession :one
SELECT EXISTS(
    SELECT 1 FROM session_run_queue
    WHERE session_id = ? AND status IN ('pending', 'leased')
) AS has_outstanding
`

// Report whether ANY row for this session is still outstanding, in EITHER
// status ('pending' or 'leased') -- not just 'pending'. Used by
// DrainSessionNow's terminal check (task #610): a row leased by a
// DIFFERENT owner (another process, or another pump instance racing this
// one) is invisible to GetOldestPendingRunQueueEntryForSession, which only
// ever looks at status = 'pending'. That gap let a drain conclude the
// session's queue was empty while a 'leased' row for it still existed,
// durable, with an unknown outcome. This query closes that gap by checking
// both statuses explicitly rather than inferring queue state from a failed
// pending-only lease attempt.
func (q *Queries) HasOutstandingRunQueueEntryForSession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.hasOutstandingRunQueueEntryForSessionStmt, hasOutstandingRunQueueEntryForSession, sessionID)
	var has_outstanding int64
	err := row.Scan(&has_outstanding)
	return has_outstanding, err
}

const leaseRunQueueEntryByID = `-- name: LeaseRunQueueEntryByID :one
UPDATE session_run_queue
SET status = 'leased',
    leased_by = ?,
    leased_at = ?,
    lease_expires_at = ?,
    updated_at = ?
WHERE id = ? AND status = 'pending'
RETURNING id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at
`

type LeaseRunQueueEntryByIDParams struct {
	LeasedBy       sql.NullString `json:"leased_by"`
	LeasedAt       sql.NullInt64  `json:"leased_at"`
	LeaseExpiresAt sql.NullInt64  `json:"lease_expires_at"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
}

// Claim a specific entry by ID (call after GetOldestPendingRunQueueEntryForSession in a transaction).
// Does not increment attempts: leasing only claims the row for execution.
// NackRunQueueEntry and CleanupExpiredLeases are the only sites that count
// an attempt, exactly once per completed failed execution or per lease
// recovered from a crashed/hung executor. Counting here too, in addition to
// NackRunQueueEntry, double-counted every failure cycle, silently halving
// the effective value of RunQueueMaxAttempts.
func (q *Queries) LeaseRunQueueEntryByID(ctx context.Context, arg LeaseRunQueueEntryByIDParams) (SessionRunQueue, error) {
	row := q.queryRow(ctx, q.leaseRunQueueEntryByIDStmt, leaseRunQueueEntryByID,
		arg.LeasedBy,
		arg.LeasedAt,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i SessionRunQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.LeasedBy,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastError,
		&i.TerminalFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingRunQueueEntries = `-- name: ListPendingRunQueueEntries :many
SELECT id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at FROM session_run_queue
WHERE status = 'pending'
ORDER BY created_at ASC, rowid ASC
`

// Get all pending entries (for pump scanning across all sessions).
func (q *Queries) ListPendingRunQueueEntries(ctx context.Context) ([]SessionRunQueue, error) {
	rows, err := q.query(ctx, q.listPendingRunQueueEntriesStmt, listPendingRunQueueEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionRunQueue{}
	for rows.Next() {
		var i SessionRunQueue
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CallData,
			&i.Status,
			&i.LeasedBy,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.Attempts,
			&i.LastError,
			&i.TerminalFailure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleLeasedRunQueueEntries = `-- name: ListStaleLeasedRunQueueEntries :many
SELECT id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at FROM session_run_queue
WHERE status = 'leased' AND lease_expires_at < ?
ORDER BY lease_expires_at ASC
`

// Get all leased entries with expired leases (for pump lease recovery).
func (q *Queries) ListStaleLeasedRunQueueEntries(ctx context.Context, leaseExpiresAt sql.NullInt64) ([]SessionRunQueue, error) {
	rows, err := q.query(ctx, q.listStaleLeasedRunQueueEntriesStmt, listStaleLeasedRunQueueEntries, leaseExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionRunQueue{}
	for rows.Next() {
		var i SessionRunQueue
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CallData,
			&i.Status,
			&i.LeasedBy,
			&i.LeasedAt,
			&i.LeaseExpiresAt,
			&i.Attempts,
			&i.LastError,
			&i.TerminalFailure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nackRunQueueEntry = `-- name: NackRunQueueEntry :one
UPDATE session_run_queue
SET status = 'pending',
    leased_by = NULL,
    leased_at = NULL,
    lease_expires_at = NULL,
    last_error = ?,
    attempts = attempts + 1,
    updated_at = ?
WHERE id = ? AND status = 'leased' AND leased_by = ?
RETURNING id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at
`

type NackRunQueueEntryParams struct {
	LastError sql.NullString `json:"last_error"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
	LeasedBy  sql.NullString `json:"leased_by"`
}

// Release a leased entry back to pending state (non-terminal failure, retry later).
// Increments attempts but does NOT set terminal_failure.
// Scoped to the current lease owner, same as AckRunQueueEntry.
func (q *Queries) NackRunQueueEntry(ctx context.Context, arg NackRunQueueEntryParams) (SessionRunQueue, error) {
	row := q.queryRow(ctx, q.nackRunQueueEntryStmt, nackRunQueueEntry,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.LeasedBy,
	)
	var i SessionRunQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.LeasedBy,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastError,
		&i.TerminalFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nackRunQueueEntryNoAttemptPenalty = `-- name: NackRunQueueEntryNoAttemptPenalty :one
UPDATE session_run_queue
SET status = 'pending',
    leased_by = NULL,
    leased_at = NULL,
    lease_expires_at = NULL,
    last_error = ?,
    updated_at = ?
WHERE id = ? AND status = 'leased' AND leased_by = ?
RETURNING id, session_id, call_data, status, leased_by, leased_at, lease_expires_at, attempts, last_error, terminal_failure, created_at, updated_at
`

type NackRunQueueEntryNoAttemptPenaltyParams struct {
	LastError sql.NullString `json:"last_error"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
	LeasedBy  sql.NullString `json:"leased_by"`
}

// Release a leased entry back to pending state without counting it as an
// attempt. Used specifically for session.SessionLockBusyError: another live
// process legitimately holding the OS session lock is routine, expected
// contention, not a failure of the call itself, and must never count toward
// RunQueueMaxAttempts. Without this, the durable queue would delete
// accepted user work after nothing more than a few turns of ordinary lock
// contention. Also used for the ErrCallQueuedNotExecuted backoff path and
// for releasing a mismatched attempts-exhausted lease unharmed.
// Scoped to the current lease owner, same as AckRunQueueEntry.
func (q *Queries) NackRunQueueEntryNoAttemptPenalty(ctx context.Context, arg NackRunQueueEntryNoAttemptPenaltyParams) (SessionRunQueue, error) {
	row := q.queryRow(ctx, q.nackRunQueueEntryNoAttemptPenaltyStmt, nackRunQueueEntryNoAttemptPenalty,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.LeasedBy,
	)
	var i SessionRunQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CallData,
		&i.Status,
		&i.LeasedBy,
		&i.LeasedAt,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastError,
		&i.TerminalFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewRunQueueLease = `-- name: RenewRunQueueLease :execrows
UPDATE session_run_queue
SET lease_expires_at = ?
WHERE id = ? AND status = 'leased' AND leased_by = ?
`

type RenewRunQueueLeaseParams struct {
	LeaseExpiresAt sql.NullInt64  `json:"lease_expires_at"`
	ID             string         `json:"id"`
	LeasedBy       sql.NullString `json:"leased_by"`
}

// Extend a lease expiry while its owner is still genuinely working on it,
// or to back off a lease without counting a failed attempt. Scoped to
// status = leased AND leased_by = ? so a lease already reassigned to a
// different owner (this owner lost the race to a prior CleanupExpiredLeases
// recovery) is never silently extended out from under the new owner:
// execrows reports 0 rows in that case, which the caller must treat as
// meaning it is no longer this executor's lease to keep alive.
func (q *Queries) RenewRunQueueLease(ctx context.Context, arg RenewRunQueueLeaseParams) (int64, error) {
	result, err := q.exec(ctx, q.renewRunQueueLeaseStmt, renewRunQueueLease, arg.LeaseExpiresAt, arg.ID, arg.LeasedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const terminalFailRunQueueEntry = `-- name: TerminalFailRunQueueEntry :one
DELETE FROM session_run_queue
WHERE id = ? AND status = 'leased' AND leased_by = ?
RETURNING id
`

type TerminalFailRunQueueEntryParams struct {
	ID       string         `json:"id"`
	LeasedBy sql.NullString `json:"leased_by"`
}

// Mark a leased entry as terminal failure (no retry, even if attempts < max).
// Used for ErrCallAlreadyAttempted-type errors where retry would cause duplicates.
// Scoped to the current lease owner, same as AckRunQueueEntry.
func (q *Queries) TerminalFailRunQueueEntry(ctx context.Context, arg TerminalFailRunQueueEntryParams) (string, error) {
	row := q.queryRow(ctx, q.terminalFailRunQueueEntryStmt, terminalFailRunQueueEntry, arg.ID, arg.LeasedBy)
	var id string
	err := row.Scan(&id)
	return id, err
}
