// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_notices.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const clearSessionNoticesReactedFailedForOwner = `-- name: ClearSessionNoticesReactedFailedForOwner :execrows
UPDATE session_notices SET reacted_failed = 0, updated_at = ?
WHERE owner = ? AND reacted_failed = 1
`

type ClearSessionNoticesReactedFailedForOwnerParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Owner     string `json:"owner"`
}

// session_notices half of ClearReactedFailedForOwner (A1) -- see that
// query's doc for the full rationale.
func (q *Queries) ClearSessionNoticesReactedFailedForOwner(ctx context.Context, arg ClearSessionNoticesReactedFailedForOwnerParams) (int64, error) {
	result, err := q.exec(ctx, q.clearSessionNoticesReactedFailedForOwnerStmt, clearSessionNoticesReactedFailedForOwner, arg.UpdatedAt, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countSessionNoticesOlderThan = `-- name: CountSessionNoticesOlderThan :one
SELECT COUNT(*) FROM session_notices WHERE delivery IN ('done', 'void') AND updated_at < ?
  AND NOT (delivery = 'done' AND wake = 1 AND reacted = 0)
`

func (q *Queries) CountSessionNoticesOlderThan(ctx context.Context, updatedAt int64) (int64, error) {
	row := q.queryRow(ctx, q.countSessionNoticesOlderThanStmt, countSessionNoticesOlderThan, updatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSessionNotice = `-- name: GetSessionNotice :one
SELECT id, owner, kind, text, wake, delivery, notice_message_id, reacted, wake_attempts, reacted_failed, job_tool_call_id, created_at, updated_at FROM session_notices WHERE id = ?
`

func (q *Queries) GetSessionNotice(ctx context.Context, id int64) (SessionNotice, error) {
	row := q.queryRow(ctx, q.getSessionNoticeStmt, getSessionNotice, id)
	var i SessionNotice
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Kind,
		&i.Text,
		&i.Wake,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.JobToolCallID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSessionNoticeWakeAttemptsForSnapshotRow = `-- name: IncrementSessionNoticeWakeAttemptsForSnapshotRow :execrows
UPDATE session_notices SET wake_attempts = wake_attempts + 1, updated_at = ?1
WHERE id = ?2 AND delivery = 'done' AND COALESCE(notice_message_id, '') = CAST(?3 AS TEXT)
  AND wake = 1 AND reacted = 0
`

type IncrementSessionNoticeWakeAttemptsForSnapshotRowParams struct {
	UpdatedAt       int64  `json:"updated_at"`
	ID              int64  `json:"id"`
	NoticeMessageID string `json:"notice_message_id"`
}

// Notices half of IncrementAsyncJobWakeAttemptsForSnapshotRow (doc sec.3.4,
// R2A-5): keyed by id (session_notices' own PK) because the settle-by-failure
// scope is the exact set captured at the start of the failed turn, and still
// the row the snapshot saw: delivery='done' and the snapshot's
// notice_message_id (a Rerun re-pend/re-pull changes it), wake=1, reacted=0.
func (q *Queries) IncrementSessionNoticeWakeAttemptsForSnapshotRow(ctx context.Context, arg IncrementSessionNoticeWakeAttemptsForSnapshotRowParams) (int64, error) {
	result, err := q.exec(ctx, q.incrementSessionNoticeWakeAttemptsForSnapshotRowStmt, incrementSessionNoticeWakeAttemptsForSnapshotRow, arg.UpdatedAt, arg.ID, arg.NoticeMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSessionNotice = `-- name: InsertSessionNotice :one
INSERT INTO session_notices (
    owner, kind, text, wake, delivery, job_tool_call_id, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, 'pending', ?, ?, ?
)
RETURNING id, owner, kind, text, wake, delivery, notice_message_id, reacted, wake_attempts, reacted_failed, job_tool_call_id, created_at, updated_at
`

type InsertSessionNoticeParams struct {
	Owner         string         `json:"owner"`
	Kind          string         `json:"kind"`
	Text          string         `json:"text"`
	Wake          int64          `json:"wake"`
	JobToolCallID sql.NullString `json:"job_tool_call_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

// session_notices carries notices with no async_jobs row (supervision,
// wake_failed marker, background SDK shell completion, wake_only timeout --
// doc sec.2/3.2). Created with delivery='pending' so it is a drain
// candidate immediately.
func (q *Queries) InsertSessionNotice(ctx context.Context, arg InsertSessionNoticeParams) (SessionNotice, error) {
	row := q.queryRow(ctx, q.insertSessionNoticeStmt, insertSessionNotice,
		arg.Owner,
		arg.Kind,
		arg.Text,
		arg.Wake,
		arg.JobToolCallID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SessionNotice
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Kind,
		&i.Text,
		&i.Wake,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.JobToolCallID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingSessionNoticesForOwner = `-- name: ListPendingSessionNoticesForOwner :many
SELECT id, owner, kind, text, wake, delivery, notice_message_id, reacted, wake_attempts, reacted_failed, job_tool_call_id, created_at, updated_at FROM session_notices WHERE owner = ? AND delivery = 'pending' ORDER BY id ASC
`

// Drain candidates (doc sec.3.3), oldest first so history order matches
// occurrence order.
func (q *Queries) ListPendingSessionNoticesForOwner(ctx context.Context, owner string) ([]SessionNotice, error) {
	rows, err := q.query(ctx, q.listPendingSessionNoticesForOwnerStmt, listPendingSessionNoticesForOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionNotice{}
	for rows.Next() {
		var i SessionNotice
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Kind,
			&i.Text,
			&i.Wake,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.JobToolCallID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactedFailedSessionNoticesForOwner = `-- name: ListReactedFailedSessionNoticesForOwner :many
SELECT id, owner, kind, text, wake, delivery, notice_message_id, reacted, wake_attempts, reacted_failed, job_tool_call_id, created_at, updated_at FROM session_notices WHERE owner = ? AND reacted_failed = 1 ORDER BY id ASC
`

// Notices half of ListReactedFailedAsyncJobsForOwner: the parent-
// notification reader for settle-by-failure closures on this table.
func (q *Queries) ListReactedFailedSessionNoticesForOwner(ctx context.Context, owner string) ([]SessionNotice, error) {
	rows, err := q.query(ctx, q.listReactedFailedSessionNoticesForOwnerStmt, listReactedFailedSessionNoticesForOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionNotice{}
	for rows.Next() {
		var i SessionNotice
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Kind,
			&i.Text,
			&i.Wake,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.JobToolCallID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionNoticesForOwner = `-- name: ListSessionNoticesForOwner :many
SELECT id, owner, kind, text, wake, delivery, notice_message_id, reacted, wake_attempts, reacted_failed, job_tool_call_id, created_at, updated_at FROM session_notices WHERE owner = ? ORDER BY id ASC
`

// Reader for `sessions jobs`/`sessions why`.
func (q *Queries) ListSessionNoticesForOwner(ctx context.Context, owner string) ([]SessionNotice, error) {
	rows, err := q.query(ctx, q.listSessionNoticesForOwnerStmt, listSessionNoticesForOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionNotice{}
	for rows.Next() {
		var i SessionNotice
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Kind,
			&i.Text,
			&i.Wake,
			&i.Delivery,
			&i.NoticeMessageID,
			&i.Reacted,
			&i.WakeAttempts,
			&i.ReactedFailed,
			&i.JobToolCallID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionNoticesReactedForOwner = `-- name: MarkSessionNoticesReactedForOwner :execrows
UPDATE session_notices SET reacted = 1, updated_at = ?
WHERE owner = ? AND wake = 1 AND reacted = 0 AND delivery = 'done'
`

type MarkSessionNoticesReactedForOwnerParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Owner     string `json:"owner"`
}

// Same reaction rule as MarkAsyncJobsReactedForOwner, for the notices table.
func (q *Queries) MarkSessionNoticesReactedForOwner(ctx context.Context, arg MarkSessionNoticesReactedForOwnerParams) (int64, error) {
	result, err := q.exec(ctx, q.markSessionNoticesReactedForOwnerStmt, markSessionNoticesReactedForOwner, arg.UpdatedAt, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pullPendingSessionNotice = `-- name: PullPendingSessionNotice :one
UPDATE session_notices
SET delivery = 'done', updated_at = ?
WHERE id = ? AND delivery = 'pending'
RETURNING id, owner, kind, text, wake, delivery, notice_message_id, reacted, wake_attempts, reacted_failed, job_tool_call_id, created_at, updated_at
`

type PullPendingSessionNoticeParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

// The pull UPDATE...RETURNING (doc sec.3.3), same shape as
// PullPendingAsyncJobNotice: one transaction per notice, caller INSERTs the
// history message and stores notice_message_id in the same tx. 0 rows
// affected means another leader already won this row.
func (q *Queries) PullPendingSessionNotice(ctx context.Context, arg PullPendingSessionNoticeParams) (SessionNotice, error) {
	row := q.queryRow(ctx, q.pullPendingSessionNoticeStmt, pullPendingSessionNotice, arg.UpdatedAt, arg.ID)
	var i SessionNotice
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Kind,
		&i.Text,
		&i.Wake,
		&i.Delivery,
		&i.NoticeMessageID,
		&i.Reacted,
		&i.WakeAttempts,
		&i.ReactedFailed,
		&i.JobToolCallID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const purgeSessionNoticesOlderThan = `-- name: PurgeSessionNoticesOlderThan :execrows
DELETE FROM session_notices WHERE delivery IN ('done', 'void') AND updated_at < ?
  AND NOT (delivery = 'done' AND wake = 1 AND reacted = 0)
`

// Same retention pass as PurgeAsyncJobsOlderThan (doc sec.3.7), including
// the A5 "never purge unreacted debt" guard, scoped to delivery='done'
// exactly like the async_jobs twin -- see that query's doc.
func (q *Queries) PurgeSessionNoticesOlderThan(ctx context.Context, updatedAt int64) (int64, error) {
	result, err := q.exec(ctx, q.purgeSessionNoticesOlderThanStmt, purgeSessionNoticesOlderThan, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rependSessionNoticesByMessageIDs = `-- name: RependSessionNoticesByMessageIDs :execrows
UPDATE session_notices SET delivery = 'pending', reacted = 0, reacted_failed = 0, wake_attempts = 0, updated_at = ?
WHERE owner = ? AND delivery = 'done' AND kind <> 'wake_failed' AND notice_message_id IN (/*SLICE:message_ids*/?)
`

type RependSessionNoticesByMessageIDsParams struct {
	UpdatedAt  int64            `json:"updated_at"`
	Owner      string           `json:"owner"`
	MessageIds []sql.NullString `json:"message_ids"`
}

// Rerun undo-truncation, session_notices' counterpart to
// RependAsyncJobsByNoticeMessageIDs (doc sec.3.8's "same for session_notices
// rows whose messages were deleted"): a notice already delivered whose
// message landed in the deleted tail is re-queued for the new branch. The
// `delivery = 'done'` guard and the wake_attempts/reacted_failed reset
// mirror RependAsyncJobsByNoticeMessageIDs's own A4/A1 fixes -- see that
// query's doc.
// wake_failed markers are excluded: they describe an outcome of the deleted
// branch, so they are voided instead (VoidWakeFailedNoticesByMessageIDs).
func (q *Queries) RependSessionNoticesByMessageIDs(ctx context.Context, arg RependSessionNoticesByMessageIDsParams) (int64, error) {
	query := rependSessionNoticesByMessageIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.Owner)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const repointSessionNoticesJobToolCallID = `-- name: RepointSessionNoticesJobToolCallID :execrows
UPDATE session_notices SET job_tool_call_id = ?1
WHERE owner = ?2 AND job_tool_call_id = ?3
`

type RepointSessionNoticesJobToolCallIDParams struct {
	NewJobToolCallID sql.NullString `json:"new_job_tool_call_id"`
	Owner            string         `json:"owner"`
	OldJobToolCallID sql.NullString `json:"old_job_tool_call_id"`
}

// R2A-4: session_notices.job_tool_call_id names its async_jobs row by
// tool_call_id text (the wake_only pull-time void reads that row). When the
// archive rename above moves the row, its notices follow it: otherwise the
// text would resolve to the NEW row a later claim put under the reused id
// and a check-in about the old job would be delivered as if about the new
// one. Runs in the archive's own transaction, before the fresh claim
// inserts, so every notice matching the old text belongs to the old row.
func (q *Queries) RepointSessionNoticesJobToolCallID(ctx context.Context, arg RepointSessionNoticesJobToolCallIDParams) (int64, error) {
	result, err := q.exec(ctx, q.repointSessionNoticesJobToolCallIDStmt, repointSessionNoticesJobToolCallID, arg.NewJobToolCallID, arg.Owner, arg.OldJobToolCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionNoticeMessageID = `-- name: SetSessionNoticeMessageID :execrows
UPDATE session_notices SET notice_message_id = ?, updated_at = ?
WHERE id = ?
`

type SetSessionNoticeMessageIDParams struct {
	NoticeMessageID sql.NullString `json:"notice_message_id"`
	UpdatedAt       int64          `json:"updated_at"`
	ID              int64          `json:"id"`
}

func (q *Queries) SetSessionNoticeMessageID(ctx context.Context, arg SetSessionNoticeMessageIDParams) (int64, error) {
	result, err := q.exec(ctx, q.setSessionNoticeMessageIDStmt, setSessionNoticeMessageID, arg.NoticeMessageID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionNoticesWakeZeroPendingForOwners = `-- name: SetSessionNoticesWakeZeroPendingForOwners :execrows
UPDATE session_notices SET wake = 0, updated_at = ?
WHERE owner IN (/*SLICE:owner_ids*/?) AND delivery IN ('pending', 'done') AND wake = 1
`

type SetSessionNoticesWakeZeroPendingForOwnersParams struct {
	UpdatedAt int64    `json:"updated_at"`
	OwnerIds  []string `json:"owner_ids"`
}

// Stop transitivity (DUR-9, doc sec.3.8), notices half of
// SetAsyncJobsWakeZeroPendingForOwners.
func (q *Queries) SetSessionNoticesWakeZeroPendingForOwners(ctx context.Context, arg SetSessionNoticesWakeZeroPendingForOwnersParams) (int64, error) {
	query := setSessionNoticesWakeZeroPendingForOwners
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	if len(arg.OwnerIds) > 0 {
		for _, v := range arg.OwnerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:owner_ids*/?", strings.Repeat(",?", len(arg.OwnerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:owner_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settleSessionNoticeReactedFailedForSnapshotRow = `-- name: SettleSessionNoticeReactedFailedForSnapshotRow :execrows
UPDATE session_notices SET reacted = 1, reacted_failed = 1, updated_at = ?1
WHERE id = ?2 AND delivery = 'done' AND COALESCE(notice_message_id, '') = CAST(?3 AS TEXT)
  AND wake = 1 AND reacted = 0
`

type SettleSessionNoticeReactedFailedForSnapshotRowParams struct {
	UpdatedAt       int64  `json:"updated_at"`
	ID              int64  `json:"id"`
	NoticeMessageID string `json:"notice_message_id"`
}

// Notices half of SettleAsyncJobReactedFailedForSnapshotRow (doc sec.3.4,
// R2A-5): closes debt on ONE snapshot row after K=3 failed passes, under the
// same still-the-row-the-snapshot-saw guard. reacted_failed distinguishes this
// from MarkSessionNoticesReactedForOwner's ordinary, real-step reaction.
func (q *Queries) SettleSessionNoticeReactedFailedForSnapshotRow(ctx context.Context, arg SettleSessionNoticeReactedFailedForSnapshotRowParams) (int64, error) {
	result, err := q.exec(ctx, q.settleSessionNoticeReactedFailedForSnapshotRowStmt, settleSessionNoticeReactedFailedForSnapshotRow, arg.UpdatedAt, arg.ID, arg.NoticeMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const voidPendingSessionNotice = `-- name: VoidPendingSessionNotice :execrows
UPDATE session_notices SET delivery = 'void', updated_at = ?
WHERE id = ? AND delivery = 'done'
`

type VoidPendingSessionNoticeParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

// A pulled notice whose "task still running" condition failed (doc sec.3.4:
// supervision notice is debt only while the scope still has a running row;
// wake_only timeout notice voids if the task is no longer running) becomes
// void instead of done. Called from WITHIN the same transaction as
// PullPendingSessionNotice's own pending->done CAS (session package's
// pullOneSessionNotice), which has ALREADY won the race for this row and
// moved it to delivery='done' inside this uncommitted transaction -- so the
// guard here is delivery='done', not 'pending' (a 'pending'-scoped WHERE
// would never match here and silently fail to downgrade 'done' to 'void',
// leaving a suppressed notice mis-recorded as delivered).
func (q *Queries) VoidPendingSessionNotice(ctx context.Context, arg VoidPendingSessionNoticeParams) (int64, error) {
	result, err := q.exec(ctx, q.voidPendingSessionNoticeStmt, voidPendingSessionNotice, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const voidUndeliveredSessionNoticesForOwner = `-- name: VoidUndeliveredSessionNoticesForOwner :execrows
UPDATE session_notices SET delivery = 'void', reacted_failed = 0, updated_at = ?
WHERE owner = ? AND delivery IN ('pending', 'done')
`

type VoidUndeliveredSessionNoticesForOwnerParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Owner     string `json:"owner"`
}

// session_notices half of VoidUndeliveredAsyncJobsForOwner (`sessions reset`,
// R8A-3): every pending or delivered notice of the owner becomes void.
func (q *Queries) VoidUndeliveredSessionNoticesForOwner(ctx context.Context, arg VoidUndeliveredSessionNoticesForOwnerParams) (int64, error) {
	result, err := q.exec(ctx, q.voidUndeliveredSessionNoticesForOwnerStmt, voidUndeliveredSessionNoticesForOwner, arg.UpdatedAt, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const voidWakeFailedNoticesByMessageIDs = `-- name: VoidWakeFailedNoticesByMessageIDs :execrows
UPDATE session_notices SET delivery = 'void', updated_at = ?
WHERE owner = ? AND kind = 'wake_failed' AND delivery = 'done' AND notice_message_id IN (/*SLICE:message_ids*/?)
`

type VoidWakeFailedNoticesByMessageIDsParams struct {
	UpdatedAt  int64            `json:"updated_at"`
	Owner      string           `json:"owner"`
	MessageIds []sql.NullString `json:"message_ids"`
}

// Rerun truncation: a delivered wake_failed marker whose message is in the
// deleted tail is dropped, not re-pended -- it reports that the deleted
// branch's wake-up failed, which says nothing about the new branch.
func (q *Queries) VoidWakeFailedNoticesByMessageIDs(ctx context.Context, arg VoidWakeFailedNoticesByMessageIDsParams) (int64, error) {
	query := voidWakeFailedNoticesByMessageIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.Owner)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	result, err := q.exec(ctx, nil, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
