// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_drivers.sql

package db

import (
	"context"
)

const deleteSessionDriver = `-- name: DeleteSessionDriver :execrows
DELETE FROM session_drivers WHERE session_id = ? AND host_id = ?
`

type DeleteSessionDriverParams struct {
	SessionID string `json:"session_id"`
	HostID    string `json:"host_id"`
}

// A driver releases only its OWN claim (scoped to its host id).
func (q *Queries) DeleteSessionDriver(ctx context.Context, arg DeleteSessionDriverParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionDriverStmt, deleteSessionDriver, arg.SessionID, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionDriversForHost = `-- name: DeleteSessionDriversForHost :execrows
DELETE FROM session_drivers WHERE host_id = ?
`

// Host exit (AsyncJobStore.Close) or dead-host purge: every marker naming
// the host goes with it.
func (q *Queries) DeleteSessionDriversForHost(ctx context.Context, hostID string) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionDriversForHostStmt, deleteSessionDriversForHost, hostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionDriver = `-- name: GetSessionDriver :one
SELECT session_id, host_id, pid, claimed_at FROM session_drivers WHERE session_id = ?
`

// The durable external-driver marker for a session (migration
// 20260929000004): which host's `rush run` loop drives it.
func (q *Queries) GetSessionDriver(ctx context.Context, sessionID string) (SessionDriver, error) {
	row := q.queryRow(ctx, q.getSessionDriverStmt, getSessionDriver, sessionID)
	var i SessionDriver
	err := row.Scan(
		&i.SessionID,
		&i.HostID,
		&i.Pid,
		&i.ClaimedAt,
	)
	return i, err
}

const insertSessionDriver = `-- name: InsertSessionDriver :execrows
INSERT INTO session_drivers (session_id, host_id, pid, claimed_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (session_id) DO NOTHING
`

type InsertSessionDriverParams struct {
	SessionID string `json:"session_id"`
	HostID    string `json:"host_id"`
	Pid       int64  `json:"pid"`
	ClaimedAt int64  `json:"claimed_at"`
}

// First claim of a session's driver marker. DO NOTHING on conflict: the
// caller reads rows-affected and, on 0, re-observes who holds the row.
func (q *Queries) InsertSessionDriver(ctx context.Context, arg InsertSessionDriverParams) (int64, error) {
	result, err := q.exec(ctx, q.insertSessionDriverStmt, insertSessionDriver,
		arg.SessionID,
		arg.HostID,
		arg.Pid,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listSessionDriverHostIDs = `-- name: ListSessionDriverHostIDs :many
SELECT DISTINCT host_id FROM session_drivers
`

// Candidate set for the dead-driver purge; liveness itself is decided by the
// host lock module, not by this query.
func (q *Queries) ListSessionDriverHostIDs(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listSessionDriverHostIDsStmt, listSessionDriverHostIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var host_id string
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeOverSessionDriver = `-- name: TakeOverSessionDriver :execrows
UPDATE session_drivers SET host_id = ?1, pid = ?2, claimed_at = ?3
WHERE session_id = ?4 AND host_id = ?5
`

type TakeOverSessionDriverParams struct {
	HostID         string `json:"host_id"`
	Pid            int64  `json:"pid"`
	ClaimedAt      int64  `json:"claimed_at"`
	SessionID      string `json:"session_id"`
	ExpectedHostID string `json:"expected_host_id"`
}

// CAS takeover of a marker whose host the caller proved dead: succeeds only
// while the row still names exactly that dead host, so of N concurrent
// takers exactly one wins (rows-affected 1).
func (q *Queries) TakeOverSessionDriver(ctx context.Context, arg TakeOverSessionDriverParams) (int64, error) {
	result, err := q.exec(ctx, q.takeOverSessionDriverStmt, takeOverSessionDriver,
		arg.HostID,
		arg.Pid,
		arg.ClaimedAt,
		arg.SessionID,
		arg.ExpectedHostID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
