// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wake_schedules.sql

package db

import (
	"context"
	"database/sql"
)

const advanceLoopWakeOccurrence = `-- name: AdvanceLoopWakeOccurrence :execrows
UPDATE wake_schedules
SET occurrence = occurrence + 1, next_run_at = ?, lease_owner = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND lease_owner = ? AND state = 'active'
`

type AdvanceLoopWakeOccurrenceParams struct {
	NextRunAt  int64          `json:"next_run_at"`
	UpdatedAt  int64          `json:"updated_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

// loop: occurrence advances and next_run_at moves to the FIRST schedule
// boundary strictly after the fired one that is >= the fire time (computed
// by the caller from the SCHEDULED time, never from the fire time -- SCHED-3).
func (q *Queries) AdvanceLoopWakeOccurrence(ctx context.Context, arg AdvanceLoopWakeOccurrenceParams) (int64, error) {
	result, err := q.exec(ctx, q.advanceLoopWakeOccurrenceStmt, advanceLoopWakeOccurrence,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelAllWakeSchedulesForOwner = `-- name: CancelAllWakeSchedulesForOwner :execrows
UPDATE wake_schedules
SET state = 'cancelled', lease_owner = NULL, lease_expires_at = NULL, updated_at = ?
WHERE owner_session_id = ? AND state = 'active'
`

type CancelAllWakeSchedulesForOwnerParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	OwnerSessionID string `json:"owner_session_id"`
}

// `sessions reset` (R8A-3 sibling): no active schedule may survive a wiped
// history. Done/cancelled rows are history and stay.
func (q *Queries) CancelAllWakeSchedulesForOwner(ctx context.Context, arg CancelAllWakeSchedulesForOwnerParams) (int64, error) {
	result, err := q.exec(ctx, q.cancelAllWakeSchedulesForOwnerStmt, cancelAllWakeSchedulesForOwner, arg.UpdatedAt, arg.OwnerSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelWakeSchedule = `-- name: CancelWakeSchedule :execrows
UPDATE wake_schedules
SET state = 'cancelled', lease_owner = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND owner_session_id = ? AND state = 'active'
`

type CancelWakeScheduleParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	ID             string `json:"id"`
	OwnerSessionID string `json:"owner_session_id"`
}

// Owner-checked, idempotent CAS: only an active row moves to cancelled. A
// done/cancelled row is a no-op (SCHED-5); a foreign owner never matches.
func (q *Queries) CancelWakeSchedule(ctx context.Context, arg CancelWakeScheduleParams) (int64, error) {
	result, err := q.exec(ctx, q.cancelWakeScheduleStmt, cancelWakeSchedule, arg.UpdatedAt, arg.ID, arg.OwnerSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimWakeScheduleLease = `-- name: ClaimWakeScheduleLease :execrows
UPDATE wake_schedules
SET lease_owner = ?, lease_expires_at = ?, updated_at = ?
WHERE id = ? AND state = 'active'
  AND (lease_owner IS NULL OR lease_expires_at <= ?)
`

type ClaimWakeScheduleLeaseParams struct {
	LeaseOwner       sql.NullString `json:"lease_owner"`
	LeaseExpiresAt   sql.NullInt64  `json:"lease_expires_at"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
	LeaseExpiresAt_2 sql.NullInt64  `json:"lease_expires_at_2"`
}

// Per-row CAS half of the atomic claim: 0 rows means another leader won
// this row between the read and the write; the caller skips it.
func (q *Queries) ClaimWakeScheduleLease(ctx context.Context, arg ClaimWakeScheduleLeaseParams) (int64, error) {
	result, err := q.exec(ctx, q.claimWakeScheduleLeaseStmt, claimWakeScheduleLease,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.LeaseExpiresAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeOnceWakeSchedule = `-- name: CompleteOnceWakeSchedule :execrows
UPDATE wake_schedules
SET state = 'done', lease_owner = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND lease_owner = ? AND state = 'active'
`

type CompleteOnceWakeScheduleParams struct {
	UpdatedAt  int64          `json:"updated_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

// once: the occurrence fired -> done. Keyed by the lease so a stale fire
// (lease lost or recovered) is a no-op; the row can never fire twice
// (SCHED-1).
func (q *Queries) CompleteOnceWakeSchedule(ctx context.Context, arg CompleteOnceWakeScheduleParams) (int64, error) {
	result, err := q.exec(ctx, q.completeOnceWakeScheduleStmt, completeOnceWakeSchedule, arg.UpdatedAt, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveWakeSchedulesForOwner = `-- name: CountActiveWakeSchedulesForOwner :one
SELECT COUNT(*) FROM wake_schedules WHERE owner_session_id = ? AND state = 'active'
`

func (q *Queries) CountActiveWakeSchedulesForOwner(ctx context.Context, ownerSessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countActiveWakeSchedulesForOwnerStmt, countActiveWakeSchedulesForOwner, ownerSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishLoopWakeSchedule = `-- name: FinishLoopWakeSchedule :execrows
UPDATE wake_schedules
SET state = 'done', lease_owner = NULL, lease_expires_at = NULL, updated_at = ?
WHERE id = ? AND lease_owner = ? AND state = 'active'
`

type FinishLoopWakeScheduleParams struct {
	UpdatedAt  int64          `json:"updated_at"`
	ID         string         `json:"id"`
	LeaseOwner sql.NullString `json:"lease_owner"`
}

// loop: max_runs reached or until_at crossed -> done instead of advancing.
// Same lease-keyed CAS as CompleteOnceWakeSchedule.
func (q *Queries) FinishLoopWakeSchedule(ctx context.Context, arg FinishLoopWakeScheduleParams) (int64, error) {
	result, err := q.exec(ctx, q.finishLoopWakeScheduleStmt, finishLoopWakeSchedule, arg.UpdatedAt, arg.ID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWakeSchedule = `-- name: GetWakeSchedule :one
SELECT id, owner_session_id, kind, message, next_run_at, every_ms, max_runs, until_at, state, occurrence, lease_owner, lease_expires_at, created_at, updated_at FROM wake_schedules WHERE id = ?
`

func (q *Queries) GetWakeSchedule(ctx context.Context, id string) (WakeSchedule, error) {
	row := q.queryRow(ctx, q.getWakeScheduleStmt, getWakeSchedule, id)
	var i WakeSchedule
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.Kind,
		&i.Message,
		&i.NextRunAt,
		&i.EveryMs,
		&i.MaxRuns,
		&i.UntilAt,
		&i.State,
		&i.Occurrence,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWakeSchedule = `-- name: InsertWakeSchedule :one

INSERT INTO wake_schedules (
    id, owner_session_id, kind, message, next_run_at,
    every_ms, max_runs, until_at, state, occurrence, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, 'active', 0, ?, ?
)
RETURNING id, owner_session_id, kind, message, next_run_at, every_ms, max_runs, until_at, state, occurrence, lease_owner, lease_expires_at, created_at, updated_at
`

type InsertWakeScheduleParams struct {
	ID             string        `json:"id"`
	OwnerSessionID string        `json:"owner_session_id"`
	Kind           string        `json:"kind"`
	Message        string        `json:"message"`
	NextRunAt      int64         `json:"next_run_at"`
	EveryMs        int64         `json:"every_ms"`
	MaxRuns        sql.NullInt64 `json:"max_runs"`
	UntilAt        sql.NullInt64 `json:"until_at"`
	CreatedAt      int64         `json:"created_at"`
	UpdatedAt      int64         `json:"updated_at"`
}

// Wake schedules (stage 4a, wake_schedules table). Storage layer only: the
// worker/timer that calls ClaimDue is stage 4b. Every statement is a CAS or
// a lease write so two concurrent schedulers can never double-fire an
// occurrence (SCHED-1/SCHED-2).
func (q *Queries) InsertWakeSchedule(ctx context.Context, arg InsertWakeScheduleParams) (WakeSchedule, error) {
	row := q.queryRow(ctx, q.insertWakeScheduleStmt, insertWakeSchedule,
		arg.ID,
		arg.OwnerSessionID,
		arg.Kind,
		arg.Message,
		arg.NextRunAt,
		arg.EveryMs,
		arg.MaxRuns,
		arg.UntilAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WakeSchedule
	err := row.Scan(
		&i.ID,
		&i.OwnerSessionID,
		&i.Kind,
		&i.Message,
		&i.NextRunAt,
		&i.EveryMs,
		&i.MaxRuns,
		&i.UntilAt,
		&i.State,
		&i.Occurrence,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueWakeSchedules = `-- name: ListDueWakeSchedules :many
SELECT id, owner_session_id, kind, message, next_run_at, every_ms, max_runs, until_at, state, occurrence, lease_owner, lease_expires_at, created_at, updated_at FROM wake_schedules
WHERE state = 'active' AND next_run_at <= ?
  AND (lease_owner IS NULL OR lease_expires_at <= ?)
ORDER BY next_run_at ASC, id ASC
LIMIT ?
`

type ListDueWakeSchedulesParams struct {
	NextRunAt      int64         `json:"next_run_at"`
	LeaseExpiresAt sql.NullInt64 `json:"lease_expires_at"`
	Limit          int64         `json:"limit"`
}

// The due, claimable rows, soonest first, bounded by the caller's limit.
// Read INSIDE the claim transaction: the writer connection holds the write
// lock from BEGIN, so nothing can lease them out before the CAS below.
func (q *Queries) ListDueWakeSchedules(ctx context.Context, arg ListDueWakeSchedulesParams) ([]WakeSchedule, error) {
	rows, err := q.query(ctx, q.listDueWakeSchedulesStmt, listDueWakeSchedules, arg.NextRunAt, arg.LeaseExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WakeSchedule{}
	for rows.Next() {
		var i WakeSchedule
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSessionID,
			&i.Kind,
			&i.Message,
			&i.NextRunAt,
			&i.EveryMs,
			&i.MaxRuns,
			&i.UntilAt,
			&i.State,
			&i.Occurrence,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWakeSchedulesForOwner = `-- name: ListWakeSchedulesForOwner :many
SELECT id, owner_session_id, kind, message, next_run_at, every_ms, max_runs, until_at, state, occurrence, lease_owner, lease_expires_at, created_at, updated_at FROM wake_schedules WHERE owner_session_id = ? ORDER BY next_run_at ASC, id ASC
`

func (q *Queries) ListWakeSchedulesForOwner(ctx context.Context, ownerSessionID string) ([]WakeSchedule, error) {
	rows, err := q.query(ctx, q.listWakeSchedulesForOwnerStmt, listWakeSchedulesForOwner, ownerSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WakeSchedule{}
	for rows.Next() {
		var i WakeSchedule
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSessionID,
			&i.Kind,
			&i.Message,
			&i.NextRunAt,
			&i.EveryMs,
			&i.MaxRuns,
			&i.UntilAt,
			&i.State,
			&i.Occurrence,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDueWakeScheduleAt = `-- name: NextDueWakeScheduleAt :one
SELECT MIN(next_run_at) AS next_due_at FROM wake_schedules WHERE state = 'active'
`

// Earliest next_run_at among active rows, for the scheduler's timer.
func (q *Queries) NextDueWakeScheduleAt(ctx context.Context) (interface{}, error) {
	row := q.queryRow(ctx, q.nextDueWakeScheduleAtStmt, nextDueWakeScheduleAt)
	var next_due_at interface{}
	err := row.Scan(&next_due_at)
	return next_due_at, err
}

const recoverExpiredWakeLeases = `-- name: RecoverExpiredWakeLeases :execrows
UPDATE wake_schedules
SET lease_owner = NULL, lease_expires_at = NULL, updated_at = ?
WHERE state = 'active' AND lease_owner IS NOT NULL AND lease_expires_at < ?
`

type RecoverExpiredWakeLeasesParams struct {
	UpdatedAt      int64         `json:"updated_at"`
	LeaseExpiresAt sql.NullInt64 `json:"lease_expires_at"`
}

// Lease recovery: a claimed row whose lease expired without firing goes
// back to unclaimed. The row was never fired (firing clears the lease in
// the same tx as the advance), so no duplicate is possible (SCHED-2).
func (q *Queries) RecoverExpiredWakeLeases(ctx context.Context, arg RecoverExpiredWakeLeasesParams) (int64, error) {
	result, err := q.exec(ctx, q.recoverExpiredWakeLeasesStmt, recoverExpiredWakeLeases, arg.UpdatedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
